### ISSUE TITLE
4-wheeled car example, need help

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#102]
I added an example called wheels.py. 

https://github.com/siconos/siconos/blob/master/examples/Mechanics/MechanicsIO/wheels.py

Can anyone tell me why it leads to solver failures?

**Comment by radarsat1** [comment]
I should mention that if I remove everything except wheel1 body and spin1 boundary condition (to give angular velocity) it also explodes.

Partly this may be because Bullet does not handle rolling contact very well, but I think there is some issue with solving such a system.

**Comment by vacary** [comment]
On master ?

**Comment by radarsat1** [comment]
I'm getting better results by using torque instead of boundary conditions but still lots of local solver failures.  Still experimenting.  I may update the example later, or add a new one.  I can also reduce the number of joints by putting two wheels in the same DS, which helps.

**Comment by radarsat1** [comment]
I will also mention that I get much better rolling behaviour by replacing the ground with a heightmap.  I believe this is because it creates multiple contacts instead of just one that fails to move during rolling.

**Comment by vacary** [comment]
The velocity are really large > 1e+4 in most of the time--step . It is normal ?

Vincent.

**Comment by radarsat1** [comment]
I just want it to roll at a normal pace ;)  I found it exploded and flew away after the "Local solver FAILED" messages, so probably it is not normal.

**Comment by vacary** [comment]
The solver output is nan.

**Comment by radarsat1** [comment]
Yeah, I've been experimenting a lot, I added something to print out the type of problem whenever local solver fails.  It is 90% of the time an fc3d problem.  This is when using forces/torques, rather than BC.  It seems the solver has a hard time with fc3d problems when there are also joints.  I definitely had some issues with misplaced joint pivots before, but I think they are correct here.  However, you'll notice that in my Gazebo examples, the solver slows down drastically as soon as there are both collisions and articulations.  I don't fully understand, but the presence of EqualityConditionNSLs seem to be making for ill-conditioned impact-friction problems.

**Comment by vacary** [comment]
I do not if the problem is coherent or not. With a small time step, the solution diverges slowly to infinity.

**Comment by radarsat1** [comment]
I added a better-working car example.  During the solution of this I still get a lot of local solver errors, but it does not explode:

https://github.com/siconos/siconos/blob/master/examples/Mechanics/MechanicsIO/wheels2.py

https://www.dropbox.com/s/8x1zt6ptpgbl9ze/wheels2.mp4

**Comment by bremond** [comment]
> I believe this is because it creates multiple contacts instead of just one that fails to move during rolling.
If the contacts are only wheel - ground you can (must!) pass
multipoints_iterations=False to mechanics_io run function.

With the multiple contact points that Bullet gives, a sphere or a
cylinder does not roll on the ground! And with those boundary conditions
(and even with a torque), the problems are probably impossible to solve.

With the heightmap you may have less contact points (I don't know, this
may happen if you hit an edge or a vertice?), but this will not cancel
the probability to have several ones.

The way bullet gives thoses multiple points is a major issue, I think, for
Siconos. Even if they are needed (a box on the ground) they may change
at each time step, and for the solver it is like to start without any
knowledge. For a box on the ground it is more efficient to set
multipoint_iterations to False and create the contactors wou want (some
little spheres at each vertices, or some cylinders for the edges). For a
wheel on the ground, just set multipoints_iterations to False.

**Comment by vacary** [comment]
I have also that I introduced a bug in the Newton loop in my recents commit.

see the log for h =0.00001  (http://www.inrialpes.fr/bipop/people/acary/Research/screen.log)

**Comment by radarsat1** [comment]
This is improved by commit 5fb187a10abede36b59d1469571ef2d006c4793b, which puts updateInteractions() inside the newton loop.

I hope it doesn't introduce errors if the newton loop is iterated more than once?

However it seems to help produce resolvable problems.  But see #103, I am wondering if we should be calling the collision engine based on *free* position instead of the solved state.

**Comment by radarsat1** [comment]
See #103 for why that last comment was a wrong intuition ;)  After working with it quite a bit today I am convinced that 5fb187a solves this issue.  I will update the file and close this.
