### ISSUE TITLE
Sitting, sliding, and rolling penetration

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#106]
I have been studying the problem of objects falling through the floor during sitting, sliding, and rolling.  It appears to be related to problems with contact point generation, which is not surprising.  The contact points when the object in tetra.py is just sitting there tend to appear and disappear.  This is exaggerated more when an object is rolling or sliding.

I found that increasing the iterations given to the perturbation algorithm helps immensely at least in the "sitting" case.  Increasing it to 5 for both parameters (iterations and minimum desired points) makes the tetra.py and cube.py stable.  I have made this the default for now, but let's discuss.

I have added a file, slide_roll.py, which throws various objects (tetra, box, cylinder, sphere) across the floor.  The higher the velocity the more the problem.  It seems that even at low velocities there are problems especially with rolling.

Note that increasing time precision and solver precision does not seem to help, it is really a problem in the stability of contacts.  Especially in rolling and sliding, the generated contacts do not always "follow" the object.  There is also the "contact processing threshold".  I have added this and the separate iterations and desired contact points perturbation parameters as Bullet-specific options to make experimentation easier.

It's possible this is not easily resolvable, and I may experiment with other contact engines entirely.  But I make an issue here to collect information.  I know that I am not the first one to explore these parameters :)

**Comment by radarsat1** [comment]
I should mention that this appears to be more of a problem for Siconos than for Bullet. I think it is because Bullet attempts to do some position-correction, whereas (in Mechanics IO) we are working purely at the velocity level at the moment.

**Comment by radarsat1** [comment]
Thinking more on this:

* For sitting, the problem was pretty clearly that contacts were disappearing.  It was not so much related to margins and other things, but just the limited number of points per surface.  Increasing perturbation points helps because the contacts are more stable across timesteps; even though it may add variables to the contact problem, it should actually make the solver globally faster, since there is more coherence between solutions in time (e.g. in stacking problems), and therefore we should benefit more from reusing previous solutions.

* For sliding, increasing perturbation points helps but the faster it slides, the more are needed.

* For rolling, it is clear that perturbation helps but does not solve the problem.  Even with a large number of perturbation points, deep penetration still occurs.

I think that for the rolling case, the reason is that as angular velocity increases, the position of needed contact points gets further and further along the rolling surface.  Since the perturbation angle is limited, increasing the number of points within the same angle doesn't help.  What is needed is to increase the perturbation angle as angular velocity increases.  I don't know if this is possible in Bullet, but maybe I'll look into it.

For sliding, I am less sure what is going on, but it seems that the faster the object is sliding, the more penetration occurs: it follows that the lack of adequate contact points at the *next* location doesn't give Siconos a chance to push against gravity.  Probably as the object moves faster, more points are not even on the object in the "free state".

## Predictive contact point generation?

What sliding and rolling seem to have in common is a lack of predictive power of where gap distances are needed for measuring contact at the location where the object will end up.  This is because we don't take velocity (linear or angular) into account in contact point generation.

So an idea that occurred to me is that we might benefit in both cases from stepping forward in time to predict contact points.  This could be done in a few ways:

1. Step forward two time steps, generate contact points, and project the surface points back to the location corresponding to the previous time step.
2. Consider the contact points in the *free state*, i.e. integrate the free velocity *only* for the purpose of contact point detection, and again we'd have to move the surface points back to the real locations.  (i.e. my ramblings in #103 were maybe not so useless.)
3. Try to take advantage of Bullet's velocity-aware contact detection.

Both ideas 1 and 2 are not completely trivial, probably changing where computeInput() is called from.. i.e. requiring an iteration step after computeState(), or calling it again after computeFreeState().  I am not sure.  But at least the idea would generalize to "any" contact engine.

3 will take some experimentation, a bit of work with "kinematic objects".

**Comment by vacary** [comment]
Thank you for this very argumented discussion. I have some questions/comments for you

- how are the inertia ? It is possible to set a diagonal inertia matrix to be sure that Coriolis are not involved 
- Is the Jacobian matrix of the constraints for NewtonEulerDS system, JacHqT updated in the Newton loop ? For a correct update in the newton loop, we need to update the geometry in Bullet at each newton iteration. If it is not the case, the correction of the velocity is only made such that the contact velocity remains in the tangent plane at the beginning of the step. If we roll at lot, this tangent is largely wrong at the end at convergence and we have some violation of the constraints (see BallinBowl example)
- This can be corrected with the projection schemes. After correcting the velocity in the tangent plane, we project the coordinates of the system such that the constraints at the position level are satisfied. This solution can be applied without updating JacHqT and therefore is cheaper. If we do both (update JAchqT and projection), the convergence of the newton loop is faster but each iteration is more expensive.
- Is it possible to implement the same  example with the spheres that comes from the native implementation to evaluate what is the magnitude of the drift of the constraint manifold. It will allow to understand if Siconos is not computing well, or if Bullet does not output correct contact points or if the coupling between Siconos and bullet is too loose.

**Comment by radarsat1** [comment]
* Inertia is ok I think, the objects in slide_roll.py are not very oblong. I will check the matrices however.

* I think you are right about needing to recalculate collision geometry during the Newton loop. This is one of the reasons for improvements since 5fb187a10abede3.  In fact we were _never_ updating the geometry inside the loop, since even before all my changes, we were calling buildInteractions() before the Newton loop, so I think it should be quite improved now.  However, one implication is that if geometry is updated during Newton loop, this might perturb any finite difference performed in Bullet for velocity estimation, so it might mess up the possibility to use Bullet's CCD algorithms. Better to provide Bullet with velocity information if we can.  Also, with updateInteractions() called in the middle of the Newton loop, we are actually removing and adding Interactions during the loop, which could be questionable, but it seems to be ok.  

* Yes, I think Combined Projection schemes should help drastically with this. However, I think it's still worth it to find good solutions in the velocity-only case.  But I definitely want to get the position constraints working, it must be an option for users.

* Good idea to compare with native implementation. I still need to "port" them to the InteractionManager / SiconosShape interface.  I have not looked into the contact detection scheme used in that code.  I don't think it's that Bullet is outputting "incorrect" contact points in the general case, but it is not correctly outputting predictive constraints for fast-moving objects, and it uses cached constraints, which during fast sliding, go out of date very quickly and so some kind of look-ahead may be needed.  If you look for "Bullet physics sliding" you will find some discussions of this, it is all very heuristic.  I am wondering if predicting ahead by one timestep in the collision geometry (and combining the two sets of contacts) could be a solution.

* Previously we were rebuilding the collision world at each timestep, which would have invalidated any cached constraints and would have had an effect on sliding.  But I am not sure if it would be a good effect or a bad effect.  It might be interesting to make it an option, or at least to experiment with it.

* Yes, I think trying Bullet's CCD is a good idea.

**Comment by radarsat1** [comment]
Interesting discovery: In Bullet, gBreakingContactThreshold is used as an heuristic for choosing the perturbation angle.  If I increase gBreakingContactThreshold x10, it has ill effects on impact and sliding contacts.  However, if I leave gBreakingContactThreshold at default (0.02) and change only this line in Bullet's btConvexConvexAlgorithm.cpp:

    perturbeAngle = gContactBreakingThreshold /radiusA

to

    perturbeAngle = 0.4 / radiusA

and also the corresponding line for `radiusB`, then all objects in slide_roll.py behave correctly.  That is to say, they do not fall through the surface during sliding, rolling, or sitting.  Although, they don't always roll "straight".

This confirms my idea that more contact points around the curvature are needed during rolling.  It's unfortunate that Bullet confounds this with the breaking threshold and doesn't offer a separate "perturbation angle scaling" variable.

However, due to the fact that rolling isn't straight, I suspect it would be better to take angular velocity into account while generating contacts, rather than relying on perturbations.

**Comment by vacary** [comment]
With respect to your last comment, I found that the use of this constant into two different place for two distinct procedures was quite dangerous. But  I suppose that the author of Bullet has an heuristic for justifying this point.  

Perhaps a discussion and a patch to Bullet would be valuable? I think a comparison with the native implementation would be very interesting

**Comment by vacary** [comment]
For other points 

- inertia is not involved since we have a sphere in the example

**Comment by radarsat1** [comment]
Well, I just discovered that positions are updated once at the start of the Newton loop.  So, after putting an extra call to updateInteractions() after initializeNewtonLoop(), sliding and rolling seems to work much better.  (33279a4bc)

**Comment by radarsat1** [comment]
I'll continue documenting my findings.  I have found the real reason for floor penetration in the sliding case.  It is again an idiosyncrasy of gContactBreakingThreshold!  But a different one.  It has to do not with how contacts are calculated, but how they are cached in btPersistentManifold.  This explains why increasing the number of perturbation points did improve things, but not *always*. Even when extra points are calculated, they may not be stored.

When a contact point is newly calculated, it is added to the btManifoldResult using btManifoldResult::addContactPoint().  In that routine, two things happen regarding contact point storage.  Recall that btPersistentManifold is a structure holding an array of btManifoldPoint.  This array is actually, statically exactly 4 objects long.  A btPersistentManifold may store up to 4 contact points.  Then,

1. The index into the array in btPersistentManifold is determined by btPersistentManifold::getCacheEntry().  This routine **finds the index of the point on the manifold that is both closest to the new contact point, and closer than getContactBreakingDistance()**.

2. If an existing "close" point was found, btPersistentManifold::replaceContactPoint() is called.  Otherwise, btPersistentManifold::addManifoldPoint() is called.

This last routine, addManifoldPoint(), adds the discovered point to the btPersistentManifold(), and if there is no room, it replaces the first point.  (In an #ifdef'd-out variation, it sorts the points according to their distance to the new point.)

3. Finally, the cached contact points are updated with the new body transforms (positions).  (i.e. this has the effect of updating position and distance information for replaced points)

I will note here that Bullet's dynamics engine updates contact points based on the free state, something I have been thinking about for Siconos.  That is, it calls performDiscreteCollisionDetection() between predictUnconstraintMotion() and solveConstraints(), integrateTransforms(). (See btDiscreteDynamicsWorld::internalSingleStepSimulation())

### To summarise

The falling-through-the-floor effect is caused by **too few points in a contact manifold being stored.**  This is because either they are too close to existing cached points, or they are closer than gContactBreakingThreshold.  Indeed, setting gContactBreakingThreshold absurdly low fixes the problem in most cases. 

I did notice that setting it like that in tetra.py (h=0.001, gContactBreakingThreshold=1e-7) actually still allows the object to gradually penetrate into the floor, albeit much slower than before.  The reason is that new contact points seem to "take turns" replacing each other, in vview you can see them disappearing one at a time from the corners of the tetrahedron and being replaced in the next timestep.

Changing the Bullet code to always replace the first contact point regardless of closeness actually completely fixes the problem.  However, that is not a very general solution, and requires changes to Bullet.

### Conclusion

Ideally Bullet would contain some kind of logic to generate at least 3 stable contact points per surface, otherwise surface-surface resting is impossible.  For the record I still *do not understand* why this is not a problem for Bullet itself and seems to only manifest in our use with Siconos.  Maybe something to do with its predictive contacts and position-correcting impulses.

However, one would think that rather than replacing "close" contact points, a better logic would be to maintain the 3 or 4 most separated points, for numerical stability.  Although during sliding, it would be necessary to take velocity into account--more points in the sliding direction?  It would be even better, I think, to allow the user to override this logic with a callback.  Either way, I am not sure this is a good use of gContactBreakingThreshold, which I already thought was overloaded with its use in determining perturbation angle, and I will look into a proposal to fix it in Bullet.  In the meantime I am trying to think of the best fix for Siconos "now".

Possibly setting gContactBreakingThreshold very low is "good enough", but this has the disadvantage of ruining contact caching for small bounces, and additionally didn't completely fix the problem for tetra.py.  Another possibility is setting the btPersistentManifold's breaking and processing thresholds used for this logic, which are related to, but independent of gContactBreakingThreshold.

I am experimenting with a few solutions and will commit something that seems like a good compromise soon.  In parallel I think discussing this on the Bullet Physics forum might be fruitful.

**Comment by radarsat1** [comment]
I should mention that this replacing of contact points one with another within the btPersistentManifold's contact points array means that we are very potentially re-using lambda values from previous iterations that are related to *different contacts*.  Especially in certain circumstances where this contact point "cycling" behaviour can be see, as I have observed in tetra.py, even though contact points appear persistent from Siconos point of view, the lambda values from the previous step are possibly associated with different contact points.  In other words, we cannot assume that because the btManifoldPoint address is the same, that it refers to the same contact point!  It even copies the user pointer data while moving the points associated with the contact point, so an Interaction and Relation may end up being associated with a different contact point at future steps.  I see no way to detect this for now.

(This is part of Bullet's "closest point" logic, of course-- likely lambda values are related, since replaced points are guaranteed to be close.  Still a bit of a surprise, however, so I note it here.)

Even the lifetime counter of the contact point is a "lie" and is copied from the replaced point!  All this is enabled by default, but is actually controlled by a #define MAINTAIN_PERSISTENCY in btPersistentManifold.h.  This reaffirms that although some thought has gone into whether or not this is a good idea, no one has made a concrete proposal to improve it, so I imagine a discussion will be well received in the Bullet forum.

**Comment by radarsat1** [comment]
Some links, to see what I'm going on about:

[getCacheEntry()](http://bulletphysics.org/Bullet/BulletFull/btPersistentManifold_8cpp_source.html#l00188)

[replaceContactPoint()](http://bulletphysics.org/Bullet/BulletFull/btPersistentManifold_8h_source.html#l00175)

**Comment by radarsat1** [comment]
Re-opening because after quite a bit of testing with various parameters (timesteps, margins, shapes, number of Newton iterations, number of calls to performDiscreteCollisionDetection, etc.), I am unable to find a "best value" for the contact breaking threshold that actually causes contact detection to work adequately under a wide variety of conditions.  The main problem is that some simulations tend to end up in this cyclical behaviour where they switch between 1 and 2, or 1 and 3, or 2 and 4 contacts from timestep to timestep.  This is a significant problem because when it occurs, the time to perform the simulation can go from a few seconds to a few minutes, simply because Interactions are not correctly retained.  Either a fix in Bullet is required, or some different approach where we retain Interactions longer than Bullet.

**Comment by radarsat1** [comment]
Ok forget everything above.  After applying the patch e4a524926d43 that avoids storing pointers to btManifoldPoint, I have been unable to reproduce the contact problems, even with setting the contact breaking threshold very small or very large.  So it seems this was all a classic, stupid **bug** after all!

before applying e4a524926d43:
![before_patch](https://cloud.githubusercontent.com/assets/66805/23380034/f976066e-fd17-11e6-9ed2-b620810b87f0.gif)

after applying e4a524926d43:
![after_patch](https://cloud.githubusercontent.com/assets/66805/23380040/fe4acb20-fd17-11e6-9b0b-4bfc4c57ccf7.gif)

I will continue to test.

**Comment by vacary** [comment]
>  I have been unable to reproduce the contact problems,

Nice. I like the way you say that. Finally, could you sum up what remains to do. All your unit test examples are working now ? Do we need to apply a patch to Bullet to use it correctly ?

**Comment by radarsat1** [comment]
"definitive" :)

I have gone back and forth quite a bit convincing myself of one solution or the other, but now that I understand more in detail how btPersistentManifold works, it does seem that we were pointing to bad memory, and the contact data was changing under the pointer to btManifoldPoint, therefore it is reassuring that fixing this made the contacts work more consistently.  With this fixed, no changes to Bullet seem necessary, but I will continue to monitor.  However, as some changes were made that seem to "fix" the issue, I will close this for now and open a new bug if more problems are identified.
