### ISSUE TITLE
Constraints at the position level for mechanical systems

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#108]
Form the beginning of Siconos, we extensively the Moreau--Jean scheme for the integration of mechanical systems. One of the very nice feature of the scheme is the treatment of the constraints at the velocity level together with the impact law. Some other schemes (Schatzman-Paoli, D1MinusLinear) treats the constraints at the position with the impact law.

The goal of this issue it to start to assess constraints at the position level in MoreauJeanOSI when it is really needed, mainly for:
- compliant contact laws (Hertz, piecewise linear with stiffness and damping, ...)
- cohesive zone model (CZM)
- Quasi-static application for finite-element techniques (see Jean Cmame 1999)

**Comment by radarsat1** [comment]
Just a question, is this *distinct* from the ideas in MoreauJeanCombinedProjectionOSI?  (Which, as I understand, solves the position and velocity constraints separately but iteratively converges on a common solution.)

**Comment by vacary** [comment]
Yes, very distinct.

In MoreauJeanCombinedProjectionOSI, we solve the constraints with the impact law at the velocity level and then we add a correction of the position to satisfy the constraints at the position level. this is the reason we need lambda[0] and lambda[1].

If we have only constraints at the position level, we need only lambda[0] and the impact law is not necessary. If we have cohesion, we have to implement a switch when the cohesive surface is broken to come back to lambda[1] and a velocity level constraints.

**Comment by radarsat1** [comment]
But there will in general be a mix of cohesion and impact constraints, right?  The state would be in the Interaction.  Initially all Interactions would be in cohesive state, but could switch to non-cohesive, while *new* interactions are always non-cohesive.  So the use of lambda[0] / lambda[1] is independent for each Interaction?

**Comment by vacary** [comment]
Yes exactly.
Normally, it is possible to have an independent use of  lambda[0] / lambda[1] in each interaction. For the sake of simplicity, we initialize the interactions with the min and max level that is needed for all interactions in the simulation.  The initialization depends on the model and the numerical technique you want to use.

**Comment by radarsat1** [comment]
Ah, I did not realize that could be dynamic per Interaction per timestep.  Very nice.  Time to experiment then ;)

**Comment by vacary** [comment]
:-) I do not say that everything works perfectly

**Comment by radarsat1** [comment]
Summary:
* Make example using position-level constraint (bouncing ball)
* Update MoreauJeanOSI to enable position level
* Implement position impact constraint formulation as LCP.

**Comment by vacary** [comment]
creation of the example (8ae6d87c2f13f45c16559cfd79097f0c3f76d3a3)

**Comment by vacary** [comment]
A first silly computation with compliant contact at the position level (5871b4aeaf6543e7a017f82300f873fda4d9fd64)

Finally, I am not using lambda[0] since we introduce only lambda[1] in the velocity dynamics for MoreauJeanOSI so it is simpler as I guessed.

It has to be improved in many ways:
- since I work with the percussion lambda[1] as an approximation of the integral of non impulsive contact  h f_k+1 . We should work directly with the non impulsive contact force f_k+1 to get a consistent integrator
- we need also to perform the integration of   non impulsive contact force with the theta scheme to avoid numerical dissipation.

**Comment by radarsat1** [comment]
Thanks, looking at it.

**Comment by radarsat1** [comment]
Very cool!

![bouncingball-compliant](https://cloud.githubusercontent.com/assets/66805/23078181/5ddf84d0-f526-11e6-909c-a9feda3883ea.png)

**Comment by vacary** [comment]
Transferred in wiki

https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
