### ISSUE TITLE
[swig] "precedence level in typecheck typemap for 'double'" errors in the kernel

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#109]
When generating the python bindings with  077e2ef I got the following issues:

/home/xhub/siconos-tmp/kernel/src/utils/SiconosAlgebra/SimpleMatrix.hpp:168: Warning 467: Overloaded method SimpleMatrix::SimpleMatrix(int) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'int').
/home/xhub/siconos-tmp/kernel/src/utils/SiconosAlgebra/SimpleMatrix.hpp:189: Warning 467: Overloaded method SimpleMatrix::SimpleMatrix(unsigned int,unsigned int,double) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/utils/SiconosAlgebra/SimpleMatrix.hpp:189: Warning 467: Overloaded method SimpleMatrix::SimpleMatrix(unsigned int,unsigned int,double,Siconos::UBLAS_TYPE) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/utils/SiconosAlgebra/SimpleMatrix.hpp:189: Warning 467: Overloaded method SimpleMatrix::SimpleMatrix(unsigned int,unsigned int,double,Siconos::UBLAS_TYPE,unsigned int) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/utils/SiconosAlgebra/SiconosVector.hpp:85: Warning 467: Overloaded method SiconosVector::SiconosVector(unsigned int,double) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/modelingTools/DynamicalSystem.hpp:0: Warning 509: Overloaded method DynamicalSystem::addWorkVector(SiconosVector const &,DynamicalSystem::DSWorkVectorId const &) effectively ignored,
/home/xhub/siconos-tmp/kernel/src/modelingTools/DynamicalSystem.hpp:0: Warning 509: as it is shadowed by DynamicalSystem::addWorkVector(SP::SiconosVector,DynamicalSystem::DSWorkVectorId const &).
/home/xhub/siconos-tmp/kernel/src/modelingTools/DynamicalSystem.hpp:0: Warning 509: Overloaded method DynamicalSystem::subWorkVector(SiconosVector const &,DynamicalSystem::DSWorkVectorId const &) effectively ignored,
/home/xhub/siconos-tmp/kernel/src/modelingTools/DynamicalSystem.hpp:0: Warning 509: as it is shadowed by DynamicalSystem::subWorkVector(SP::SiconosVector,DynamicalSystem::DSWorkVectorId const &).
/home/xhub/siconos-tmp/kernel/src/modelingTools/NewtonEulerDS.hpp:0: Warning 467: Overloaded method rotateAbsToBody(double,double,double,double,SP::SiconosVector) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/modelingTools/FirstOrderNonLinearDS.hpp:0: Warning 467: Overloaded method FirstOrderNonLinearDS::computeJacobianfx(double,bool) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/simulationTools/TimeDiscretisation.hpp:0: Warning 467: Overloaded method TimeDiscretisation::TimeDiscretisation(double,std::string const &) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').
/home/xhub/siconos-tmp/kernel/src/simulationTools/Simulation.hpp:0: Warning 467: Overloaded method Simulation::oneStepNSProblem(int) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'int').
/home/xhub/siconos-tmp/kernel/src/simulationTools/TimeStepping.hpp:0: Warning 467: Overloaded method TimeStepping::TimeStepping(PyObject *,SP::TimeDiscretisation,int) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'int').
/home/xhub/siconos-tmp/kernel/src/simulationTools/EventsManager.hpp:0: Warning 467: Overloaded method EventsManager::insertEvent(int,double) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'int').
/home/xhub/siconos-tmp/kernel/src/modelingTools/HarmonicBC.hpp:0: Warning 467: Overloaded method HarmonicBC::HarmonicBC(SP::UnsignedIntVector,double,double,double,double) not supported (incomplete type checking rule - no precedence level in typecheck typemap for 'double').

A precedence=SWIG_TYPECHECK_DOUBLE may do the trick?

**Comment by radarsat1** [comment]
Didn't catch that, I'll try to fix.

**Comment by xhub** [comment]
I think this is fixed now. Thanks for taking care of it and make the code way nicer
