### ISSUE TITLE
[kernel] Interaction.upperLevelForInput() < 0 is always false

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#110]
Build of the kernel are failing because we check for something that is always false, cf
http://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=24687

Should this condition be replaced by Interaction.upperLevelForInput() == 0?

**Comment by vacary** [comment]
fixed via (48d851d22bbdf32080182f3fdad2eecfc8e271e9)
