### ISSUE TITLE
Prismatic joint disconnects

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#113]
I have been trying to understand why joints are difficult to keep together.

Here is a script that demonstrates some objects bouncing while they are connected via a prismatic joint.  At first it runs fine, but eventually it leads to quite a lot of solver failures ("Local solver FAILED, GS continue") despite the high precision settings, and one can see the two bodies eventually separate, although they stay in the same orientation.  It seems the prismatic joint is good at keeping co-orientation but not good at keeping them co-linear.

Is this just the failure mode due to enforcing the joints purely on the velocity level?  i.e., an accumulation of position error when the solver fails to find a velocity that enforces the constraint?  In that case, once they are disconnected, the velocity constraint continues to keep them apart.

~~~
#!/usr/bin/env python
from siconos.mechanics.collision.tools import Contactor
from siconos.io.mechanics_io import Hdf5
import siconos.numerics as Numerics

with Hdf5() as io:
    io.addPrimitiveShape('Bar', 'Box', (0.1, 0.1, 1))
    io.addPrimitiveShape('Ground', 'Box', (10, 10, .5))
    io.addNewtonImpactFrictionNSL('contact', e=0.8, mu=0.2)
    io.addObject('ground', [Contactor('Ground')],
                 translation=[0, 0, 0])

    o = [(1,0,0), 0.1]
    io.addObject('bar1', [Contactor('Bar')], translation=[-0.055, 0, 3.5], mass=1,
                 orientation=o)
    io.addObject('bar2', [Contactor('Bar')], translation=[0.055, 0, 3], mass=1,
                 orientation=o)

    io.addJoint('joint1', 'bar1', 'bar2', [0,0,1], [], 'PrismaticJointR')

with Hdf5(mode='r+') as io:
    io.run(t0=0,
           T=10,
           h=0.001,
           theta=0.50001,
           Newton_max_iter=20,
           solver=Numerics.SICONOS_FRICTION_3D_NSGS,
           itermax=10000,
           tolerance=1e-8)
~~~

![prismatic-test](https://cloud.githubusercontent.com/assets/66805/23617759/e5993710-026c-11e7-8765-66ec0963fc61.gif)

Setting e=0.7 yields even stranger results where one object "hovers" over the other for a while.

![prismatic-test](https://cloud.githubusercontent.com/assets/66805/23618218/6cb5d6ee-026e-11e7-823a-0d9819037a0d.gif)

**Comment by vacary** [comment]
This strange effect is mainly due to velocity level treatment of constraints. It seems that the velocity constraints are always quite good but there is a lot of drift at the coordinate level (translation and rotation).

Have you to reproject onto the constraints with the MoreauJeanDirectProjectionOSI ? 

It could be also good to treat the bilateral constraints at the position level (see  #108) with a consistent treatment of the time integration.

**Comment by radarsat1** [comment]
I found that GenericMechanical is not using the "hybrid" solver, I am trying to improve this.  I have verified that greatly increasing the number of iterations leads to better behaviour, the objects stay together longer, but still diverge when they interact permanently with the ground.  Still many problems do not converge, so I think it must be related to not using the best FC3D solver in GenericMechanical.  I am trying to enable the hybrid solver in this case.

**Comment by radarsat1** [comment]
But indeed, I believe that ultimately it may be due to velocity constraint errors accumulating at the position level, so position treatment may be needed.  Still, I think there is something to improve here, as it doesn't make sense that the equality constraints cause the FC3D problems to be much more difficult to solve.

**Comment by radarsat1** [comment]
Ok I have enabled the HYBRID solver for GenericMechanical in 09ee2679.  However, it does not seem to make a difference.

Note that previously we were changing the "local solver" settings for the LCP solver instead of the friction solver!  (We were switching it from SICONOS_LCP_LEMKE to ONECONTACT_NSN_GP_HYBRID!) Now, SWIG returns internalSolvers as a list instead of a single object.  In GenericMechanical, the friction solver is internalSolvers[1].

**Comment by radarsat1** [comment]
I enabled DirectProjection classes in 8db1b76f5 but there is an error.  I will make a new issue for that.
