### ISSUE TITLE
TimeStepping/MoreauJeanDirectProjectionOSI fails.

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#114]
This is needed for #108 and probably #113.  In 8db1b76f5, I allowed to use TimeSteppingDirectProjection from Python.  Taking an example in MechanicsIO and changing run() to have the following parameters:

    time_stepping=TimeSteppingDirectionProjection,
    osi=MoreauJeanDirectProjectOSI,

also causes mechanics_io.py to create an extra OneStepNSProblem of type MLCPProjectOnConstraints, used to initialize TimeSteppingDirectProjection.  (As in the example program, [BouncingBallNETS.cpp](https://github.com/siconos/siconos/blob/master/examples/Mechanics/NewtonEuler/BouncingBallNETS.cpp).)

Unfortunately this leads to an error with examples I tried on.  (E.g. cube.py)
I tried calling simulation.setProjectionMaxIteration(10000), but it does not fix it.

~~~
No module named siconos.fclib.
load siconos module ...
setup model simulation ...

Simulation will run from 0.0000 to 10.0000s, step 1 to step 20001 (h=0.0005, times=[?,?])

import scene ...
Import  dynamic or static object number  1 from initial state
                object name    cube
Import  dynamic or static object number  -1 from initial state
                object name    ground
Adding shape Ground to static contactor [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
first output static and dynamic objects ...
output static object -1
start simulation ...
step 1 < 20001
output in hdf5 file at step  1

step 2 < 20001
output in hdf5 file at step  2
...

step 500 < 20001
output in hdf5 file at step  500

step 501 < 20001
output in hdf5 file at step  501
number of contacts 0
SolverInfos at time : 0.2505 iterations=  1 precision= 0.0 local_precision=

step 502 < 20001
output in hdf5 file at step  502
number of contacts 0
SolverInfos at time : 0.251 iterations=  1 precision= 0.0 local_precision=

step 503 < 20001
output in hdf5 file at step  503
number of contacts 0
SolverInfos at time : 0.2515 iterations=  1 precision= 0.0 local_precision=

step 504 < 20001
output in hdf5 file at step  504
number of contacts 0
SolverInfos at time : 0.252 iterations=  1 precision= 0.0 local_precision=

step 505 < 20001
output in hdf5 file at step  505
number of contacts 0
SolverInfos at time : 0.2525 iterations=  1 precision= 0.0 local_precision=

step 506 < 20001
output in hdf5 file at step  506
number of contacts 0
SolverInfos at time : 0.253 iterations=  1 precision= 0.0 local_precision=

step 507 < 20001
output in hdf5 file at step  507
number of contacts 0
SolverInfos at time : 0.2535 iterations=  1 precision= 0.0 local_precision=

step 508 < 20001
output in hdf5 file at step  508
number of contacts 0
SolverInfos at time : 0.254 iterations=  1 precision= 0.0 local_precision=

step 509 < 20001
output in hdf5 file at step  509
number of contacts 0
SolverInfos at time : 0.2545 iterations=  1 precision= 0.0 local_precision=

step 510 < 20001
output in hdf5 file at step  510
number of contacts 0
SolverInfos at time : 0.255 iterations=  1 precision= 0.0 local_precision=

step 511 < 20001
output in hdf5 file at step  511
number of contacts 0
SolverInfos at time : 0.2555 iterations=  1 precision= 0.0 local_precision=

step 512 < 20001
output in hdf5 file at step  512
number of contacts 0
SolverInfos at time : 0.256 iterations=  1 precision= 0.0 local_precision=

step 513 < 20001
output in hdf5 file at step  513
number of contacts 0
SolverInfos at time : 0.2565 iterations=  1 precision= 0.0 local_precision=

step 514 < 20001
output in hdf5 file at step  514
number of contacts 0
SolverInfos at time : 0.257 iterations=  1 precision= 0.0 local_precision=

step 515 < 20001
output in hdf5 file at step  515
number of contacts 0
SolverInfos at time : 0.2575 iterations=  1 precision= 0.0 local_precision=

step 516 < 20001
output in hdf5 file at step  516
number of contacts 0
SolverInfos at time : 0.258 iterations=  1 precision= 0.0 local_precision=

step 517 < 20001
output in hdf5 file at step  517
number of contacts 0
SolverInfos at time : 0.2585 iterations=  1 precision= 0.0 local_precision=

step 518 < 20001
output in hdf5 file at step  518
number of contacts 0
SolverInfos at time : 0.259 iterations=  1 precision= 0.0 local_precision=

step 519 < 20001
output in hdf5 file at step  519
number of contacts 0
SolverInfos at time : 0.2595 iterations=  1 precision= 0.0 local_precision=

step 520 < 20001
output in hdf5 file at step  520
number of contacts 0
SolverInfos at time : 0.26 iterations=  1 precision= 0.0 local_precision=

step 521 < 20001
              max criteria equality =  -1.000000e+24.
              max criteria unilateral =  1.192471e-03.
Traceback (most recent call last):
  File "cube.py", line 79, in <module>
    output_frequency=None)
  File "/home/sinclairs/.local/lib/python3.5/site-packages/siconos/io/mechanics_io.py", line 2406, in run
    log(simulation.computeOneStep, with_timer)()
  File "/home/sinclairs/.local/lib/python3.5/site-packages/siconos/io/mechanics_io.py", line 233, in silent
    fun(*args)
  File "/home/sinclairs/.local/lib/python3.5/site-packages/siconos/kernel.py", line 24432, in computeOneStep
    return _kernel.TimeStepping_computeOneStep(self)
Exception: Runtime Exception : youyou
~~~

**Comment by radarsat1** [comment]
I verified that running "siconos BouncingBallNETS.cpp" is successful.  Both flags WITH_PROJ and WITH_FC3D are enabled.

I would hazard a guess that the most striking difference between these cases is that with Mechanics IO and Bullet, the Interactions are dynamic.

**Comment by radarsat1** [comment]
Not a solution, but I found that if I added some calls to updateInteractions() before updateOutput() then the errors I get are related to the OSNSMatrix allocation:

~~~
Exception: Siconos Matrix Exception : SimpleMatrix::setBlock(row,col): row is out of range
~~~

It seems the size(0) and size(1) of that matrix were 0.  I fixed this by adding `_hasBeenUpdated=false` in preCompute so that it would reallocate the dense matrix.

~~~
bool MLCP::preCompute(double time)                                                       
{                                                                                        
  _hasBeenUpdated=false; 
  ...
~~~

Now the cube.py example is able to run.

However I won't commit the change because I am not sure it is the correct way to handle this memory error, and it doesn't work for GenericMechanical (e.g. doublePendulum.py), which gives,

~~~
TimeSteppingDirectProjection::advanceToEvent() project on constraints. solver failed.
~~~

**Comment by radarsat1** [comment]
I will say, on a positive note, that for cube.py is it quite a success!  I am able to run it with a timestep h=0.1 (10 Hz!!) with apparently **zero** penetration.  Compared to normal TimeStepping, where it falls right through the floor.

**Comment by vacary** [comment]
@radarsat1 Did you commit this example ? Perhaps, you can create a branch with your modifications such that I will be able to check what happens

**Comment by radarsat1** [comment]
Check the branch https://github.com/siconos/siconos/tree/directproj
there are 3 examples there.  Depends on my pull request #121, (otherwise DS is not initialized properly) but it could be rebased as necessary.

**Comment by radarsat1** [comment]
The examples are "cube_directproj.py", "n_cubes_directproj.py", and "doublePendulum_directproj.py".  cube_directproj works great, but the others stall for so long that I have had to cancel them.  The n_cubes_directproj stalls after a few hundred steps (with about 12 contacts), but the doublePendulum_directproj stalls on the first timestep.  I will try leaving it overnight to see if it progresses at all or if it's really stopped.

**Comment by radarsat1** [comment]
It seems the reason it gets completely stuck is because there is no limit to the number of iterations of the while() loop in mlcp_enum.c.  If I limit the loop to iparam[0], it terminates early and seems to work ok.

I noticed that TimeSteppingDirectProjection calls TimeStepping::newtonSolve instead of TimeSteppingDirectProjection::newtonSolve.  Any comments on that?  Should TimeSteppingDirectProjection::newtonSolve be removed?

**Comment by radarsat1** [comment]
I just rebased 'directproj' branch again.  Currently reviewing and preparing basic changes for a pull request.  Can anyone comment on the change in 6e2f487627fdaacddd755cd79b339a2fbe8db198?

~~~
 bool MLCP::preCompute(double time)
 {
+  _hasBeenUpdated=false;
   bool res = LinearOSNS::preCompute(time);
   _numerics_problem.n = _n;
   _numerics_problem.m = _m;
~~~

It's really the only thing I'm not sure about here.

**Comment by vacary** [comment]
I have no idea about this change. 
I think we have to be more explicit in the naming of variables such as _hasBeenUpdated, but it seems correct.

**Comment by radarsat1** [comment]
Ok, after looking a little deeper, it seems the real problem was that when interactions are created dynamically, the hasChanged flag gets reset during initOSNS/updateIndexSets and thus ignored when compute() is called.  The better solution was to ensure that hasChanged gets set correctly after calling initOSNS (in updateInteractions) and also to move the call to OSNS->setHasBeenUpdated() from prepareNewtonSolve() to computeOneStepNSProblem().

The latter fix is only because in TimeSteppingDirectProjection, computeOneStepNSProblem is called in the projection loop as well as in the newton loop, so sometimes I got a failure there.  Since setHasBeenUpdated() needs to be called in both cases, prepareNewtonIteration() is not the correct place.  Logically setHasBeenUpdated() simply should always be called before computeOneStepNSProblem(), so it seemed to make sense to just put it there, before compute().
