### ISSUE TITLE
enable SerializersGeneration on CI and remove SiconosFullGenerated.hpp and SiconosFullKernelGenerated.hpp from master

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#116]
The serialization was once again broken. b6c1b002a should fix it and make it easier to generate SiconosFullGenerated.hpp and SiconosFullKernelGenerated.hpp

Since generating those two files only relies on doxygen (which is a simple dependency), I propose we remove those two files from the master. On CI, we would enable WITH_GENERATION and we would add those files to the release branch.

**Comment by xhub** [comment]
The build for serialization is broken again, see http://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=25396 

Any opinion on that? I'll probably try to implement something if no one says anything before that.

**Comment by radarsat1** [comment]
I think it's a great idea to always generate these files, in case they are needed.  In that case, WITH_SERIALIZATION should imply WITH_GENERATION, the latter could even be removed. (But maybe better to leave it.)

Way too annoying to always have to check this every time a member of a class is changed.  (That said perhaps I'll put a commit hook on my computer that compiles Siconos with serialization and all tests enabled before pushing.)

**Comment by vacary** [comment]
Any updates ?

**Comment by xhub** [comment]
I don't think so ... took me a while to remember the details. @vacary what is your opinion?

@radarsat1 Would you like to implement that? I don't have a lot of free time but I could look into that still

**Comment by radarsat1** [comment]
Generation was always broken on some version of Ubuntu, actually I can't repeat the problem now so maybe it was before I upgraded.  In any case, it would mean that to compile Siconos you must have doxygen and python-lxml installed, is that acceptable?  I probably will have more free time for this kind of thing in Feb.

**Comment by xhub** [comment]
I think that we should still commit those files when we branch for a release. For CI, we should build the serialization only on  platform where the generation works
