### ISSUE TITLE
duplicate member variable with name _jacxRhs in DynamicalSystem and LagrangianDS

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#117]
From DynamicalSystem.hpp:
```
  /** jacobian according to x of the right-hand side (\f$ \dot x =
      f(x,t) + r \f$) */
  SP::SiconosMatrix _jacxRhs;
```

From LagrangianDS.hpp
```
SP::BlockMatrix _jacxRhs;
```

I think the declaration in DynamicalSystem.hpp should be moved to FirstOrderNonLinearDS.

Opinions?

**Comment by vacary** [comment]
fixed  by (08c7f54ddcf2dba19498992b41f2b5b811116afa)
