### ISSUE TITLE
How to initialize DS now, after recent refactor?

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#119]
I am adapting my code to the latest refactor, where a lot of initialization functions have changed.  I am having to make some guesses based on the diff, it would be nice to get an overview of the changes.  In any case, mostly it is clear, but I when initializing a new dynamically-added DynamicalSystem, I have a problem that I can't resolve so clearly.  I removed the call to DynamicalSystem::initialize(), since it seems that was removed.  However, now it crashes during Topology::initDS() because the workVector pointer is null.

This is the complete sequence I am using to initialize a new DS:

* model->nonSmoothDynamicalSystem()->insertDynamicalSystem(ds);
* model->nonSmoothDynamicalSystem()->topology()->setOSI(ds, osi);
* model->nonSmoothDynamicalSystem()->topology()->initDS(model, nextTime, ds, osi);
* ds->initialize(nextTime, osi->getSizeMem())  **removed**
* simulation->initialize(model, false)

Previously this worked, but now there is a segfault in MoreauJeanOSI::initializeDynamicalSystem(), called from Topology::initDS(), due to workVector==NULL.  (*_dynamicalSystemsGraph->properties(dsv).workVectors)  What step am I missing to initialize it?

**Comment by radarsat1** [comment]
Ok I found that the initialization of workVectors was commented-out in Topology::insertDynamicalSystem, so assuming this is on purpose, I moved the initialization to where it is needed in MoreauJeanOSI::initializeDynamicalSystem().  Probably this then needs to be done in every OSI, or we should put it in a function in OneStepIntegrator.

Please advise if the solution in https://github.com/siconos/siconos/commit/3be9667fc2dc5c9975e13b6f28c2cad33933b692 is acceptable.

**Comment by vacary** [comment]
It seems that your solution is correct. I think it is a side effect of our work on lazy initialization.

My question is: why was it working for a dynamical system that is created at the beginning of the simulation ?

**Comment by vacary** [comment]
ok, I got it It has been written in the initialize of OSI that is calls only when we initialize the Simulation. 

@fperignon Most of the code that you have factorized there:
~~~
  DynamicalSystemsGraph::VIterator dsi, dsend;
  for(std11::tie(dsi, dsend) = _dynamicalSystemsGraph->vertices(); dsi != dsend; ++dsi)
  {
    if(!checkOSI(dsi)) continue;
    SP::DynamicalSystem ds = _dynamicalSystemsGraph->bundle(*dsi);
    _dynamicalSystemsGraph->properties(*dsi).workVectors.reset(new VectorOfVectors());
    _dynamicalSystemsGraph->properties(*dsi).workMatrices.reset(new VectorOfMatrices());
    // Initialize memory buffers
    ds->initMemory(getSizeMem());
    // Force dynamical system to its initial state
    ds->resetToInitialState();
    // part of the work which depends on osi and/or DS types.
    initializeDynamicalSystem(m, t0, ds);
  }
~~~

should (or must) be in in the initializeDynamicalSystem. This other way is to create a generic  initializeDynamicalSystem in OneStepIntegrator and call it in the inherited method initializeDynamicalSystem

What do you think ?

**Comment by fperignon** [comment]
> Le 30 mars 2017 à 09:06, Vincent Acary <notifications@github.com> a écrit :
> 
> ok, I got it It has been written in the initialize of OSI that is calls only when we initialize the Simulation.
> 
> @fperignon <https://github.com/fperignon> Most of the code that you have factorized there:
> 
>   DynamicalSystemsGraph::VIterator dsi, dsend;
>   for(std11::tie(dsi, dsend) = _dynamicalSystemsGraph->vertices(); dsi != dsend; ++dsi)
>   {
>     if(!checkOSI(dsi)) continue;
>     SP::DynamicalSystem ds = _dynamicalSystemsGraph->bundle(*dsi);
>     _dynamicalSystemsGraph->properties(*dsi).workVectors.reset(new VectorOfVectors());
>     _dynamicalSystemsGraph->properties(*dsi).workMatrices.reset(new VectorOfMatrices());
>     // Initialize memory buffers
>     ds->initMemory(getSizeMem());
>     // Force dynamical system to its initial state
>     ds->resetToInitialState();
>     // part of the work which depends on osi and/or DS types.
>     initializeDynamicalSystem(m, t0, ds);
>   }
> should (or must) be in in the initializeDynamicalSystem. This other way is to create a generic initializeDynamicalSystem in OneStepIntegrator and call it in the inherited method initializeDynamicalSystem
> 
> What do you think ?
> 
> 


both solutions are correct.
The point of this is that we can handle (init, print, integrate … whatever you want) modeling tools object like DS and Interactions
as soon as they have been created, and independently from any simulation object.
 So specific internal buffers like properties(*dsi).workVectors that are osi-dependant should be initialized and filled by the osi. 

What is the problem with the factorisation of the lines above? Since all OSI are supposed to do this job, I think it’s more secure and cleaner that
rewriting these lines in each osi.
Anyway if needed, I prefer the second solution, that is to write  a generic « initialize work buffers for ds »  in OneStepIntegrator and call it in the inherited method initializeDynamicalSystem. 
Sounds right to you?

Note that it could also be a good idea to move all memory vectors from ds  to these workVectors inside the graph? This is something to be discussed.

**Comment by radarsat1** [comment]
I agree that this is something that should be done by the OSI, no problem there.  Does OneStepIntegrator have enough information to do it correctly in all cases?  (Just needs getMemSize(), right?)  If so, we should move it there, definitely.

Further, any reason not to move the calls to initMemory() and resetToInitialState() into initializeDynamicalSystem()?  And the workVector initialization?

If it was possible to avoid the calls to topology()->setOSI() and topology()->initDS() that would be even better, perhaps we could have insertDynamicalSystem() initialize the DS if it's not yet initialized, and take an optional OSI parameter that would call setOSI() if provided.  What do you think?

**Comment by radarsat1** [comment]
Note that I opted for a different name prepareIntegratorForDS().  Easier to read, but also I feel like "initialize" indicates some kind of in-place operation, without implying the "insert", so I hope that "prepare" is clearer without having to write insertAndInitialize or something..
