### ISSUE TITLE
Prismatic joint misbehaves under an orthogonal impulse

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#120]
I think I understand more specifically what is wrong with the prismatic joint now.  If you apply an initial velocity or force along the prismatic axis, everything is fine.  Same if it's along one of the axes, but on the other orthogonal axis, the objects spin around each other incorrectly -- their orientation appears to be equal but in the wrong sense -- maybe it is just a sign error?

Video demonstration:
![prismatic-test-2](https://cloud.githubusercontent.com/assets/66805/24481236/6be69254-14bf-11e7-8b61-aa51bef21b2f.gif)

Here we see a top view of two cubes that are attached by a prismatic joint in Z (axis=[0,0,1]). An impulse is applied by initial velocity in X, Y, and Z directions respectively. The impulse along the X axis (left) and along the Z axis (right) are fine, but the behaviour of the cubes when an impulse is applied in the Y axis seems wrong-- they seem to be turning equally, but the wrong way.

I'm looking into it, but any help would be appreciated.

Here is the code:

```python
#!/usr/bin/env python
from siconos.mechanics.collision.tools import Contactor
from siconos.io.mechanics_io import Hdf5
import siconos.numerics as Numerics
import siconos.kernel as Kernel

with Hdf5() as io:
    io.addPrimitiveShape('Cube', 'Box', (1, 1, 1))
    io.addPrimitiveShape('Ground', 'Box', (10, 10, .5))
    io.addNewtonImpactFrictionNSL('contact', e=0.0, mu=0.2)
    io.addObject('ground', [Contactor('Ground')], translation=[0, 0, -0.25])

    io.addObject('cube1', [Contactor('Cube')], translation=[-1, 0, 0.5], mass=0.1)
    io.addObject('cube2', [Contactor('Cube')], translation=[ 1, 0, 0.5], mass=0.1,
                 velocity=[0,5,0,0,0,0])
    # Try velocity=[5,0,0,0,0,0]) = correct behaviour
    # Try velocity=[0,0,5,0,0,0]) = correct behaviour
    # Try velocity=[0,5,0,0,0,0]) = incorrect behaviour

    io.addJoint('joint1', 'cube1', 'cube2', [0,0,1], [], 'PrismaticJointR')

with Hdf5(mode='r+') as io:
    io.run(t0=0,
           T=3,
           h=0.001,
           theta=0.50001,
           Newton_max_iter=20,
           solver=Numerics.SICONOS_FRICTION_3D_NSGS,
           itermax=10000,
           tolerance=1e-14)
```

**Comment by radarsat1** [comment]
It turns out that simply negating the quaternion differential in the first two components of the prismatic constraint "fixes" the issue, but I'm sure this won't work on the position level, so further work is needed.  I'm still working to understand exactly how H is derived here.  I understand it for knee joint, but the quaternion calculations are a little daunting for prismatic.  In any case, here is some fun sympy code that seems to generate derivatives that correspond well with the expressions in PrismaticJointR.cpp:

```python
#!/usr/bin/env python3

import sympy
from sympy import Symbol
from sympy.utilities.codegen import codegen

q11 = Symbol('q11')
q10 = Symbol('q10')
q13 = Symbol('q13')
q12 = Symbol('q12')
q21 = Symbol('q21')
q20 = Symbol('q20')
q23 = Symbol('q23')
q22 = Symbol('q22')
X2 = Symbol('X2')
X1 = Symbol('X1')
Y2 = Symbol('Y2')
Y1 = Symbol('Y1')
Z2 = Symbol('Z2')
Z1 = Symbol('Z1')
_V1x = Symbol('_V1x')
_V1y = Symbol('_V1y')
_V1z = Symbol('_V1z')
_G10G20d1x = Symbol('_G10G20d1x')
_G10G20d1y = Symbol('_G10G20d1y')
_G10G20d1z = Symbol('_G10G20d1z')

H1 =   (((q11**2 + q10**2 - q13**2 - q12**2) * (X2 - X1)
         + (2*q11*q12 + 2*q10*q13) * (Y2 - Y1)
         + (2*q11*q13 - 2*q10*q12) * (Z2 - Z1)) * _V1x
        + ((2*q11*q12 - 2*q10*q13) * (X2 - X1)
           + (q12**2 - q13**2 + q10**2 - q11**2) * (Y2 - Y1)
           + (2*q12*q13 + 2*q10*q11) * (Z2-Z1)) * _V1y
        + ((2*q11*q13 + 2*q10*q12) * (X2-X1)
           + (2*q12*q13 - 2*q10*q11) * (Y2-Y1)
           + (q13**2 - q12**2 - q11**2 + q10**2) * (Z2-Z1)) * _V1z
        - _G10G20d1x * _V1x - _G10G20d1y * _V1y - _G10G20d1z * _V1z)

print("H1 =", H1)
print()

[(f_name, f_code), header] = codegen(
    ("dH1X1", H1.diff(X1)), "C", header=False, empty=False,
    argument_sequence=(X1,Y1,Z1,q10,q11,q12,q13,X2,Y2,Z2,q20,q21,q22,q23),
    global_vars=(_V1x,_V1y,_V1z,_G10G20d1x,_G10G20d1y,_G10G20d1z))

print('Derivative of H1 with respect to X1')
print(f_code)

# Gives:
# H1_result = (_V1x*(-pow(q10, 2) - pow(q11, 2) + pow(q12, 2) + pow(q13, 2))
#              + _V1y*(2*q10*q13 - 2*q11*q12)
#              + _V1z*(-2*q10*q12 - 2*q11*q13))

# In PrismaticJointR.cpp:
# jachq1(0,0) = (_V1x * (-q11^2 - q10^2 + q13^2 + q12^2)
#                + _V1y * (-2*q11*q12 + 2*q10*q13)
#                + _V1z * (-2*q11*q13 - 2*q10*q12))
# Same answer!

[(f_name, f_code), header] = codegen(
    ("dH1q10", H1.diff(q10)), "C", header=False, empty=False,
    argument_sequence=(X1,Y1,Z1,q10,q11,q12,q13,X2,Y2,Z2,q20,q21,q22,q23),
    global_vars=(_V1x,_V1y,_V1z,_G10G20d1x,_G10G20d1y,_G10G20d1z))

print('Derivative of H1 with respect to q10')
print(f_code)
```

generates (formatted for legibility):

~~~
Derivative of H1 with respect to X1
#include "dH1X1.h"
#include <math.h>
double dH1X1(double X1, double Y1, double Z1, double q10, double q11,
  double q12, double q13, double X2, double Y2, double Z2, double q20,
  double q21, double q22, double q23)
{
   double dH1X1_result;
   dH1X1_result = _V1x*(-pow(q10, 2) - pow(q11, 2) + pow(q12, 2) +
      pow(q13, 2)) + _V1y*(2*q10*q13 - 2*q11*q12) + _V1z*(-2*q10*q12 -
      2*q11*q13);
   return dH1X1_result;
}

Derivative of H1 with respect to q10
#include "dH1q10.h"
#include <math.h>

double dH1q10(double X1, double Y1, double Z1, double q10, double q11,
   double q12, double q13, double X2, double Y2, double Z2, double q20,
   double q21, double q22, double q23)
{
   double dH1q10_result;

   dH1q10_result = _V1x*(2*q10*(-X1 + X2) - 2*q12*(-Z1 + Z2) +
      2*q13*(-Y1 + Y2)) + _V1y*(2*q10*(-Y1 + Y2) + 2*q11*(-Z1 + Z2) -
      2*q13*(-X1 + X2)) + _V1z*(2*q10*(-Z1 + Z2) - 2*q11*(-Y1 + Y2) +
      2*q12*(-X1 + X2));

   return dH1q10_result;
}
~~~

After a bit of reverse engineering on the function Jd1d2 these seem to correspond well.  But I think I'll avoid doing that for every element of the Jacobian ;)  I assume the auto-generated code is fine, the problem is more likely in H1/H2 somewhere.

**Comment by radarsat1** [comment]
Here is the same video as above but after the work-around committed in eb428ce2c.

![prismatic-test-2](https://cloud.githubusercontent.com/assets/66805/24524074/bcd481ce-156b-11e7-92d0-080f162fada8.gif)

**Comment by radarsat1** [comment]
I've confirmed now that this temporary fix also fixes #113, and I have also confirmed after playing with the pending solution to #114 that the temporary fix indeed does not work at the position level.

**Comment by vacary** [comment]
cool :_)

What do you mean by " the temporary fix indeed does not work at the position level."

**Comment by radarsat1** [comment]
I mean that I committed a fix in eb428ce2c91 that inverts the derivative of the rotation, but H1/H2 are still incorrect.  So it works at the velocity level but not at the position level.  I am working on it, I found the hand-written notes in siconos-junk, but I am still not sure where the error is.

**Comment by vacary** [comment]
The maple files are also somewhere. I will find it

**Comment by radarsat1** [comment]
There is one maple file there but I cannot open it ;)

**Comment by vacary** [comment]
there  : siconos-junk/SandBox/Joints

**Comment by radarsat1** [comment]
Some progress. I have reconstructed the Maple code based on the handwritten notes using sympy and achieved the same results.  Here is some basic code that generates H1:

**Comment by radarsat1** [comment]
Some progress, I have reconstructed the Maple code using sympy and generated equivalent functions that seem to give the same results. Further, I found that if I change the direction of the q1 frame adjustment I can get the same negation of the quaternion part of H1/H2.  Here is some basic code:

    G1G2d1 = qmul( qinv(q1), qmul(G2 - G1, q1) )
    Ha = lambda V: np.dot(G1G2d1, V)
    Hb = lambda V: np.dot(G10G20d1, V)
    H1 = sympy.simplify(Ha(V1) - Hb(V1))
    H2 = sympy.simplify(Ha(V2) - Hb(V2))

I got better results if I changed G1G2d1 to,

        G1G2d1 = qmul( q1, qmul(G2 - G1, qinv(q1)) )

Unfortunately, it still didn't work in position.  Now I am realizing there is further something wrong, because I found that even with this solution, it does not work if the two bodies have different initial orientations.

**Comment by radarsat1** [comment]
I am wondering if there is a problem with the formulation.  In fact, the code given in my previous comment reproduces what is already in PrismaticJointR.cpp.  However, the handwritten notes give the formula,

    G1G2d1 = qmul( qinv(q1_0), qmul(G2 - G1, q1_0) )

where q1_0 is the q1(t) of t=0, not

    G1G2d1 = qmul( qinv(q1), qmul(G2 - G1, q1) )

That is, the bodies need to be compared to V1/V2 with respect to the *original frame*, since V1/V2 are specified in the initial frame and not adjusted to changes in q1.  I think somehow that both q1 and q1_0 need to be taken into account.  I've been trying to do it but without success so far.

**Comment by vacary** [comment]
Super.
Really happy that the code has been translated into Sympy. I think that it would be really good to commit the simply files directly into the repository.

Regarding your question about the fact that it is not working working in position, I am asking whether it is not more deeper problem. We are computing gradients w.r.t to the quaternion variable. I am pretty sure that this gradient are not consistent with the fact that with are dealing with unit quaternions that must lie into a Lie group. The computation of differential in Lie group are not given by the Jacobian into linear vector spaces. This is not crucial at the velocity level but at the position level it may be.

I will try to propose you another type of tangent operators.

**Comment by radarsat1** [comment]
Yes, I see your point about the gradients in rotation space.  I am not (yet) familiar enough with quaternions to answer intelligently ;)

However, I will note that the DirectProjection method appears to work fine with PivotJointR.

I'll keep working on this today, since it's interesting and if I can figure it out it should help immensely with implementing other joint types as well.  I'll look into committing the sympy code, for now it is a bit messy and doesn't generate code that looks quite as efficient.  We talked about using autodiff (like CppAd) which I am still interested in, but I needed an intermediate solution for now!

**Comment by xhub** [comment]
Btw someone mentioned Casadi a while ago. One of the main dev of casadi is working at the UW-Madison. So I can ask him for help if we use his software.

**Comment by radarsat1** [comment]
Just a warning, I have rebased the directproj branch on the lastest master.

**Comment by radarsat1** [comment]
Casadi is another autodiff framework like CppAd, right?  Could be interesting.  As long as it's an easily installable dependency I don't much care which one is used ;)  (I was looking at CppAd principally because it's in Ubuntu via apt-get)  Maybe he could summarize the benefits of Casadi vs alternatives for us?

**Comment by vacary** [comment]
ok, if it works fine with a pivot joint, the problem comes from a wrong formulation of the joint. You are specking and the hand-written note, those in siconos-junk ?

**Comment by radarsat1** [comment]
I just pushed commit 4e363b84 to directproj that includes prismatic.py.  It uses sympy's codegen to write a file "prismatic.generated_c" containing C code that calculates H1, H2, and jachq.  It adds some CMake dependencies to run this script when it changes, which must be enabled by turning on WITH_SYMPY.

If WITH_SYMPY is enabled, then PrismaticJointR.cpp will use the generated code.  (Note, it's for Python3, so you must "pip3 install sympy".)  No detection of sympy is performed.  It generates code that is only #included in PrismaticJointR.cpp as static functions, and the extension .generated_c is used to stop the automatic source file detection trying to compile it on its own.

Currently it generates code according to the current behaviour of the prismatic joint, as far as I can tell, so you should see no difference using WITH_SYMPY.  However, you can modify the formulas in it and get new calculations for H1/H2 and jachq.  I'm passing pretty much all available information to the functions as parameters, which isn't very efficient, but is for completeness so that one can modify the generating code without needing to change the function signatures.  (Hopefully the C compiler can optimise it all out since the functions are static.)

That said, at the moment it only replaces H1/H2 and leaves H3/4/5 as they are.  (The orientation constraints.)  Same for rows 2,3,4 of jachq -- the old calculations are still performed, and only rows 0 and 1 are replaced.

**Comment by radarsat1** [comment]
> ok, if it works fine with a pivot joint, the problem comes from a wrong formulation of the joint.

That's my hypothesis, yes.

> You are specking and the hand-written note, those in siconos-junk ?

Yes.  In particular, this:
![screenshot from 2017-04-06 17-00-53](https://cloud.githubusercontent.com/assets/66805/24773226/aa8bc598-1aea-11e7-8293-45a77175e940.png)

Notice the use of q1_0 in the RHS of the last line.  The current code does not use q1_0, but rather q1.  However, if I change it for q1_0, there is no rotation at all in the result.  I'll keep working on it!

> did you finally try with the Maple code in siconos-junk/Sandbox/Joints ?

I'm afraid I don't have Maple.  I haven't asked around to see if I can find it yet, but it's been a good exercise to reconstruct the equations myself.  I am able to see the formula for H1 and H2 by looking at the .mw file in a text editor, however it includes all individual quaternion element manipulations and so is not easy to read.  I can't tell if there is a "higher level" formula in that file like the one I showed in previous comments.  Can you open the Maple file and tell me if it corresponds to,

> qmul( qinv(q1), qmul(G2 - G1, q1) )

as I suspect?  Maybe you could take a screenshot for me..
