### ISSUE TITLE
siconos_vview not working: about fclib, csparse

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#126]
Hi, I am a new user of siconos, and I successfully compiled it with the cmake flag:

> -DWITH_BULLET=ON

**Comment by radarsat1** [comment]
Hi, please give more information regarding the error you are seeing?  If you see,

> No module named siconos.fclib.

this is normal and can be ignored.  I am not sure what you mean by "csparse", do you see an error regarding csparse?

**Comment by batzkass** [comment]
Hi, and thanks for you fast answer. I put the submit button by mistake before finishing the message, I am currently writing an update.

**Comment by batzkass** [comment]
Ok, I got the

> No module named siconos.fclib

error, I thought the problem was from this import so I tried to compile fclib by myself but I got an other error with csparse.

Anyway, as you said I can ignore this message, this is what I have done in siconos/examples/Mechanics/MechanicsIO:
`siconos cube.py` -> everything was ok
then
`siconos_vview cube.hdf5`
and I get:

> No module named siconos.fclib.
ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Graphics/vtkDataObjectToDataSetFilter.cxx, line 290
vtkDataObjectToDataSetFilter (0x2dd8a40): Couldn't create any points
ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Graphics/vtkDataObjectToDataSetFilter.cxx, line 290
vtkDataObjectToDataSetFilter (0x2dd76a0): Couldn't create any points
Traceback (most recent call last):
  File "/usr/local/bin/siconos_vview", line 945, in <module>
    transformer.SetInputData(datasets[contactor_name])
AttributeError: SetInputData

Any idea ?
Many thanks

**Comment by radarsat1** [comment]
Hi, that's odd, it seems the VTK function does not exist, so it must be a version problem with that library.  I am using it with Python 2.7.12 after installing the "python-vtk6" package in Ubuntu, which appears to be VTK version 6.2.0.  Which version of VTK are you running?

**Comment by radarsat1** [comment]
Oh I see now, sorry, vtk-5.10.1.  Try using VTK 6.

**Comment by batzkass** [comment]
Thanks, with the python-vtk6 package it works now. On Ubuntu 16.04, it seems that the default python-vtk package installs the 5.10 version.

**Comment by radarsat1** [comment]
Excellent.  Hopefully VTK gets Python 3 support sometime :P
