### ISSUE TITLE
cxx11 issues with boost >=1.64, cppunit >=1.14

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#128]
Some notes/remarks following Mac OS update which leads to cppunit 1.14, boost 1.64 and cmake 3.8

- cmake 3.8 change swig functions swig_add_module to (more complete) swig_add_library
- cppunit 1.14 seems to be only c++11
- boost 1.64 add a 'BOOST_SPN_OEXCEPT' which breaks swig wrapping of kernel.i

Solution: 
use -DCMAKE_CXX_STANDARD=11 
add boost header boost//smart_ptr/detail/sp_noexcept.hpp in sharedPointers.i 

Work on my OS (mac) but untested for other OS and/or lower versions of boost.

opt : add -DSICONOS_USE_BOOST_FOR_CXX11=OFF to use cxx11 smart pointers rather than boost ones.

**Comment by vacary** [comment]
Hi,
It seems that 

> boost/smart_ptr/detail/sp_noexcept.hpp

only exist for boost version >= 1.64

I added the condition in d9b057d10842abd5c045ed8b3778d7e8387594b7

**Comment by fperignon** [comment]
Execution (siconos script) failed for most of the examples:
"binding failed: Symbol not found", because of boost shared pointer in function args.
