### ISSUE TITLE
Configuring examples and examples on Cdash are not running anymore.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#129]
It seems that all the examples are not running on Cdash.

Configuring is not working :
> cmake ~/siconos/examples

fails

**Comment by vacary** [comment]
a first attempt to fix cmake configuration 3c8b3adab1d0dc2163f44d6a6442decf0893963b

**Comment by fperignon** [comment]
A second attemp to fix cmake/examples conf ... 791bb929481f5978330df1c9c1796bda58b2c46b
