### ISSUE TITLE
Failing tests: FirstOrderLinearDSTest::testBuildFirstOrderLinearDS1 and LagrangianLinearTIDSTest::testBuildLagrangianLinearTIDS1

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#131]
It seems quite important that these tests are failing, so I thought I should point it out in a dedicated issue, since I cannot solve it.

The failing assertion in the first case (FirstOrderLinearDS1) is [line 113](https://github.com/siconos/siconos/blob/master/kernel/src/modelingTools/test/FirstOrderLinearDSTest.cpp#L113)

    *(ds->rhs()) == tmp

The failing assertion in the second case (LagrangianLinearTIDS1) is [line 110](https://github.com/siconos/siconos/blob/master/kernel/src/modelingTools/test/LagrangianLinearTIDSTest.cpp#L110)

    *(ds->jacobianRhsx()->block(1,0)) == *rhsK

Actually some investigation in the first case shows that the rhs() and tmp are equal with the exception of the last element which differs only by an order of 1e-15.  The second case does not fail for me.  So maybe we need to replace these tests with epsilon-equality tests?  It would be a good addition to SiconosVector to have such a comparison function.  But what is an acceptable delta here?

**Comment by radarsat1** [comment]
I added a few prints to investigate,

~~~
  printf("tmp: "); tmp.display();
  printf("rhs: "); ds->rhs()->display();
  printf("==0:  %g\n", (*ds->rhs())(0) - tmp(0));
  printf("==1:  %g\n", (*ds->rhs())(1) - tmp(1));
  printf("==2:  %g\n", (*ds->rhs())(2) - tmp(2));
  printf("==:  %d\n", *ds->rhs() == tmp);
~~~

and this is the output:

~~~
--> Test: constructor 1.
tmp: [3](1.600000e+01,1.650000e+01,1.666667e+01)
rhs: [3](1.600000e+01,1.650000e+01,1.666667e+01)
==0:  0
==1:  0
==2:  3.55271e-15
==:  0
~~~

**Comment by fperignon** [comment]
this test passed on my system, 
with this output:

700: --> Test: constructor 1.
700: tmp: [3](1.600000e+01,1.650000e+01,1.666667e+01)
700: rhs: [3](1.600000e+01,1.650000e+01,1.666667e+01)
700: ==0:  0
700: ==1:  0
700: ==2:  0
700: ==:  1

same for LagrangianLinearTIDS

On cdash, the result is 


maybe we should investigate on differences coming from  lapack implementation  (openblas vs atlas)?

By the way, operator == for SiconosVector is already based on epsilon-equality tests, the result of a == b  is true if
 (a - b).normInf() < std::numeric_limits<double>::epsilon()
this epsilon is 2.22045e-16 on my system.

**Comment by radarsat1** [comment]
Ah ok, sorry, that's good to know regarding the epsilon comparison.  It seems the difference for me exceeds that epsilon you are reporting. Looking at cdash, it appears that the test fails on all combinations of operating systems (ubuntu, debian, fedora) and lapack implementations (atlas, openblas).. [here](http://cdash-bipop.inrialpes.fr/testSummary.php?project=1&name=FirstOrderLinearDSTest%3A%3AtestBuildFirstOrderLinearDS1&date=2017-05-09)

There must be a difference in order of operations somewhere.  Maybe not a big deal but I guess this is what the test is meant to detect.
