### ISSUE TITLE
Failing test: test_ds_interface, because rhs() is null for NewtonEulerDS

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#132]
After the recent refactor I am not sure whether this is correct or not, so I pose the question:  the test `test_ds_interface` in `test_dynamical_systems.py` fails because in the case of NewtonEulerDS, the assertion `assert ds.rhs() is not None` fails.  However, I see that in NewtonEulerDS::computeRhs(), the computation is only performed if _wrench is non-null, otherwise nothing happens.  Is it correct, or is the assertion now incorrect in assuming that rhs() should always be defined?

**Comment by fperignon** [comment]
> Le 9 mai 2017 à 19:09, Stephen Sinclair <notifications@github.com> a écrit :
> 
> After the recent refactor I am not sure whether this is correct or not, so I pose the question: the test test_ds_interface in test_dynamical_systems.pyfails because in the case of NewtonEulerDS, the assertion assert ds.rhs() is not None fails. However, I see that in NewtonEulerDS::computeRhs(), the computation is only performed if _wrench is non-null, otherwise nothing happens. Is it correct, or is the assertion now incorrect in assuming that rhs() should always be defined?
> 
> 


I leave this failing test for NewtonEuler as a reminder, to handle (later …) this rhs problem in NewtonEuler.

In DynamicalSystems, I think (but we may discuss that)  that rhs() should always be defined as soon as initRhs() has been called to fill xdot vector properly (see for example LagrangianDS.cpp). This is mandatory for lsodar for instance.

If so, the implementation of this initRhs in NewtonEuler should be properly done, especially to set _x[1].
This will fix the test_dynamical_systems.py error.

**Comment by vacary** [comment]
fixed with 228eca05133a8dd1c2604c2baa276ab50581cbba.

I developed an experimental version of the complete interface for NewtonEulerDS. This has been test on very simple  example. Perhaps, a fox is still there.
