### ISSUE TITLE
Failing test: test_smc.py, _DSPhi is null in LinearSMCOT2::initialize

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#133]
Commit 7120c857fd3d4431e2dc963633664400389a7722 changed the following in LinearSMCOT2::initialize,

~~~
   if (dsType == Type::FirstOrderLinearDS)
   {
-    _DSPhi.reset(new FirstOrderLinearDS(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
-    _DSPred.reset(new FirstOrderLinearDS(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
+    FirstOrderLinearDS& fods = static_cast<FirstOrderLinearDS&>(*DS);
+    SP::SiconosVector x0(new SiconosVector(*fods.x0()));
+    SP::SiconosMatrix A = fods.A();
+    SP::SiconosVector b = fods.b();
+    if(fods.A() && fods.b())
+      {
+       SP::SiconosMatrix A(new SimpleMatrix(*fods.A()));
+       SP::SiconosVector b(new SiconosVector(*fods.b()));
+       _DSPhi.reset(new FirstOrderLinearDS(x0, A, b));//(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
+       _DSPred.reset(new FirstOrderLinearDS(x0, A, b));//(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
+      }
   }
~~~

However the `if(fods..)` part seems to be missing an `else`, which leaves _DSPhi unset.  In the case of `test_smc.py`, _DSPhi is left null, which causes a segfault.  Assuming the copy constructor is changed to be explicitly avoided here for a good reason, I don't know what is the correct fix.

Additionally, the copy constructor is still used in the Type::FirstOrderLinearTIDS case, maybe it should be changed as well, but I don't understand the reason so I'll assign to @fperignon.

By the way if I do change it back to,
~~~
    _DSPhi.reset(new FirstOrderLinearDS(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
    _DSPred.reset(new FirstOrderLinearDS(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
~~~
with no `if`, then the test passes successfully.

**Comment by fperignon** [comment]
> Le 9 mai 2017 à 20:13, Stephen Sinclair <notifications@github.com> a écrit :
> 
> Commit 7120c85 <https://github.com/siconos/siconos/commit/7120c857fd3d4431e2dc963633664400389a7722> changed the following in LinearSMCOT2::initialize,
> 
>    if (dsType == Type::FirstOrderLinearDS)
>    {
> -    _DSPhi.reset(new FirstOrderLinearDS(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
> -    _DSPred.reset(new FirstOrderLinearDS(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
> +    FirstOrderLinearDS& fods = static_cast<FirstOrderLinearDS&>(*DS);
> +    SP::SiconosVector x0(new SiconosVector(*fods.x0()));
> +    SP::SiconosMatrix A = fods.A();
> +    SP::SiconosVector b = fods.b();
> +    if(fods.A() && fods.b())
> +      {
> +       SP::SiconosMatrix A(new SimpleMatrix(*fods.A()));
> +       SP::SiconosVector b(new SiconosVector(*fods.b()));
> +       _DSPhi.reset(new FirstOrderLinearDS(x0, A, b));//(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
> +       _DSPred.reset(new FirstOrderLinearDS(x0, A, b));//(*(std11::static_pointer_cast<FirstOrderLinearDS>(DS))));
> +      }
>    }
> However the if(fods..) part seems to be missing an else, which leaves _DSPhi unset. In the case of test_smc.py, _DSPhi is left null, which causes a segfault. Assuming the copy constructor is changed to be explicitly avoided here for a good reason, I don't know what is the correct fix.
> 
> Additionally, the copy constructor is still used in the Type::FirstOrderLinearTIDS case, maybe it should be changed as well, but I don't understand the reason so I'll assign to @fperignon <https://github.com/fperignon>.
> 

(Maybe)  fixed  in 690356e <https://github.com/siconos/siconos/commit/690356e6e7679998eb6f7f27e4b2dbb7bf513381>. The copy constructor was not used because I’m not sure it is reliable when A and/or b are plugins rather than known matrice/vector. And I don’t know if this case should be taken into account in LinearSMCOT2. Since it concerns control component, maybe @xhub can check this? 
By the way, does anyone know (@xhub?) if  there is a reason to save attribute ‘b’ in FirstOrderNonLinearDS while it’s clearly an operator of derived linear classes?
