### ISSUE TITLE
Useless files/classes : DynamicalSystemsSet and MLCP2

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#136]
MLCP2 is outdated and seems to be useless.
DynamicalSystemsSet has been replaced with Graph and should be removed.

I will remove these in future commits. 
If someone feels these classes are still required, please complain!

**Comment by vacary** [comment]
Mechanisms does not compile anymore

**Comment by xhub** [comment]
I was interested in reviving the global part of Siconos. I think MLCP2 was part of it but it's fine to nuke it for now.

**Comment by fperignon** [comment]
For the record, I saved every removed file (MLCP2 and friends)  in siconos-junk, just in case
