### ISSUE TITLE
3 D.o.F. particles with shapes.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#151]
The goal of this issue is to think to an implementation of a 3dof particles with shapes inherited from NewtonEulerDS without Euler (without rotations).

**Comment by radarsat1** [comment]
To be clear, the idea here is "support for NewtonEulerDS with 3-DoF position and no orientation."

**Comment by vacary** [comment]
This enhancement could be easily carried out if needed now, since we have SecondOrderDS and the bullet Engine is correctly connected with that
