### ISSUE TITLE
Pop-corn effect.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#152]

**Comment by radarsat1** [comment]
I created a program to generate pyramidal stacks of boxes for testing this: https://github.com/siconos/siconos/blob/master/examples/Mechanics/GeometricPrimitives/box_stacks.py

I don't know how to cause it, but it would be nice to find a repeatable, more controlled configuration that does, so here you can change `N` to make big stacks of boxes, and also change the sizes of the boxes in order to try different geometries (and therefore inertias)

**Comment by vacary** [comment]
I tried the file you submitted but it does not create the "pop-corn" effect even with a large amount of boxes. I have the impression that the issue is raised when large rotations are involved that generates unsymmetric delassus matrices.

**Comment by radarsat1** [comment]
Maybe we can try giving the boxes in the script non-zero initial velocities?

**Comment by vacary** [comment]
I will try to reproduce the bug with a "small chute" example.

**Comment by vacary** [comment]
After a long work, I created some small examples that reproduce the pop-corn effect. They may be found at
https://github.com/vacary/siconos/tree/test_inertia/examples/Mechanics/GranularMaterial

The first curious fact is that the effect appears randomly and I am to able to reproduce two times the same simulation. I am wondering if it comes from:
- a wrong memory management
- a random process in bullet for choosing contact points
- a numerical instability in the NSN solver that is related the "if...then..else" statements.

For the moment, I do not understand.

**Comment by vacary** [comment]
My first work was to investigate how the inertia matrix influences the results. Firstly, I checked that our inertia computation for convex hull is right by comparing with occ. It is ok. Then I tested several cases:
- full inertia matrix
- diagonalized inertia matrix 
- uniform inertia matrix (\alpha I) equivalent to a sphere or a cube

The pop-corn problem continues to appear in all cases, but the number of occurence decreases with diagonalized inertia matrix and uniform inertia matrix. I can conclude that the problem is not directly related to inertia matrix. 

I also rotate the body such that the matrix of inertia is diagonal. I get the same result as for the full inertia matrix which is reassuring.

I am new pretty sure that the problem do not come from the inertia matrix even if to renders the problem more difficult.

**Comment by vacary** [comment]
Secondly, I tested the effect of the shape the body. For that I created body with the inertia matrix of the convex hull but I change the shape to a cube. The pop corn problem appears also. The small test in
https://github.com/vacary/siconos/tree/test_inertia/examples/Mechanics/GranularMaterial
are based on these configurations.

**Comment by vacary** [comment]
Finally, I am pretty convinced that the problem comes the instabilities in the NSN solver. With the PLI solver, the pop-corn effect does not appear. I tries to focus my work on the NSN hybrid solver that should fix this problem. As I mentioned in #214, the hybrid solver was not able to improve the solution since the error measure was different for PLI and NSN solvers. I fixed that in e140907

I hope it will improve the situation

**Comment by vacary** [comment]
Thanks @radarsat1. I think the random character came from the unitialized rho parameter in PLI when it is used on hybrid solver.

**Comment by vacary** [comment]
I ran some simulations over 10 s of the chute_con_rocas example with a coefficient of friction of 2.0:

- NSGS with NSN_GP is prone to pop-corn effect
- NSGS with NSN_GP_HYBRID or PLI solver do not demonstrate pop-corn effect.

I close this issue.

I relaunched simulations over 20 s to be sure. I will re-open the issue it if appears a problem.

**Comment by radarsat1** [comment]
Yes, and now that I think about it, if moving contact points were the culprit, then the effect would not have shown up in the case where `clearOverlappingPairCache=true`, which was the previous behaviour of the Bullet backend in which the problem was first detected.  Great to have some empirical results, let's keep an eye on it.
