### ISSUE TITLE
File format discussion

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#153]
I create this issue to discuss changes to the file format.  As discussed in the last meeting, the discussion should be split into 2 parts.

1. Small changes needed for the immediate future.  Renaming tables, adding metadata, etc.

2. Larger work towards a "simulation" file format that takes into account many possibilities of Siconos and similar software.

## Small changes

Current situation.  We use HDF5, which appears to work well, I think we should continue using it.  It is efficient and has nice utilities (h5dump in particular) to support it.  Only drawback is that it's not specifically made for dynamically extended tables, the efficiency of extending multiple tables during runtime should be investigated.  There are some interesting points regarding different versions of HDF5, we should look into them more closely.  (e.g, support for [parallelism](https://ftp.hdfgroup.org/HDF5/PHDF5/), etc.)

https://ftp.hdfgroup.org/h4vsh5.html

https://ftp.hdfgroup.org/HDF5/doc/ADGuide/Changes.html

Regarding creating HDF5 files, I just read that it is possible to convert to/from [a standard XML representation](https://support.hdfgroup.org/HDF5/XML/), we should look at whether it could be useful in some situations, e.g output from C/C++ programs.

Current tables are:
~~~
GROUP "/" {
   GROUP "data" {
      GROUP "boundary_conditions" {
      DATASET "cf" {
      DATASET "dynamic" {
      GROUP "input" {
         GROUP "bar" {
            DATASET "Bar-0" {
         GROUP "cube2" {
            DATASET "Cube-0" {
         GROUP "ground" {
            DATASET "Ground-0" {
         GROUP "post" {
            DATASET "Knob-1" {
            DATASET "Post-0" {
      GROUP "joints" {
         DATASET "joint1" {
         DATASET "joint2" {
      GROUP "nslaws" {
         DATASET "contact" {
         DATASET "frichigh" {
         DATASET "friclow" {
         DATASET "stop" {
      GROUP "permanent_interactions" {
      GROUP "ref" {
         DATASET "Bar" {
         DATASET "Cube" {
         DATASET "Ground" {
         DATASET "Knob" {
         DATASET "Post" {
      DATASET "solv" {
      DATASET "static" {
      DATASET "velocities" {
~~~

What changes are needed in the short term?

What metadata should we add?  (I think some version and "simulation type", e.g. rigidbody3d, rigidbody2d, fem3d, etc, should be added, even not all are supported.)

## Larger file format project

If we are to propose a file format for general simulation output, we should look at the state of the art, and consider needs of other software as well.

Keeping in mind that Siconos can be used for various simulation types and not only mechanics, we need at least some metadata to indicate simulation type (including e.g. electronics & biology, flexible and rigid bodies, etc?), or to design well the constraints of the project. (e.g. only 3d rigid body simulations)

Finally, some existing formats to look at: scene descriptions, too many examples to list (X3D, Collada, etc..  probably we should embed existing scene description types instead of inventing a new one), robot simulation formats (e.g. Gazebo log files = SDF + time steps)

This would of course need to be a dedicated project if it continues, but some initial discussion might be worthwhile.  Finally though this would need to be an inclusive project that opens up to the whole simulation community, if it stands a chance of adoption.

We should also, in my opinion, evaluate whether an existing format can take care of these needs, with possibly some small extensions that could be contributed, because in this kind of thing it's easy to end up with: https://xkcd.com/927/

**Comment by radarsat1** [comment]
Let's leave the "larger file format project" part of this aside, please use this space to discuss fixing up the current HDF5 format. (i.e. renaming tables etc.)

**Comment by bremond** [comment]
I think for some minimal modifications, we should have at least in the context of a
hierarchical data model:

 1. understandable naming, without abbreviations, so something like

   cf -> contact_forces
   ref -> reference_shapes
   solv -> solver

 2. a separation between what is input (every specifications, initial
    conditions, shapes, permanent interactions, etc.) and output
    (results or characterizations of results computed by siconos)

   so:
   boundary_conditions
   input
   joints
   nslaws    
   permanent_interactions
   static
   
   would go under a group named 'input' (or specifications or ...)
   input/boundary_conditions
   input/objects (or bodies or ...)
   input/joints
   input/nslaws
   input/permanent_interactions
   input/static_objects (or ...)

   and:
   cf        
   dynamic
   solv

   would go under a group named 'output' (or simulation_results or ...)

   output/contact_forces
         /positions
         /velocities
         /solver


This 2 points are simple to implements with what we already have in
mechanics_io and this may be a preamble to deeper modifications.


I think also that we should add an attribute for the format version at
the root group for backward compatiblity and check that every accesses
(vview, vexport) are made from a common "API" in mechanics_io (this
should be the case).

**Comment by vacary** [comment]
I agree with the separations input/output.

For the naming convention, is suggest
input/boundary_conditions  --> ok
input/objects (or bodies or ...)  --> object or bodies is ok for me
input/joints --> ok
input/nslaws --> non smooth_laws or contact laws
input/permanent_interactions --> ok
input/static_objects (or ...)  --> fixed_objects

output/contact_forces --> should we split local frame 
output/positions --> configuration (position + rotations)
output/velocities 

We can also have at the same level something like simulation_info 
simulation/timestepping (type, times step, number of Newton iterations, max, iter, tolerance and other parameters. )
simulation/solver

ok for the format version and some info on the siconos version or the commit tag

**Comment by radarsat1** [comment]
Agreed with renaming so far.

Is there any reason not to put velocities and positions in the same table? It would simplify some logic. 

What about my idea for adding a "time index" table?  (One row per time step, telling which row ranges in "_dynamic" and "_cf" correspond.)  Do you agree that it would help with efficiency, or is it overcomplicated?

Currently we have initial positions listed in the object descriptors, and that's why I had to special-case this scenario in vview to view empty simulations.  What about putting this simply in the first row of `_dynamic`, or at least copying it there immediately on creation (for objects without time_of_birth)?

**Comment by bremond** [comment]
We discussed about this today, here is the white board:

![20181211_165728](https://user-images.githubusercontent.com/5980800/49814177-61436400-fd69-11e8-82a5-62ca714ee4cb.jpg)

**Comment by vacary** [comment]
transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement

**Comment by vacary** [comment]
transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
