### ISSUE TITLE
MoreauJeanGOSI is no longer working

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#154]
Example BouncingBallTS-MoreauJeanGOSI.cpp throws:
`Runtime Exception : MoreauJeanGOSI::fillDSLinks. The implementation is not correct for two different OSI for one interaction`

If have remove the test 
`  
  if (checkOSI(DSG.descriptor(ds1)) || checkOSI(DSG.descriptor(ds2)))
  {
    RuntimeException::selfThrow("MoreauJeanGOSI::fillDSLinks. The implementation is not correct for two different OSI for one interaction");
  }
`
in fillDSLinks, it works perfectly well. I deduce that something is wrong we set the OSI.

**Comment by radarsat1** [comment]
First, where is BouncingBallTS-MoreauJeanGOSI.cpp?  I cannot find a file with this name.  In any case I get the same error from BouncingBallNEGlobalTS.cpp.

It seems you added that check in May in 24b67a9c997633e686506aecad8628492b126b67.
The semantics of this test are not clear from the description:

>  "the implementation is not correct"

this checks that the OSI is assigned to both DSs, I'm not sure what is incorrect?

> "or two different OSI for one interaction"

at least for the case of BouncingBallNEGlobalTS.cpp, there is only one OSI, and moreover in fact in this case, ds1==ds2.  So I wonder if you just need to fix this test? For example, adding `&& (ds1!=ds2)`

**Comment by vacary** [comment]
ok, I forgot much my commits. Now, it is fixes with c8c8a432bba0bde8a76f1825e1d727c53a421733 

I didn't have time to change the implementation that is incorrect for two DS linked by an interaction and integrated by two different OSI. 

I must correct the test or perhaps correct directly the implementation. I need for that to build a new example with two DSs and two OSIs

**Comment by vacary** [comment]
fixed in ba7d3af160995d98cf343b3e0bcf9ae7826deb45
