### ISSUE TITLE
Can't run Python simulations when serialization is enabled due to missing linker dependency

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#158]
I was trying to run Python files in examples/Mechanics in the container I use for testing the build and was always getting the following error:

~~~
ImportError: /usr/local/lib/python3.4/dist-packages/siconos/mechanics/collision/_base.so: undefined symbol: _ZTV9LinearSMC
~~~

Indeed using ldd reports that there is no dependency on libsiconos_control.so from collision/_base.so, naturally.

It was not clear why there would be undefined symbols from control in the mechanics swig modules, until I noticed the following in MechanicsBase.i:

~~~
#ifdef WITH_SERIALIZATION
%{
#include <SiconosFull.hpp>
%}
#endif
~~~

After recompiling WITH_SERIALIZATION=OFF, I was able to run the simulations.  So I suspect that either we need to be more careful with how the serialization headers are included here, or add libsiconos_control.so as a dependency to all mechanics submodules when serialization is enabled.  I prefer the former solution.  Although I'm not entirely sure why simply including the headers is causing a load-time linker dependency error.

**Comment by xhub** [comment]
I also agree that the proper fix is to prevent that unwanted dep. Can you provide a list of the unkown symbols, so that we can try to infer where the problem is coming from?

**Comment by xhub** [comment]
I also agree that the proper fix is to prevent that unwanted dep. Can you provide a list of the unkown symbols, so that we can try to infer where the problem is coming from?

**Comment by xhub** [comment]
I also agree that the proper fix is to prevent that unwanted dep. Can you provide a list of the unkown symbols, so that we can try to infer where the problem is coming from?

**Comment by vacary** [comment]
@radarsat1 Check that it works now

**Comment by radarsat1** [comment]
I can confirm that this is fixed.  E.g., _numerics.so no longer depends on kernel or control:

```
$ ldd ~/.local/lib/python2.7/site-packages/siconos/_numerics.so | grep siconos
	libsiconos_numerics.so.5 => /home/sinclairs/.local/lib/libsiconos_numerics.so.5 (0x00007f79def37000)
	libsiconos_externals.so.5 => /home/sinclairs/.local/lib/libsiconos_externals.so.5 (0x00007f79de88f000)

$ ldd ~/.local/lib/python2.7/site-packages/siconos/_kernel.so | grep siconos
	libsiconos_numerics.so.5 => /home/sinclairs/.local/lib/libsiconos_numerics.so.5 (0x00007f2b3db79000)
	libsiconos_kernel.so.5 => /home/sinclairs/.local/lib/libsiconos_kernel.so.5 (0x00007f2b3c9ba000)
	libsiconos_externals.so.5 => /home/sinclairs/.local/lib/libsiconos_externals.so.5 (0x00007f2b3bd73000)

$ ldd ~/.local/lib/python2.7/site-packages/siconos/control/_sensor.so | grep siconos
	libsiconos_kernel.so.5 => /home/sinclairs/.local/lib/libsiconos_kernel.so.5 (0x00007f742013e000)
	libsiconos_control.so.5 => /home/sinclairs/.local/lib/libsiconos_control.so.5 (0x00007f741fe3c000)
	libsiconos_externals.so.5 => /home/sinclairs/.local/lib/libsiconos_externals.so.5 (0x00007f741dd08000)
	libsiconos_numerics.so.5 => /home/sinclairs/.local/lib/libsiconos_numerics.so.5 (0x00007f741d9db000)
```

**Comment by radarsat1** [comment]
And I can run simulations with serialization enabled now.
