### ISSUE TITLE
MoreauJeanGOSI fails to run correctly on more than one DS

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#159]
Everything is in the title. I added to experimental examples in 6524e912512b588524a4299c0c36963c4e0a90d1

**Comment by vacary** [comment]
This commit fixes partly the bug 8cda7afd1ed3ae33f38ec7ca1d737bc7df9efaba by clearing the sparse matrix before filling it again.

Unfortunately, the result is still curious since the energy increased at each impact:

![captura de pantalla 2017-07-03 a las 1 27 29 p m](https://user-images.githubusercontent.com/3368202/27791025-6cdcae76-5ff3-11e7-9db1-3b3d25ec5aba.png)

**Comment by xhub** [comment]
I tried to revive MoreauJeanGOSI last year, but it is WIP, see 75329dc188bcb8078f6fd3bcf4721b7d4f6e0c53 and little has been done on my side.

This definitively needs a lot of work, but it is worth it. I wanted more GFC problems and simulations.

In a nutshell: assume nothing works :)

**Comment by vacary** [comment]
This is fixed with commit (24a73a0b4b6b4676fcac3dfc1a816d5413e828eb)
