### ISSUE TITLE
Poll: Should default joints be absolute or relative to q1?

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#161]
I am currently normalizing the API for joints, because there are still some outstanding differences in the constructors etc that make them confusing to use.  I'd like to make things the same and as least surprising as possible.

One difference is that some joint constructors have absoluteRef = false, some have absoluteRef = true, and some don't have absoluteRef and assume false.

I am adding the absoluteRef option to all joint constructors.  Should the default be absolute or relative to q1?

My vote is for absolute (i.e. absoluteRef=true)

@bremond @vacary

**Comment by radarsat1** [comment]
Equally valid could be the opinion that absoluteRef should not have a default value!  Perhaps it would make sense to force the user to specify...

**Comment by radarsat1** [comment]
After some thought, I think that last idea is best.  It should never be "automatic" whether P and A are relative to q1 or not, the user must specify.  I've coded this along with some other changes to joint construction in #162.

**Comment by radarsat1** [comment]
I'll go ahead and merge this tomorrow if there is no argument.  I posed it as a PR just to make sure it does not surprise anyone or break code that is developed outside the Siconos repository.

But if you think such a breaking change should wait until 4.2 please let me know.

**Comment by bremond** [comment]
Is it ok with mechanisms /MBTB stuff (https://github.com/siconos/siconos/tree/master/mechanics/src/mechanisms) ? Sorry I do not have to check right now (the SliderCrank for example)
No tests are there... and we can think of of an interface occ/new mechanics API for 4.2 but not for 4.1

**Comment by radarsat1** [comment]
I checked the OCC examples, but I will double-check on mechanisms before merging anything.

**Comment by radarsat1** [comment]
Yes, a few lines in mechanisms were affected, thanks.

**Comment by radarsat1** [comment]
Closed in 77ecc5e4225d2d29242961975e5670b4550b6bd8
