### ISSUE TITLE
Force calculation utilities

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#167]
Moving commit comment https://github.com/siconos/siconos/commit/841179d1e83ceca8dfedd22c53eec40007315a19#commitcomment-22934113 to this issue for discussion.  Regarding my recent [spring-damper examples](https://github.com/siconos/siconos/blob/841179d1e83ceca8dfedd22c53eec40007315a19/examples/Mechanics/JointsTests/spring_damper_pivot.py):

> @vacary *I am wondering if the small pieces of code in the controller could be implemented into a generic C++ classes JointTorque that may associated with the joint ?*

I agree that it could be cool to formalize that code a bit better, however I struggled to find a good way within the Siconos "ethos" if you want. For example, I think it's best to keep the links between interactions and DS within the graph, but to apply forces to the linked DS then such as JointTorque would need to maintain these pointers, and take control of mExt/fExt away from the user.

That is why I elected to instead just provide some utility functions that would make the calculations trivial for the user, but still leave it up to the user to decide how to apply them.  I also added as clear a note as I could to say that spring-damper forces may be more appropriate to model as internal forces fInt/mInt, depending on the context.

Basically Siconos seems to provide two methods of applying force in the NE context:

1. Provide the fExt/mExt vectors, which are assumed to be calculated or constant.  This is what I am using here.  (It's a bit inefficient -- due to the Python numpy conversion a new fExt/mExt are provided every time I change them instead of replacing the values.)

2. Provide plugin functions that calculations fExt/mExt on demand.

Neither of these really lends itself to the common idiom in physics engines that provides a "force accumulator", a vector that you add to while calculating each source of forces.  I already added [NewtonEulerDS::addExtForceAtPos()](https://github.com/siconos/siconos/blob/5ed4e1bcbdfe1a53c205597b65794944326ac0ba/kernel/src/modelingTools/NewtonEulerDS.cpp#L1510) to facilitate off-center-of-mass force calculations, but made sure to document very well that this modifies the vectors pointed to by `_fExt` and `_mExt`, and I'm still not sure this is the "right way" for Siconos.. what do you think?  It seems to be the only function in Siconos that does something like that, so I was very hesitant, but it's too useful not to include.

Other things to consider:

* It would be cool to potentially involve non-smooth problems here.  For example, ODE implements a ["Motor" model](https://www.ode-wiki.org/wiki/index.php?title=Manual:_Joint_Types_and_Functions#Stops_and_motor_parameters) that treats force/torque/current limits as a non-smooth problem.  It calculates the required torque to reach a velocity within one timestep while keeping current draw under a limit.  This is sort of "bundled with" friction calculations if I understand correctly, so perhaps there is some relationship with the use of RelayNSL to simulate 1D joint friction, and could be combined with an offset to provide a velocity or torque controller.

* It would also be nice to consider how to combine Siconos Mechanics with Siconos Control, and provide access to these control problems more formally, providing easy access to sliding mode methods to reach a desired velocity or setpoint, for example.

* In providing force calculation utilities we should consider how such an API might transfer to a Lagrangian context. It might even be best to await some development of NE/Langrangian automatic conversion to see how that might look.  I imagine that at minimum a JointTorque class would need a pointer to two NewtonEulerDS and a NewtonEulerJointR, but maybe there is an abstraction that could include an alternative for the LagrangianDS here.  The concept of "joints" (or at least "joint axis") needs to be lifted away from the assumption that it is a Relation, since LagrangianDS might implement it as a coordinate instead.

**Comment by xhub** [comment]
Just commenting on the Control-Mechanics link. That's something that has been on an unwritten wishlist for a long time. I believe that there should be a glue layer so that the user doesn't have to fiddle too much with the type of controller. Could you mock an API that looks reasonnable to you in a separate issue?

**Comment by radarsat1** [comment]
To be honest it's not clear to me at all how to do it, but I'm not familiar enough with Control.  Off the top of my head, I guess NEJointR and NEDS would both need to be something that Sensor can interpret, and then Actuator would need to be able to add external forces through a joint.  Perhaps it could be done with subclasses of those?

**Comment by vacary** [comment]
Transferred in wiki

https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
