### ISSUE TITLE
[Numerics] merge all Newton loops

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#168]
There are currently at least 3 implementations of the Newton method in Numerics :

newton_LSA
fc3d_nonsmooth_Newton_solvers_solve
fc3d_onecontact_nonsmooth_Newton_solvers_solve (uses nonSmoothDirectNewton)

We have to merge all 3 and make all solvers only use 1 implementation. There is already an example of how to make the merit based approach work with newton_LSA in fc3d_nonsmooth_Newton_AlartCurnier2

The results on the test cases are not always the same, due to a difference in the line-search. This requires some investigation.

**Comment by vacary** [comment]
transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
