### ISSUE TITLE
[Numerics] fallback heuristic when LS fails in Newton method

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#169]
Right now, when the LS fails, a full Newton step is taken. This behavior should be controlled via an option. Also, we may want to implement other heuristics, like adding a proximal term.

**Comment by vacary** [comment]
Fully agree. We have to control with an option. It is a way to inform the user and to know whenever the solver fails due LSA

**Comment by vacary** [comment]
The fallback to a full Newton step has been remove. Let us open a new issue if we want to add specific fallback procedures.
