### ISSUE TITLE
Implement infinite bounds in Relay

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#17]
The goal is treat explicitly infinite bounds in RelayProblem.

How to encode it ? How to avoid the duplication of variable ?

**Comment by radarsat1** [comment]
Towards this, a small test program would help and we can fix bugs from there.

**Comment by vacary** [comment]
Transfered to wish list in wiki 

https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
