### ISSUE TITLE
Tests test-LCP_NEWTONMIN-lcp_* (Failed)

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#173]

**Comment by xhub** [comment]
NEWTONMIN is actually quite broken, I let the tests fail. There are NaNs popping up in DGESV.

**Comment by vacary** [comment]
Why do you close the issue if the tests are broken ?

**Comment by xhub** [comment]
I think the solver has to be overhauled. It never worked as far as I can remember, some issues were just unnoticed before.

It is fair to have an issue about the solver, it is #175 It goes beyond just those test failing.
