### ISSUE TITLE
RockingBlock_RockingBlockED_NewMarkAlpha fails

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#178]
x0: 0.0334936490538904
y0: 0.558012701892219
theta0: 1.0471975511966
PI: 3.14159265358979
Initial position of the rocking block:
[3](3.349365e-02,5.580127e-01,1.047198e+00)
Initial velocity of the rocking block:
[3](0.000000e+00,0.000000e+00,0.000000e+00)
Mass matrix of the rocking block:
1.000000e+00, 0.000000e+00, 0.000000e+00, 
0.000000e+00, 1.000000e+00, 0.000000e+00, 
0.000000e+00, 0.000000e+00, 1.041667e-01, 
External force applied on the rocking block:
[3](0.000000e+00,-9.810000e+00,0.000000e+00)
====> Simulation initialisation ...

Size of IndexSet0: 2
Size of IndexSet1: 1
Size of IndexSet2: 0
====> Start computation ... 

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
In EventDriven::advanceToEvent, some events are detected!!!
a0: [3](3.349365e-02,5.580127e-01,1.047198e+00)
a1: [3](0.000000e+00,0.000000e+00,0.000000e+00)
a2: [3](0.000000e+00,-4.905000e-06,0.000000e+00)
a3: [3](0.000000e+00,3.921237e-16,0.000000e+00)
a4: [3](0.000000e+00,-6.722087e-16,0.000000e+00)
a5: [3](0.000000e+00,2.800884e-16,0.000000e+00)
A new event occurs at time: 4.882813e-07
Runtime Exception : NewMarkAlphaOSI::computeFreeOutput, this OSNSP does not exist

**Comment by vacary** [comment]
fixed in 3842041d4f4cf9788dc113f5e6ff4ee97f61fbdf
