### ISSUE TITLE
Build errors related to "ONLY mechanics"

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#18]
I get build errors on current master (15102fcb) related to stuff in FreeCAD, despite the following disabled items in my options file:

    $ grep -e FREE -e OCC -e MEC myoptions.cmake 
    option(WITH_OCC "compilation with OpenCascade Bindings. Default = OFF" OFF)
    option(WITH_FREECAD "Use FreeCAD. Default = OFF" OFF)
    option(WITH_MECHANISMS "Generation of bindings for Saladyn Mechanisms toolbox. Default = OFF" OFF)

The errors are,

    Linking CXX executable testMultiBody
    ../../../../libsiconos_mechanics.so.3.9.0: undefined reference to `BRepBuilderAPI_MakeEdge::IsDone() const'
    ../../../../libsiconos_mechanics.so.3.9.0: undefined reference to `BRepAdaptor_HSurface::BRepAdaptor_HSurface(BRepAdaptor_Surface const&)'
    ../../../../libsiconos_mechanics.so.3.9.0: undefined reference to `Extrema_SequenceOfPOnSurf::Clear()'
    ../../../../libsiconos_mechanics.so.3.9.0: undefined reference to `GeomAdaptor_Surface::NbVPoles() const'

etc...

I've tracked it down to the following changes in e0b39b03,

    diff --git a/cmake/siconos_find_common_dep.cmake b/cmake/siconos_find_common_dep.cmake
    index 39ad1ea..e768547 100644
    --- a/cmake/siconos_find_common_dep.cmake
    +++ b/cmake/siconos_find_common_dep.cmake
    @@ -84,7 +84,7 @@ ENDIF(WITH_BULLET)
     # --- OCC ---
     IF(WITH_OCC)
       if(NOT WITH_MECHANISMS)
    -    COMPILE_WITH(OCE 0.15 REQUIRED ONLY mechanics)
    +    COMPILE_WITH(OCE 0.15 REQUIRED)
         SET(HAVE_OCC TRUE)
         LIST(REMOVE_ITEM SICONOS_LINK_LIBRARIES DRAWEXE)
       endif()
    @@ -95,7 +95,7 @@ IF(WITH_MECHANISMS)
       SET(OCE_TOOLKITS "TKernel"  "TKMath" "TKService" "TKV3d"  "TKBRep" "TKIGES" "TKSTL" "TKVRML" "TKSTEP" "TKSTEPAttr" "TKSTEP209" "TKSTEPBase" "TKShapeSchema" "TKGeomBase" "TKGeomAlgo" "TKG3d" "TKG2d" "TKXSBase" "TKPShape" "TKShHealing" "TKHLR" "TKTopAlgo" "TKMesh" "TKPrim" "TKCDF" "TKBool" "TKBO" "TKFillet" "TKOffset")
     
       message(STATUS "Searching for OCE ....")
    -  compile_with(OCE COMPONENTS ${OCE_TOOLKITS} ONLY mechanics)
    +  compile_with(OCE COMPONENTS ${OCE_TOOLKITS})
       LIST(REMOVE_ITEM SICONOS_LINK_LIBRARIES DRAWEXE)
     
       if(OCE_FOUND)

That is to say, if I apply this diff, reverting just these changes from e0b39b03, then I can build successfully.

**Comment by fperignon** [comment]
Hi,

I've had the "ONLY mechanics" part because I get also build errors during kernel compilation due to OCE. The "ONLY" in compile_with just tells that OCE must be linked with mechanics component, not with the others, which was enough to fix my build ... that will be broken with your fix.
My guess is that testMultibody must not be built when OCE is not used? We need to check this.

**Comment by vacary** [comment]
Below you will find  my conf file. With ONLY mechanics, it does not link at all with OCE. If I removed it, to works !

What you should we do ?

    # ================================================================
    # All the default values for siconos cmake parameters
    #
    # Usage:
    # cmake path-to-sources
    #  --> to keep default value
    # 
    # cmake path-to-sources -DWITH_PYTHON_WRAPPER=ON
    #  --> to enable (ON), or disable (OFF) the concerned option.
    #
    # For details about all these options check siconos install guide.
    # ================================================================
    
    # --------- User-defined options ---------
    # Use cmake -DOPTION_NAME=some-value ... to modify default value.
    option(WITH_DOCUMENTATION "Build Documentation. Default = OFF" OFF)
    option(WITH_PYTHON_WRAPPER "Build python bindings using swig. Default = ON" ON)
    option(WITH_DOXYGEN_WARNINGS "Explore doxygen warnings. Default = OFF" OFF)
    option(WITH_DOXY2SWIG "Build swig docstrings from doxygen xml output. Default = OFF." OFF)
    option(WITH_SYSTEM_INFO "Verbose mode to get some system/arch details. Default = OFF." OFF)
    option(WITH_TESTING "Enable 'make test' target" OFF)
    option(WITH_GIT "Consider sources are under GIT" OFF)
    option(WITH_SERIALIZATION "Compilation of serialization functions. Default = OFF" OFF)
    option(WITH_GENERATION "Generation of serialization functions with gccxml. Default = OFF" OFF)
    option(WITH_CXX "Enable CXX compiler for numerics. Default = ON" ON)
    option(WITH_UNSTABLE "Enable this to include all 'unstable' sources. Default=OFF" OFF)
    option(BUILD_SHARED_LIBS "Building of shared libraries. Default = ON" ON)
    option(DEV_MODE "Compilation flags setup for developpers. Default = OFF" OFF)
    option(WITH_BULLET "compilation with Bullet Bindings. Default = OFF" ON)
    option(WITH_OCC "compilation with OpenCascade Bindings. Default = OFF" OFF)
    option(WITH_MUMPS "Compilation with MUMPS solver. Default = OFF" OFF)
    option(WITH_FCLIB "link with fclib when this mode is enable. Default = OFF" ON)
    option(WITH_FREECAD "Use FreeCAD. Default = OFF" OFF)
    option(WITH_MECHANISMS "Generation of bindings for Saladyn Mechanisms toolbox. Default = OFF" ON)
    option(WITH_XML "Enable xml files i/o. Default = ON" ON)
    option(WITH_DOCKER "Build inside a docker container. Default = OFF" OFF)
    
    # Set python install mode:
    # - user --> behave as 'python setup.py install --user'
    # - standard --> install in python site-package (ie behave as python setup.py install)
    # - prefix --> install in python CMAKE_INSTALL_PREFIX (ie behave as python setup.py install --prefix=CMAKE_INSTALL_PREFIX)
    set(siconos_python_install "user" CACHE STRING "Install mode for siconos python package")
    
    
    # List of components to build and installed
    # List of siconos component to be installed
    # complete list = externals numerics kernel control mechanics io
    set(COMPONENTS externals numerics kernel control mechanics io CACHE INTERNAL "List of siconos components to build and install")

**Comment by vacary** [comment]
Fix in [09eb4dd5bf78e42e0da0578048b9b647e2a8b117] (09eb4dd5bf78e42e0da0578048b9b647e2a8b117).

thanks
