### ISSUE TITLE
One Step NS problem "blocks" computation

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#184]
Hi, I think something is wrong in the blocks (diagonal and extra-diagonal) computation.
They are properties of vertices (diagonal blocks) and edges (extra-diagonal) and
the computation is done in OneStepNSProblem::updateInteractionBlocks .
The proper way should be:
A - for linear systems allocates and computes blocks only one time, at first touch (i.e. the first time the interaction is in active index set)
B - for nonlinear systems : allocates at first touch, computes every time step

A is not achieved and blocks are computed at every time step (more or less) which is a pity.
Indeed it seems that when an interaction is not active anymore and removed from index set 1, 
its properties are lost, including the previously computed block. And when the interaction is back, 
computation is required again. For example, in the bouncing ball, HWH is computed at every time step
although it remains the same all along the process. For large systems these repeated matrices products are costly and very annoying.

We talk about this with Maurice and have some ideas in mind to fix this.
But since everything dealing with the graph may have some unexpected side effects (...), we'll try to document this and fix it in a fork. 

Here are things to thing about:

* move properties to IG0 only (blocks, upper_block, lower_block). Still loop over IG1,2 ... but act on IG0 properties may avoid side effects when copying/removing vertices and edges to/from subgraphs.
The question is, are they some cases where properties of a given vertex/edge are not the same in indexSet0, 1, ...? 

* at the time, when there are two edges (ds) between vertices (interactions), these edges share the upper/lower block property (example : line 156, OneStepNSProblem.cpp, shared pointer equality). 
We should avoid this and deal with sum of blocks during assembly (fillW). It's quite long to explain why, we may talk about this later.

* would it be a good thing to have a "isLinear" test at interaction level rather than at "nsds" level?

See WIP fix  #203

**Comment by xhub** [comment]
Is the target release 4.2?

**Comment by vacary** [comment]
yes

**Comment by vacary** [comment]
@fperignon could you add a pull request on this feature such that we can close the issue if it works ?

**Comment by vacary** [comment]
@fperignon  Should we close this issue after your merge ?

**Comment by vacary** [comment]
transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
