### ISSUE TITLE
WITH_UNSTABLE_TESTS : a new option in CMAKE for unstable tests 

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#200]
After a discussion with @bremond, it seems that it could be useful to have a cmake  option for disabling unstable tests. We mean by unstable tests the tests that fail in some configurations due to instabilities in the numerical computations. 

This is particularly the case with semi smooth Newton bases that are not very robust w.r.t to the linear solver of the round-off errors.

The goal of this cmake option is to retain only stable tests for running job on Travis and to leave these tests on Jenkins to remember the problems of robustness.

What do you think ?

**Comment by radarsat1** [comment]
I agree that this is a good idea.  I think in general it's good to have one set of tests aimed at verifying internal consistency and API functionality (i.e. do the right thing, don't segfault), and a second set of tests aimed at verifying that solvers are robust (i.e. solver gives the right answer, etc.)

**Comment by vacary** [comment]
ok, I pushed the option into master directly. I still some examples to filter and it should be ok.
