### ISSUE TITLE
fc3d_FixedPoint_set_internalsolver_tolerance: too many prints in verbose mode

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#207]
is called inside nsgs loop and if numerics is in verbose mode, it prints at each iteration of the solver
fc3d_FixedPoint_set_internalsolver_tolerance - Internal solver tolerance is set to ...

it is unusable in a simulation, 

maybe some flag numerics_debug is needed ?

**Comment by vacary** [comment]
Perhaps, you can increase the level of verbose to 2

**Comment by vacary** [comment]
fixed in  683ec52
