### ISSUE TITLE
Contact points sometimes not on surface of convex hull

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#211]
I have made an issue in Bullet, and this one is just to track it in regards to Siconos development.

https://github.com/bulletphysics/bullet3/issues/1563

This week I decided to try to get to the bottom of some contact point issues that have bothered me for a long time.  After resolving a few issues lately, I still got points in the wrong locations, e.g.:

![image](https://user-images.githubusercontent.com/66805/36311823-4b59ac74-130b-11e8-9386-963df8ee9ad0.png)

As you can see there is one contact with points on the surfaces of the objects, and 3 contacts with points inside the surface of the bottom object.  After reproducing the bug using Bullet-only code, as seen in the linked issue, I'm pretty sure this is a bug in Bullet, so I will post an update here when it is resolved.

**Comment by radarsat1** [comment]
In case it wasn't clear, the points inside the surface are generated by the "rotation perturbation" feature of Bullet, where the smaller object is rotated in a few directions to find new contact points.  After rather a lot of analysis and trying things, I found that this goes away if you comment the `QUEUE_STATIC_CONTACTORS` flag in `SiconosBulletCollisionManager.cpp`, which changes the order in which moving and static objects are added.  Indeed there are a few code paths (calculations) in Bullet that are different depending on which object is first.

**Comment by radarsat1** [comment]
I have made a PR for Bullet:  https://github.com/bulletphysics/bullet3/pull/1564

With the proposed change, the same output as above appears as:

<img src="https://user-images.githubusercontent.com/66805/36313672-00e648f4-1311-11e8-89d1-59f3c9a83b66.png" width="300">

which looks a lot healthier.

**Comment by radarsat1** [comment]
Merged! :)

**Comment by vacary** [comment]
super rapid answer of @erwincoumans. really great.
Do you think that we have to base our simulation on the devel branch of bullet ?

**Comment by radarsat1** [comment]
Things were working well enough without this fix, especially if the static contactors were added in the right order with respect to the dynamic objects.  (That's the effect of QUEUE_STATIC_CONTACTORS in SiconosBulletCollisionManager.cpp, to reverse the order in which static and dynamic objects are added.. maybe it is not needed now!)

In particular it only affect the location of contact points, but as long as the contact point *distance* was correct it should generally give the same behaviour (I think..)

But, yes, I think this should improve things, so if you can use an updated Bullet, all the better.  I will use this version and continue to watch for problems as I test.  I think it's very very important that we get reliable contact information, I hope the last of these problems is now licked!

**Comment by radarsat1** [comment]
I also want to soon test and see if this was somehow related to the "popcorn" behaviour..  the contact points being away from where they should be could maybe have contributed to sudden torque? (hypothesis... )

**Comment by radarsat1** [comment]
Oh, just noting here something @erwincoumans mentioned in the PR response:

> Note that you can also enable separating axis test (SAT) and contact clipping for convex hulls, which also > computes multiple contact points directly (without perturbation).

    world->getDispatchInfo().m_enableSatConvex=true;

> and for each convex shape:

    convexShape->initializePolyhedralFeatures();

We should try it!
