### ISSUE TITLE
[cmake] add a WITH_FORTRAN option

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#22]
motivations:
- not all platform have a fortran compiler easily available (Windows, Mac OS X)
- not all build system support fortran (Ninja, VS, ...)

We would loose at least:
- ql0001
- odepack
- hem5

Todo:
- add a cmake option WITH_FORTRAN
- and a bunch of "if defined(WITH_FORTRAN) ... else ... endif" in
  - LsodarOSI.{h,c}pp
  - Hem5OSI.{h,c}pp
  - lcp_nsqp.c, lcp_qp.c

Optional:
- add sundials (CVODE) to have a good event-driven integrator even if WITH_FORTRAN=NO

**Comment by xhub** [comment]
Unfortunately, I don't have time to implement this now. This is low priority and should not block a release.

**Comment by vacary** [comment]
fixed in #199
