### ISSUE TITLE
pep8 compliance for mechanics_io functions

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#220]
This means changing function names from camelCase to snake_case

for example addPluginSource => add_plugin_source, addObject => add_object

As we may have reach some stability, this may be the good time to do this (so before the next release)

If you agree, I can do it for next week.

**Comment by radarsat1** [comment]
Sure, sounds okay to me.  What about `io.addNewtonImpactFrictionNSL`?  Do we leave it with the C++ class name, `add_Newton..`, or should we rename it, `add_non_smooth_law`?

I added `addRelayNSL` and `addNewtonImpactNSL` for the joint friction and joint stops, perhaps we should combine these similar to `addJoint`.  On the other hand each NSL potentially takes different parameters so it makes sense to have different functions for them.

I thought that one possibility could be to support parameters as a dict, and use `**`, that would be very portable to new classes, e.g. getattr(siconos.kernel, 'NewtonImpactNSL')(**{'e': 0.5})

But unfortunately it seems that the SWIG-generated class constructors in this case do not support named parameters.
