### ISSUE TITLE
Contactors not related to effective collision_group slow down the collision detection

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#221]
As mentioned in #134, the addition to an example of "fake" contactors that are not related to a collision_group then into account by a slaw slows down the computation.

Here is an example 

https://github.com/vacary/siconos/blob/avatar/examples/Mechanics/RockFall/cubes_sphere_contactors.py
 
where the a cube contactor is added for visualization purpose.

Comparison with the fake contractor
real	1m12.432s
user	1m12.104s
sys	0m0.235s

and without:

real	0m26.262s
user	0m26.049s
sys	0m0.195s

**Comment by radarsat1** [comment]
It's possible with enough extra objects it adds up.  In particular this invokes the ConvexConvex bullet algorithm when it is not needed.  One solution is to properly synchronize the Bullet contact filtering mechanism with our collision_group property, the other is to simply avoid adding objects to the Bullet CollisionWorld that do not have associated NSLaws.

The former is a bit more work but probably better since the latter requires scanning all objects in the scene for each contactor to see if any potential contact pairs exist.

**Comment by vacary** [comment]
If it is just for avatar visualization, it is perhaps not very mandatory to do such a work.

**Comment by radarsat1** [comment]
Yes, that's another possibility, it needs a way to identify avatar objects and not add them to the Bullet scene.  We could reserve a collision_group (e.g. -1 ?) or have another property.

**Comment by radarsat1** [comment]
Please try f8e84011, change collision_group to -1 for avatar objects.

**Comment by radarsat1** [comment]
I should mention that the reason for the slow-down is excessive collision detection at every single timestep between the avatar Bullet collision objects and the objects they are on top of (e.g. sphere-cube collisions for every sphere-cube pair, meaning 4x8 = 32 extra contacts per cube that are not used).  It is better to not create Bullet collision objects at all when we can indicate that they are not for contact detection, so this solution makes sense imho.

**Comment by vacary** [comment]
Many thanks. The solution with the collision_group=-1 is perfect for me. It divided the time by 20 on the simulation cubes_sphere_contactors.py.

Let us do it like for the moment. Should we close the issue #134 or should we keep as an enhancement the fact that we can add avatar for visualization?

**Comment by radarsat1** [comment]
I'm just adding support for g==-1 to vview, then I will close #134.

**Comment by vacary** [comment]
Why do you need support for collision_group=-1 ?  It works for me.

**Comment by radarsat1** [comment]
I mean, an option to view only the objects with g==-1 if any of them have g==-1.  Well, I am fixing up a bit the visibility/colouring code for actors in general and so I'll include a "view only avatars" mode.

**Comment by radarsat1** [comment]
Done in db987eb00984b1b32734325cc8962b083b4bea24
