### ISSUE TITLE
Examples: ball and chain breaks

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#226]
If I run this example [ball_and_chain.py](../blob/master/examples/Mechanics/InterestingDynamics/ball_and_chain.py) with the latest siconos, the chain breaks itself. Everything goes well in the video:

[ball_and_chain on youtube](https://www.youtube.com/watch?v=obGfJTuS1tA)

**Comment by radarsat1** [comment]
It's a great example for stress testing collision detection issues ;)
For me the chain breaks if I revert to Bullet 2.87, but if I run it with Bullet master then it does not break.
So try updating Bullet to its master branch.  The fix should be included in the next Bullet release.

**Comment by radarsat1** [comment]
I should mention that it does still break for me if I add restitution (e=0.3).  Not perfect!  It's a good stress test.
However, if I set worldScale=10 it still works with e=0.3.  Very good news, as it is evidence that the breaking is purely a contact detection issue.

**Comment by bremond** [comment]
Ok let's close this for 4.2
