### ISSUE TITLE
Simple Shape rendering in siconos_vview

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#231]
This issue is related to #134 
In 6d84226, I changed constructions of 'Shape' by 'Contactor' with collision_group=-1 (fake contactor) to be able to render hdf5 files produced by siconos_mechanisms, that is
```
io.addObject('artefact-{0}'.format(shape_name),
-                         [Shape(shape_name)],
+            io.add_object('artefact-{0}'.format(shape_name),
+                         [Contactor(shape_name,collision_group=-1)],
```
Nevertheless, it was working before with simple Shape but it seems that the "new" version of siconos_vview is only able to deal with Contactors. It seems that something has been broken with the direct use of the  Shape class. 

Since it is a bit curious to declare contactors everywhere just for visualization, I am wondering if it possible to work with a mixed list (Shape or Contactor), as before, to render shape objects that are not related to contact. It is not a crucial change but more something aesthetic.

If it is too much work for a cosmetic change, we can close this issue right now :-0

**Comment by radarsat1** [comment]
No worries, assign all such issues to me ;)  I knew that refactor might introduce some bugs.  And indeed, I forgot to check mechanisms, sorry!  I'll look into it.

**Comment by vacary** [comment]
I just mention that putting Contactor everywhere makes siconos_mechanisms working well

**Comment by vacary** [comment]
Finally, it is more important than I have expected. For the occ interface, @bremond uses the Volume for computing inertia and then it not possible to replace the Volume object by a Contactor with the collision_group=-1.

**Comment by vacary** [comment]
I try a simple fix in bd5ba01d

**Comment by radarsat1** [comment]
I never really considered the role of Shape and Volume much, apologies.  I see that the list can contain a Volume that adds extra information for inertia calculation, but is not actually a Contactor.  So there certainly may be interest in visualizing it, and thus giving it collision_group=-1 is a fairly logical solution.  None would be fine too, if we want to distinguish, but this works.  Close?

**Comment by vacary** [comment]
yep
