### ISSUE TITLE
Link with cblas

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#238]
This is related to #233 

In siconos_find_common_dep.cmake, we now have 
```
compile_with(BLAS REQUIRED SICONOS_COMPONENTS numerics externals)
compile_with(LAPACK REQUIRED SICONOS_COMPONENTS numerics externals)
```
and the siconos_kernel libraries fails to link on my computer due to missing dependencies in 
SiconosVector that calls directly cblas stuff

With the following modifications,
```
compile_with(BLAS REQUIRED SICONOS_COMPONENTS kernel numerics externals)
compile_with(LAPACK REQUIRED SICONOS_COMPONENTS kernel numerics externals)
```
it works,

Should we change the code in SiconosVector such that it relies on Numerics or to add the previous lines in the cmake file ?

**Comment by radarsat1** [comment]
Ah, that makes sense.  The latter is fine by me.  I'm surprised this didn't cause a problem on Linux.

**Comment by radarsat1** [comment]
Hm, I think I found similar issues with io.  Every class has the siconos_io function which means it's a global dependency.
