### ISSUE TITLE
Errors in Fedora CI

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#239]
Travis jobs have been failing only in Fedora, c.f. https://travis-ci.org/siconos/siconos/jobs/364257072
with respect to all Python numerics tests.

I have been trying but I am unable to reproduce this outside the CI environment, when I run the container manually and run ctest the tests pass. I am at a loss, perhaps someone else has better luck?

Its probably simply a path issue but I can't see how it was introduced by recent changes.

```
The following tests FAILED:
	 19 - python_test_friction_contact, (Failed)
	 20 - python_test_lcp, (Failed)
	 21 - python_test_linalg, (Failed)
	 22 - python_test_mcp, (Failed)
	 23 - python_test_mcp2, (Failed)
	 24 - python_test_mlcp, (Failed)
	 25 - python_test_ncp, (Failed)
	 26 - python_test_sparse, (Failed)
	 27 - python_test_vi, (Failed)
	595 - python_test_Kernel, (Failed)
	596 - python_test_bouncing_ball, (Failed)
	597 - python_test_diode_bridge, (Failed)
	598 - python_test_dynamical_systems, (Failed)
	599 - python_test_lagrangiands_osi, (Failed)
	600 - python_test_matrix_exp, (Failed)
	601 - python_test_modelingTools, (Failed)
	602 - python_test_xml, (Failed)
	815 - python_test_smc, (Failed)
CMake Error at /home/travis/build/siconos/siconos/CI/machinery/CTestDriver.cmake:161 (message):
   *** test failure *** 
```

**Comment by bremond** [comment]
> when I run the container manually and run ctest the tests pass.

I was in the same situation, I can now reproduce the results in Travis
by cleaning docker:
docker system prune -a -f
(just the cache should be cleaned, maybe there is something lighter...)

With that, in build--fedora-latest-default/
make docker-build 

build totally the container (nothing is cached)

So, I understand that this is a fedora update that cause the problem,
with an "old" fedora:latest, such as the one that was in our cache it
was ok.

**Comment by radarsat1** [comment]
Ah, that explains it, I did not think about it just being caused by an update on the Fedora side.

**Comment by radarsat1** [comment]
Hm, I rebuilt the docker image from scratch but all the tests are still passing for me.. :(

**Comment by radarsat1** [comment]
That is to say, when I run the CI/driver.py, it seems to fail in a similar way to Travis, but when I enter interactive mode and run ctest, everything passes.  It's very strange.

**Comment by bremond** [comment]
The problem comes from cmake. I simply switch to an older cmake version (3.02) in [siconos.yml](../blob/master/CI/config/siconos.yml) and it works (https://travis-ci.org/siconos/siconos/jobs/371477043). Note that, to be effective on your computer, you have to delete the previous volumes to see the installation of cmake in `/usr/local`: just do `docker rm /ci_driver-fedora-latest-gcc-openblas-lapacke-usr-local`. The workaround for CI is in c8dbe6d34a. We have to remember that cmake-3.11 is not a friend of us at the moment: it fails at setting the correct dependencies between swig files and generated docstrings..

**Comment by radarsat1** [comment]
Wow.  Yes, I just verified that it is fixed when I run CI/driver.py locally now.  Thank you, nice work.

(I get an error with SOCLCP_test3 but that must be something different.)

**Comment by bremond** [comment]
SOCLCP_test3 ...

https://travis-ci.org/siconos/siconos/jobs/372021091
