### ISSUE TITLE
[MechanicsIO::contactPoints] Copy/Paste code error

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#242]
Hi, in:
https://github.com/siconos/siconos/blob/e32a26627237460fcabb399dbf872743ffdba99e/io/src/mechanics/MechanicsIO.cpp#L345
shouldn't it be `ds2->number()` instead ?

**Comment by vacary** [comment]
@batzkass thank you for this feedback.

This is fixed in cbf892f

**Comment by vacary** [comment]
As follow-up, in Siconos, the fixed (static) objects in the scene are not viewed as dynamical systems, i.e, no dynamics is related to these objects. As a consequence, the interaction between a dynamical object (ds1) and a static object only involved the ds1. In the graph, we implement the interaction a source ds (ds1) and target ds (ds2). In this particular case, ds1=ds2.

We use also this trick to detect if an interaction concerns one or two ds (bodies)
