### ISSUE TITLE
[doc] - download.rst

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#243]
According to the [installation doc](https://github.com/siconos/siconos/blob/master/docs/sphinx/install_guide/download.rst#L22), the git clone command line is:
`git clone git@github.com:siconos/siconos.git`
This way, only registered users can download the code, raising a "permission denied" issue for others. 

Using:
`git clone https://github.com/siconos/siconos.git`
would allow anybody to download it.

**Comment by vacary** [comment]
thanks
We will correct soon in the new version of the documentation
https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/index.html

**Comment by xhub** [comment]
Looks like we haven't push the the new version.

**Comment by fperignon** [comment]
done!

Beware of the address, without 'mirror' in the name :
https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos/install_guide/download.html
