### ISSUE TITLE
[io.mechanics] allow disabling output in hdf5 during simulation

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#245]
This is a python patch which allows to disable the hdf5 records during simulation if `output_frequency==0`. In my case I use the `io.mechanics run()` function but I retrieve all data during simulation with a controller.

[PATCH-output_frequency-disable.txt](https://github.com/siconos/siconos/files/2048864/PATCH-output_frequency-disable.txt)

**Comment by vacary** [comment]
The patch has been applied in ff5a1770ca981bf16f681c083417d871e704f4f7
Thanks @batzkass

**Comment by vacary** [comment]
I close the issue. Feel free to reopen if needed.
