### ISSUE TITLE
[doc] remove all date and author version oxygen  entries in C/C++ source files 

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#247]
A suggestion of @fperignon is to remove  all \date and \author \version  entries in C/C++ source files. I fully agree with that. What do you think ?

**Comment by bremond** [comment]
I agree also, date and authors are in already in git

**Comment by xhub** [comment]
Sounds good!

**Comment by xhub** [comment]
I believe this as been fixed in 9a9edacbf5d7f1d75af2e768362aef050c79ef73

Reopen if that's not the case. There are still references in the examples
