### ISSUE TITLE
reading and completing the documentation of mechanics and control interface

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#248]
After a complete refactoring of the documentation (thanks @fperignon ), we have to take the opportunity to read, correct and complete the documentation.

I closed #25 and #26 where some old discussions are presented to renew to renew the process

**Comment by fperignon** [comment]
the last version of the doc is now published (
CI process from https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-mirror <https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-mirror>
to siconos.gforge.inria.fr <http://siconos.gforge.inria.fr/> or https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/index.html <https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/index.html>)

check the API C++ (https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/reference/siconos_api_reference.html <https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/reference/siconos_api_reference.html>)
and the API Python (https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/reference/python_api.html <https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos-mirror/reference/python_api.html>)
I think there are still a lot of things to review especially bugs in latex formula processing.

**Comment by bremond** [comment]
>I think there are still a lot of things to review especially bugs in latex formula processing.

Here is one

https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos/reference/python/kernel/MoreauJeanOSI_pyclass.html

**Comment by vacary** [comment]
Transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
