### ISSUE TITLE
Build failure, ubuntu 17.10

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#253]
See :

https://cdash-tripop.inrialpes.fr/viewBuildError.php?buildid=963

Compilation may be achieved by running 'make' rather than 'make -j N'. 
Seems to be a problem of dependency / order of generation of some targets/files (swig builds) required by building process? But why only on ubuntu???

**Comment by xhub** [comment]
I see a lot of compiler failures:

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See  for instructions.
[ 99%] Linking CXX shared module ../../wrap/siconos/mechanics/collision/_base.so
```

My hypothesis is that the system runs out of memory. Does this build have serialization?

**Comment by fperignon** [comment]
> Le 13 sept. 2018 à 15:37, Olivier Huber <notifications@github.com> a écrit :
> 
> I see a lot of compiler failures:
> 
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See  for instructions.
> [ 99%] Linking CXX shared module ../../wrap/siconos/mechanics/collision/_base.so
> My hypothesis is that the system runs out of memory. Does this build have serialization?
> 
> 

don’t know but I tried to build on ubuntu 17.10 without serialization and have the same problem.
I also thought about this memory thing and try to monitor it but for the moment I haven’t seen anything
explaining the failure.
I don’t know if we can increase the memory allocated to a docker container used during CI?

**Comment by xhub** [comment]
As long as it's an ICE or getting killed, I think it is a code issue. The build on cdash is with serialization. We should restrict it to -j1, if it not the case. If serialization is enable, it is almost surely going to OOM when building those parts. The other option would be to add some swap on disk.

When you built, did it work with make -j1? Is the 17.10 image/install up-to date? On that machine, does it work with with a different version of GCC or clang?

On that built, GCC is at version 7.2.0, there is version 7.3 available. It may fix that issue, if it is not memory related.

On CI, the build with 17.10 and C++11 is OK: https://cdash-tripop.inrialpes.fr/buildSummary.php?buildid=974

**Comment by xhub** [comment]
I think we can close. We only test 17.10 with C++11, and it works fine. Also 17.10 is not an LTS and is more than a year old, not a priority in my opinion. Feel free to reopen if I missed something
