### ISSUE TITLE
Manually move dynamical systems

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#257]
Hi,

I use the python interface to setup and track mechanical (NewtonEuler) simulations, with something similar than [this example](https://github.com/siconos/siconos-tutorials/blob/master/examples/mechanics/RockFall/cubes_sphere_contactors.py). I wonder how I could manually move a dynamical system.
I can see in [this example](https://github.com/siconos/siconos-tutorials/blob/master/examples/mechanics/BouncingBall/BouncingBallTS.py#L113) how to get a pointer to the q and velocity vectors. If I try to modify the values with:
```
myDS.q()[0]=2.
print(myDS.q()[0]) #this prints 2, looks like it worked.
```
The value is however not used in the calculation, it is overwritten by the initial value the first time I run simulation.computeOneStep()

So, is there a way to manually modify the DS properties (velocities, positions) after the initial instantiation ?

Thanks.

**Comment by bremond** [comment]
Hello François,

If you plan to modify the initial coordinates values you gave to the
dynamical system constructor before the simulation start, you have to
modify the vector q0 as well.

Then after the simulation is started, the vector q may be modified
alone.

For example for the python time-stepping bouncing ball you can check
this:

   [...]
   #
   # numpy pointers on dense Siconos vectors
   #
   q = ball.q()
   v = ball.velocity()
   p = ball.p(1)
   lambda_ = inter.lambda_(1)
   
   
   # modification of the initial state (1 ==> 10)
   q[0] = 10
   ball.q0()[0] = 10
   [...]

and in the simulation loop:

   while s.hasNextEvent():
       s.computeOneStep()
   
       dataPlot[k, 0] = s.nextTime()
       dataPlot[k, 1] = q[0]
       dataPlot[k, 2] = v[0]
       dataPlot[k, 3] = p[0]
       dataPlot[k, 4] = lambda_[0]
   
       k += 1
       if k == 200:
           ball.q()[0] = 2
       s.nextStep()
   

This is the same for a Newton Euler system, the initial position of the
system is saved at construction in a q0 vector, and for example in
BulletBouncingBox/BulletBouncingBox.py

   [...]
   #
   # numpy pointers on dense Siconos vectors
   #
   q = body.q()
   v = body.velocity()

   # modification of the initial position
   body.q()[2] = 20
   body.q0()[2] = 20
   [...]

And the modification of the position in the simulation loop:

   # time loop
   while(simulation.hasNextEvent()):
   
       simulation.computeOneStep()
       
       if k == 200:
           body.q()[2] = 10


Maurice

**Comment by batzkass** [comment]
Many thanks for your help.
At this time I found a best way to achieve my aim than the solution of manually move the DS.
Anyway I will later need to manually move/rotate the DS so your explanations will help me, and maybe someone else.
François
