### ISSUE TITLE
vview broken due to Hsource

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#260]
In commit 6ee68f7d3efea70e6c411538ab81cd41877d84bd there is a class added called Hsource, which derives from VTKPythonAlgorithmBase which is not yet imported.  I don't see Hsource referenced anywhere else so I don't know whether to remove it or not, but notice that `vtk` is imported later in the script after there is a chance to process command-line args, so I suggest putting anything using vtk after that point.

**Comment by radarsat1** [comment]
```
$ python3 io/swig/io/vview.py 
Traceback (most recent call last):
  File "io/swig/io/vview.py", line 774, in <module>
    class Hsource(VTKPythonAlgorithmBase):
NameError: name 'VTKPythonAlgorithmBase' is not defined
```

**Comment by bremond** [comment]
Sorry about that, this was not meant to be commited.

this says that vview and MechanicsIO must pass some tests.
