### ISSUE TITLE
Build is extremely sensitive to the order of components

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#261]
The order of the declared components of siconos in the build is very important for the building process.

If you ask for
```
set(COMPONENTS externals numerics kernel control io mechanics mechanisms  CACHE INTERNAL "List of siconos components to build and install")
```
building of siconos will fail because the io  component needs  include from mechanics and mechanisms.

Perhaps, we have to check the order of components in the COMPONENTS variable or to reorder them in each COMPONENTS CmakeLists.txt

**Comment by xhub** [comment]
I thought that we could easily make dependence in CMake with add_dependencies https://cmake.org/cmake/help/latest/command/add_dependencies.html

we should have that to control the behavior
