### ISSUE TITLE
BLAS detection

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#265]
I recently changed my os. Again the bas/lapack detection is a nightmare.

Why not embedding BLAS/LAPACK in c in externals ? If the lib are on the system, we use it as for suitesparse ?

**Comment by xhub** [comment]
Is this still an issue or did things settle down? I'm not in favor in embedding BLAS/LAPACK in externals, but we may have too ... I would rather try to dowload openblas from the web if no local install can be found.

**Comment by roccaa** [comment]
When installing on Ubuntu 18.04, it was indeed a problem: 

putting  ``export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH`` in the ``.bashrc``

or the flags:
```
-DWITH_BLAS=atlas 
-DBLAS_LIBRARIES=/usr/lib/x86_64-linux-gnu/libcblas.so
-DLAPACK_LIBRARIES=/usr/lib/x86_64-linux-gnu/liblapack_atlas.so 
-DBLAS_INCLUDE_DIRS=/usr/include/x86_64-linux-gnu/atlas/ 
-DLAPACK_INCLUDE_DIRS=/usr/include/x86_64-linux-gnu/atlas/ 
```
at the ``cmake`` call, solved the problem in my case

**Comment by xhub** [comment]
Does it still fail with the latest master? I did accidentally push some commits that could have messed that up. I hope everything is good now.  If it is still not good, can you please check at d538674e9 ?

**Comment by roccaa** [comment]
It does work fine now. 
It can be useful to put in the online guide the ``cmake`` flags for the optional libraries as they are often in some local/non standard directories.
For example in the case of lp_solve: ``-DLpSolve_INCLUDE_DIR``

**Comment by xhub** [comment]
If it doesn't work with lpsolve install through a distro, please open a bug.

Otherwise, +1 to have more doc on the cmake options

**Comment by roccaa** [comment]
It is detecting correctly the distribution ``lp_solve``.
