### ISSUE TITLE
Require at least C++11

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#268]
C++11 support has been around for quite some time. We can require a compiler supporting this version of C++. This would allow us to
- use delegating constructor (see #98)
- use initializer list (for SiconosVector({1.0, 4.2, 5.}, and SiconosMatrix)
- more auto keyword? (especially for dealing with those iterators)

**Comment by vacary** [comment]
I vote for that

**Comment by fperignon** [comment]
So do I.
I'm  working on this having in mind the use of "modern" cmake things like
 target_compile_features(myTarget PUBLIC cxx_std_11)
By the way I think it would be the opportunity to review all the compiler options we set in CC/CXXcompilersetup.cmake

**Comment by xhub** [comment]
Super. For the compiler options, a PR or issue to discuss it would be great.
