### ISSUE TITLE
[windows] port of Siconos

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#269]
An issue for an open discussion about a port of siconos on Windows.

For the moment, possible ways might be
- use the Ubuntu Console in Windows to perform installation as on Linux Machine
- full port through visual studio
- a conda package
- docker vm
- standard vm

What do you think ?

**Comment by xhub** [comment]
I was able to compile siconos on windows using visual studio a few years ago. I was closed to make it work on appveyor (see the appveyor.yml file), to have a windows CI.

I also had some binaries created using cross-compilation, but 5 or 6 years ago.

Recently I had good success using LLVM to cross-compile from Linux to windows, using the Visual Studio SDK. It looks really sturdy.

I think that a conda package would be also great to allow people to install siconos easily.

VM are rather limited in usefulness.

**Comment by xhub** [comment]
Also see the other packaging issues for ideas on Windows https://github.com/siconos/siconos/labels/packaging

**Comment by vacary** [comment]
I added here issue #47

NSIS has some scripting capabilities that could be leverage to provide a nice NSIS installer for Siconos with some dependencies "automatically" installed, like the MSVC C++ redistribuable kit.

Freecad seems to be using this technique and we could use their NSIS-related file as templates.

**Comment by vacary** [comment]
I transfer here the issue #56

See https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/

It would enable us to remove a few hacks if it is does the job.

**Comment by vacary** [comment]
Transferred in https://github.com/siconos/siconos/wiki/Wish-list-and-enhancement
