### ISSUE TITLE
[python] copy values from SiconosVector to numpy

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#270]
Right now, when calling in Python a C++ function with a SiconosVector argument, if the later is modified, then the value is not updated in the numpy object. The root cause is that a the data storage for a SiconosVector cannot be set to a specific memory area. Hence, we always have to do a memory allocation (bad) and then copy the values from the numpy object to the SiconosVector. Possible fixes:

- Add a boolean to control whether we need to copy the values from the SiconosVector back to the numpy object. This would be easy, we already have to track whether we allocate some memory. We can then do a memcpy from the SiconosVector values to the numpy object

- Make it possible to create a SiconosVector from a memory area. This would mean that the size is constant (but that's not a major issue), then we have nothing to do (except when we had to allocate memory in the numpy conversion for whatever reason). However, this is nontrivial. It is worth doing tho, since it would enable the evaluation of the dynamics from the Solver

I plan on doing method 1 soon

**Comment by xhub** [comment]
In both your example, we start from a SiconosVector object, and build a numpy object. I'm talking about another case, where we start from a numpy object. The example is from @roccaa 
```
rel1_C = sk.FirstOrderNonLinearR()
import os
print('Compilation of the C plugin with Siconos')
from subprocess import call

call(['siconos','--noexec','.'], stdout=open(os.devnull, 'wb'))
rel1_C.setComputehFunction('Relation1Plugin','computeh')

t = 0.0
y = np.ones(2)
x = np.ones(18)
λ = np.zeros(2)
z = zeros(0)
rel1_C.computeh(t,x,λ,z,y)
y
```

Here the numpy object ```y``` is not updated. In the SWIG glue, this correspond to the ```SP_SiconosVector_from_numpy``` function in ```wrap/swig/KernelTypes.i``` A temporary SiconosVector is created, and the values of the numpy object are copied. If the values of the SiconosVector are changed (as it is the case for y in FirstOrderNonLinearR::computeh), the changes are not propagated to the numpy object. This would require a memcpy from the SiconosVector to the numpy array at the end of the function (close to the freearg part).

**Comment by bremond** [comment]
Ok, I understand now. Note that  in this case you can simply do:
```python
y = np.ones(2)
sy=siconos.kernel.SiconosVector(y)
yp = siconos.kernel.getVector(sy)
```
etc.
and pass the SiconosVector ```sy``` to the function.
You get the updated ```SiconosVector``` ```sy``` array as well as the ```numpy``` ```yp``` one .
Well, I haven't tested, but if it does not work we can raise an issue.

If you do not go further, I propose this solution.
What you are speeking about would be needed if, on the python side, you get the input numpy arrays from another software than siconos, and that arrays are also input to this other software.
For the moment, I haven't seen this situation.

**Comment by xhub** [comment]
Here is a self-contained example: in short, all approached failed, but the one with a SiconosVector opaque pointer. For me this is not a trivial issue because of the lack of correctness. We make the promise to have a transparent numpy usage, but it is not true, since only the flow of information only  goes from numpy to Siconos. In many instances, this is fine (constructors, ...). Here the idea was more to use some functions for debugging purpose (like debugging the computeh from a C plugin). I don't think that there will be much cost to add a boolean in that case in the swig clue and copy back. 

```python
import siconos.kernel as SK                                                                                                                                                                                                                                                    
import numpy as np                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
from cffi import FFI                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                               
ffibuilder = FFI()                                                                                                                                                                                                                                                             
ffibuilder.set_source("_example", r"""                                                                                                                                                                                                                                         
    #include <stdio.h>                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                               
    void computeh(double time, unsigned int xsize, double* x, unsigned int lambda_size, double* lambda                                                                                                                                                                         
                                            , double* y, unsigned int zsize, double* z) {                                                                                                                                                                                      
    printf("On entry: y = [%f, %f]\n", y[0], y[1]);                                                                                                                                                                                                                            
    printf("Pointer values: x = %p, lambda = %p, y = %p, z = %p\n", x, lambda, y, z);                                                                                                                                                                                          
    printf("Array sizes: xsize = %d; lambda_size = %d; zsize = %d\n", xsize, lambda_size, zsize);                                                                                                                                                                              
    y[0] = 42.;                                                                                                                                                                                                                                                                
    y[1] = -42;                                                                                                                                                                                                                                                                
    printf("On exit:  y = [%f, %f]\n", y[0], y[1]);                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                          
""")                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                               
ffibuilder.cdef("""                                                                                                                                                                                                                                                            
    void computeh(double time, unsigned int xsize, double* x, unsigned int lambda_size, double* lambda , double* y, unsigned int zsize, double* z);                                                                                                                            
""")                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                               
pluginname = ffibuilder.compile(verbose=True)                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                               
y = np.ones(2)                                                                                                                                                                                                                                                                 
y1 = np.ones(2)                                                                                                                                                                                                                                                                
y2 = np.ones(2)                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                               
sy = SK.SiconosVector(y1)                                                                                                                                                                                                                                                      
yp = SK.getVector(sy)                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                               
sp = SK.SiconosVector(y2)                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
FONLR = SK.FirstOrderNonLinearR()                                                                                                                                                                                                                                              
FONLR.setComputehFunction(pluginname, "computeh")                                                                                                                                                                                                                              
FONLR.computeh(3., (), (), (), y)                                                                                                                                                                                                                                              
FONLR.computeh(3., (), (), (), yp)                                                                                                                                                                                                                                             
FONLR.computeh(3., (), (), (), sp)                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
print("y = {}; yp = {}; sp = {}".format(y, yp, sp))                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                               
assert np.linalg.norm(np.asarray(sp) - (42,-42)) < 1e-10                                                                                                                                                                                                                       
assert np.linalg.norm(y - (42,-42)) < 1e-10                                                                                                                                                                                                                                    
assert np.linalg.norm(yp - (42,-42)) < 1e-10
```

**Comment by xhub** [comment]
I just add that when the base object is a numpy array, the flow of information is unidrectional.

Whenever the base object is a siconos object, it is bidirectional

**Comment by bremond** [comment]
Thank you for the efficient self contained example!  But in your example, there is no difference between the ```y``` and ```yp``` checks: they are both made after a call to computeh with a numpy array, so they show the same thing. You can see the ```getVector```  trick if you do not call ```computeh``` with ```sy``` but with ```yp```. If you change this, the check on ```yp`` is ok. Obviously, the one on ```y``` is false. I made some simplifications and add some comments to only show this bidirectional way with a numpy pointer on a working copy of the data (at the end of the comment).
My question is: does this simple solution, I mean this 3 steps procedure:

1. we have a numpy array, it can only be an input to siconos
2. we make a copy inside a SiconosVector for siconos input/output, thanks to ```SiconosVector``` copy constructor which accepts a numpy array as input.
3. we get a new numpy pointer on the values inside the SiconosVector for python input/output, thanks to the```getVector``` function.

can fit the needs of @roccaa ?

"We make the promise to have a transparent numpy usage"
I think we should not say that, but only transparent from siconos data.
With bound or fixed vectors, we would be able to do so.
To come back to the first point, with a boolean somewhere, don't we risk to get weird cases?
I think at what happens to a numpy state passed to a LagrangianDS after its modification inside the kernel.
It is supposed to be modified on the fly (the side effect magic of oo programming!) as in the BouncingBallTS.py. How a boolean can be helpful in this case ?

Here are my simplifications to your example:
```python
import siconos.kernel as SK
import numpy as np
from cffi import FFI

ffibuilder = FFI()
ffibuilder.set_source("_example",
r"""
 #include <stdio.h>
 void computeh(double time, unsigned int xsize, double* x, unsigned int lambda_size, double* lambda, double* y, unsigned int zsize, double* z) {

 printf("Pointer values: x = %p, lambda = %p, y = %p, z = %p\n", x, lambda, y, z);
 printf("Array sizes: xsize = %d; lambda_size = %d; zsize = %d\n", xsize, lambda_size, zsize);
 y[0] = 42.;
 y[1] = -42;
 printf("On exit:  y = [%f, %f]\n", y[0], y[1]);}                                   """)

ffibuilder.cdef("""                                                                     void computeh(double time, unsigned int xsize, double* x, unsigned int lambda_size, double* lambda , double* y, unsigned int zsize, double* z);                     """)

pluginname = ffibuilder.compile(verbose=True)

# 1. we have a numpy array, it can only be an input to siconos
y = np.ones(2)

# 2. we make a copy inside a SiconosVector for input/output
sy = SK.SiconosVector(y)

# 3. we set a pointer on the values inside the SiconosVector for
#    bidirectional access from python
yp = SK.getVector(sy)

FONLR = SK.FirstOrderNonLinearR()
FONLR.setComputehFunction(pluginname, "computeh")
FONLR.computeh(3., (), (), (), sy)
print("y = {}; yp = {};".format(y, yp))
assert np.linalg.norm(np.asarray(yp) - (42,-42)) < 1e-10
```

**Comment by vacary** [comment]
Clearly, in a DIRECTOR class (Python inherited class from  c++ class), the question of access is always a nightmare, see for instance, [FastSpinningObjects.py](https://github.com/siconos/siconos-tutorials/blob/master/examples/mechanics/NewtonEuler/FastSpinningObjects.py) where I was obliged to test if the call is made from Python or for the C++ and to add a function internal functions in [NewtonEulerR.cpp](https://github.com/siconos/siconos/blob/master/kernel/src/modelingTools/NewtonEulerR.cpp)

Firstly, I propose to put this simple self contained example at the top of the documentation of the use of siconos in Python.

Secondly, should we think about an alternative to boost:ublas based on std::vector with an implementation with a fixed C array as Maurice starts to propose ?

**Comment by bremond** [comment]
"You can see the getVector trick if you do not call computeh with sy but
 with yp."

Sorry, read : "You can see the getVector trick if you do not call computeh with yp but
 with sy.".

**Comment by roccaa** [comment]
@bremond I see.
If I want to work with numpy as inputs (and as observers ... ), as first need to initialize this numpy object as recasted pointer to siconos objects.
Example (assume whatever you want in computeh() as long as it does not change the pointer ...):
```
rel1_C = sk.FirstOrderNonLinearR()
import os
print('Compilation of the C plugin with Siconos')
from subprocess import call

call(['siconos','--noexec','.'], stdout=open(os.devnull, 'wb'))

rel1_C.setComputehFunction('Relation1Plugin','computeh')

# A useless unitary example
t = 0.0
y = np.ones(2)
sy= sk.SiconosVector(y)
y = sk.getVector(sy)
x = np.ones(18)
λ = np.zeros(2)
z = zeros(0)
rel1_C.computeh(t,x,λ,z,y)
rel1_C.computeh(t,x,λ,z,sy)
print("y  = ", y, " -- should be [-0.5, -0.5]")
print("sy  = ", sy, " -- should be [-0.5, -0.5]")
```
This correctly ouputs:
```
Compilation of the C plugin with Siconos
y  =  [-0.5 -0.5]  -- should be [-0.5, -0.5]
sy  =  [2](-0.5,-0.5)  -- should be [-0.5, -0.5]
```
Which is ok. The redefinition of ``y`` is a bit heavy from a user point of view but that's fine.
Thanks for your replies.

**Comment by xhub** [comment]
I will try propose a PR to memcpy the SiconosVector array back into into the numpy one. I know it is nowhere written that we explicitly support change to a numpy array in the siconos code, but there is nothing that warns against it either. I don't think that written it in the doc is a good fix. If I'm evaluating a software and run into this kind of issue, then I'm likely to not use it since the trust that it is working has been damaged.

This is rather a corner case, so I don't expect any major performance hit. If anyone has a big slow python simulation, feel free to see if there is a difference.

For the SiconosAlgebra work, I agree that we could expect good performance improvements by switching to constant size vector and having some custom allocator to not have the memory all over.
But from what I can see that 

Unfortunately, the C++ committee removed the dynarray, and there is not alternative in sight.
I don't think that resizing the size of a vector is used very often ... so we don't really need this feature.
An important feature for me would be to use an existing memory inside the vectors or matrices.
This pages has some useful info https://stackoverflow.com/questions/1735841/initializing-a-ublas-vector-from-a-c-array

One important usecase for me would be the ability to evaluate the function values and jacobians from a optimisation solver. This would use the solver memory arrays.

**Comment by bremond** [comment]
"Edit: that's fine as long as the user keeps in mind that Siconos work
on a copy (right ?) of his original numpy object ..."

@roccaa, yes, you are right, nothing prevents you from forgetting the
need of this copy. At the moment, for siconos, we can say that numpy
arrays are:

 - first-class citizens in the case they are returned by a function of the API,
 - second-class citizens, if they comes from outside.

And from a user point-of-view, the arrays seems the same and this may lead
to some confusions and difficulties.

But the solution is not simple: strides, slices, c or fortran order can
affect the numpy storage of outside numpy arrays. On the siconos part,
side effects may modify the vectors even if they are not passed as
argument of some function (for example a call to ```nextStep()```), so,
I think that all synchronizations attempts at argument passing time will
lead to even more confusing results.

Siconos uses ublas on std::vector as the underlying storage of its
vectors. With bounded or fixed vector under ublas, we could gain an
interface for contiguous numpy array and NewtonEuler dynamical systems
only.

For more than contiguous numpy arrays and for FirstOrder or Lagrangian
systems, for which the size is not known at compile time, we would need
to write or use a true interface ublas to numpy, something as

https://mathema.tician.de/software/pyublas

Note that with pyublas, not all slices are possible. So, even if we were
at this level, far better than what we have now, the segregation between
some numpy arrays would remain and the user would still have to be
carefull (but ok less than today!).

Technicaly, I think that probably this kind of ublas/numpy could be
inserted in siconos, without a total rewrite of the whole kernel, the
same way as it is done for ublas/array in #127 : it would need a
NumpyStorage class at the same level as the BoundedStorage one.

**Comment by vacary** [comment]
up,
This question is again on the top of the todo list. 
Since we plan to introduce namespaces in the nest version of siconos, the question of the swig wrapper starts to be problematic. We plan to use instead pybind11. In that case, we have some further possibilities:
- to implement glue code pybind11/ublas as in https://mathema.tician.de/software/pyublas
- to switch to built-in [pybind11/Eigen interface](https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html)
with again the question of transparency and safety for users and compatibility with numpy.

At least, to SiconosVector to numpy, pybind11 provides everythinf for a coherent interface
