### ISSUE TITLE
build documentation for the master branch

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#271]
Do we have a build of the documentation for the master branch? It would be nice so that we can also easily see and update part of the docs.

Thanks!

**Comment by fperignon** [comment]
yes, but not fully automatic :


you need to add this project as a remote git repos :

https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos <https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos>

and push your changes to this repo 
CI leads to web pages publishing.

And to do so you need an account on gricad-gitlab : 
https://register.gricad-gitlab.univ-grenoble-alpes.fr/index.html <https://register.gricad-gitlab.univ-grenoble-alpes.fr/index.html>

**Comment by xhub** [comment]
Thanks for the setup explanation. I registered a few days ago on gricad-gitlab (handle is also xhub)
