### ISSUE TITLE
Open discussion concerning compilers settings

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#272]
Req :  move to Cxx11 and update compilers setup in Siconos.

We have to review all options defined in CCompilerSetup.cmake, CXXCompilerSetup.cmake
(and opt. FCompiler.cmake) 

For each option, try to answer to the following points : 
-  useful? relevent? 
- still exists in current available compilers? 
- possibly taken into account through a compiler feature    (https://cmake.org/cmake/help/v3.13/manual/cmake-compile-features.7.html)
- range : all components? Only one? 

Bonus : try to follow  'modern' cmake docs requirements : 
  - do not use  things like set(CMAKE_CXX_FLAGS ...)
  - use per-target setup, with things like 

```
target_compile_options(my_library PRIVATE
  # clang/GCC warnings
  $<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:GNU>>:
  "-Wall">
  # MSVC warnings
  $<$<CXX_COMPILER_ID:MSVC>:
  "/W4">)
```

**Comment by vacary** [comment]
Do not hesitate to propose a PR such that we close this issue and we discuss the PR.

**Comment by vacary** [comment]
Any update ? Should it be close ?

**Comment by fperignon** [comment]
no, this is still required but undone.

It mostly consists in reviewing all the options provided in CXXCompiler and CCompiler setup cmake files.

I’ll have a look to this.
