### ISSUE TITLE
Cannot find clapack.h on Ubunu 18.04

### ISSUE THREAD

**Issue by arturrataj** [siconos/siconos#274]
\# apt install libatlas*
$ find /usr -name clapack.h
/usr/include/x86_64-linux-gnu/clapack.h
$ cmake ../siconos
-- Checking to see if CXX compiler accepts flag -D__aligned__=ignored
-- Checking to see if CXX compiler accepts flag -D__aligned__=ignored - yes
-- Performing Test C_HAVE_-D__aligned__=ignored
-- Performing Test C_HAVE_-D__aligned__=ignored - Success
-- Performing Test C_HAVE_-std=c99
-- Performing Test C_HAVE_-std=c99 - Success
-- Found Python executable: /usr/bin/python
-- Found Python library: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
-- Python version is : 2.7.15
-- Python include dir is : /usr/include/python2.7
-- Python Site package dir is : /usr/lib/python2.7/dist-packages

-- Compilation with required package BLAS version
-- Lapack libraries have been found : /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libopenblas.so. We now turn to headers.
-- Found a library with LAPACK API (generic).
Lapack libraries : /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libopenblas.so.
Lapack headers : clapack.h in LAPACK_INCLUDE_DIRS-NOTFOUND.
-- Compilation with required package LAPACK version
CMake Error at cmake/siconos_find_common_dep.cmake:15 (message):
cannot find lapack include directories
Call Stack (most recent call first):
CMakeLists.txt:102 (include)

-- Configuring incomplete, errors occurred!
See also "/home/art/src/siconos-build/CMakeFiles/CMakeOutput.log".
See also "/home/art/src/siconos-build/CMakeFiles/CMakeError.log".

**Comment by arturrataj** [comment]
# apt install libatlas*
$ find /usr -name clapack.h
/usr/include/x86_64-linux-gnu/clapack.h
$ cmake ../siconos
-- Checking to see if CXX compiler accepts flag -D__aligned__=ignored
-- Checking to see if CXX compiler accepts flag -D__aligned__=ignored - yes
-- Performing Test C_HAVE_-D__aligned__=ignored
-- Performing Test C_HAVE_-D__aligned__=ignored - Success
-- Performing Test C_HAVE_-std=c99
-- Performing Test C_HAVE_-std=c99 - Success
-- Found Python executable: /usr/bin/python
-- Found Python library: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
-- Python version is : 2.7.15
-- Python include dir is : /usr/include/python2.7
-- Python Site package dir is : /usr/lib/python2.7/dist-packages

-- Compilation with required package BLAS version 
-- Lapack libraries have been found : /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libopenblas.so. We now turn to headers.
-- Found a library with LAPACK API (generic).
    Lapack libraries : /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libopenblas.so.
    Lapack headers : clapack.h in LAPACK_INCLUDE_DIRS-NOTFOUND.
-- Compilation with required package LAPACK version 
CMake Error at cmake/siconos_find_common_dep.cmake:15 (message):
  cannot find lapack include directories
Call Stack (most recent call first):
  CMakeLists.txt:102 (include)


-- Configuring incomplete, errors occurred!
See also "/home/art/src/siconos-build/CMakeFiles/CMakeOutput.log".
See also "/home/art/src/siconos-build/CMakeFiles/CMakeError.log".

**Comment by arturrataj** [comment]
This helps:
\# apt remove openblas*
$ rm CMakeCache.txt

**Comment by xhub** [comment]
Thanks for the bug report and sorry for the inconvenience. While the root cause is investigated, a workaround could be to use lapacke rather than lapack. Can you retry after runnning ```apt-get install liblapacke-dev``` and see if it works with the lapacke libraries? You may want to restart the cmake process in an empty directory.
