### ISSUE TITLE
Where should we update interactions in the simulation process when a contact collision algorithm is in the loop?

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#276]
This issue is a follow-up of the PR #241. 

The question is when we should call 
```
updateWorldFromDS();	
updateInteractions();
updateContactsFromChangeLog();
```
Several options:
- per each time step
- per each Newton loop

It is a bit tricky because if we update only at the beginning of the time-step, the local frame at contact (related to the Jacobian matrices of constraints) is constant over the time--step and the number of interactions is fixed.
In the Newton loop, we would like to update the local frames at contact (and/or Jacobian matrices of the constraints), to  be more accurate especially if there are some large finite rotations. The problem that we face for the moment, is the fact that some interactions may appear or disappear at each Newton iterations. This can cause some instability in the Newton method.

 We would need to have only an update of the existing local frames without creating or deleting interactions. I do not know if it possible with the current API of bullet and our coupling.

**Comment by radarsat1** [comment]
One idea that I had on this was to call it in the loop, but only ever _add_ contacts and never remove them.  (Per time step, of course, not over the whole sim.)  This would maintain numerical stability (I think), while still allowing them to be created when necessary.  It is tricky, I agree.

> We would need to have only an update of the existing local frames without creating or deleting interactions.

I did however modify the contacts to be maintained in the local frame by recalculating `_pc1`/`_pc2` from members `_relPc1` and `_relPc2` back in 01a06f2cfa5db43cf

**Comment by vacary** [comment]
closed. see #365
