### ISSUE TITLE
assertion error in test_serialization1

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#279]
Using boost 1.67 on debian unstable, I get the following error in test_serialization.py:

```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error-Success
Aborted (core dumped)
```

The test is very simple: `v2.xml_import(v1.xml_export())`

therefore I am worried this is some weird problem with boost 1.67.
This is the output of `v1.xml_export()`:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="16">
<SiconosVector class_id="1" tracking_level="1" version="0" object_id="_0">
	<_dense>1</_dense>
	<vect class_id="87" tracking_level="1" version="0" object_id="_1">
		<data object_id="_2">
			<count>3</count>
			<item_version>0</item_version>
			<item>1.00000000000000000e+00</item>
			<item>2.00000000000000000e+00</item>
			<item>3.00000000000000000e+00</item>
		</data>
	</vect>
</SiconosVector>
```

This looks fine to me, so I don't understand.

**Comment by radarsat1** [comment]
Can anyone reproduce this?

**Comment by xhub** [comment]
The most recent boost I have access to is 1.65. For my newbie eye, we are missing a
```
</boost_serialization>
```
at the end, no?

See https://github.com/boostorg/serialization/issues/82 for some useful comments (and also maybe why this last tag is not in the XML. See also https://github.com/boostorg/serialization/issues/109

I don't have a lot of time to look into that. Also trying with 1.69 may be a good idea.

Also, if one looks at
https://www.boost.org/doc/libs/1_69_0/libs/serialization/doc/release.html
it is a bit worrisome to me that it has not been updated in a while. I don't want to sound too negative, but what's the plan B if the library starts to rot?

**Comment by vacary** [comment]
If I remember well, I had the same problem with boost 1.67 on MacOs. boost/serialization is bugged in this version.

**Comment by radarsat1** [comment]
Okay thank you for confirming that it may have to do with the exact BOOST version, I will try with some other versions to be sure.
