### ISSUE TITLE
[cmake] RPATH Stuff and MACOSX

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#28]
Using RPATH stuff is now mandatory on MACOSX. In [SiconosSetup.cmake](https://github.com/siconos/siconos/blob/master/cmake/SiconosSetup.cmake), there is some lines about RPATH for the linking of library. I do not know how it works but there is not path in the resulting build library.

In a brute force way, I added following the recommendation in [https://cmake.org/Wiki/CMake_RPATH_handling](https://cmake.org/Wiki/CMake_RPATH_handling) 

     if(APPLE)
       set(CMAKE_MACOSX_RPATH ON)
       # use, i.e. don't skip the full RPATH for the build tree
       SET(CMAKE_SKIP_BUILD_RPATH  FALSE)
     
       # when building, don't use the install RPATH already
       # (but later on when installing)
       SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE) 
       
       SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
       
       # add the automatically determined parts of the RPATH
       # which point to directories outside the build tree to the install RPATH
       SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
       
       
       # the RPATH to be used when installing, but only if it's not a system directory
       LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
       IF("${isSystemDir}" STREQUAL "-1")
         SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
       ENDIF("${isSystemDir}" STREQUAL "-1")
     endif(APPLE)

But it doesn't work ...

**Comment by vacary** [comment]
In fact, It works on my MacBook El Capitan 10.11.3
I closed the issue, but do not hesitate to reopen it in case of troubles

**Comment by fperignon** [comment]
Still failed for me on macosx.
Fix coming soon ...

**Comment by vacary** [comment]
Your MacOSX is weird :-) use port :-(

**Comment by fperignon** [comment]
no way ...

**Comment by radarsat1** [comment]
I have one computer on which I think I am having the same problem, so hopefully I can help here.  Not sure what to try right now, but happy to test.
