### ISSUE TITLE
Documentation location and Default value for compute residue

### ISSUE THREAD

**Issue by roccaa** [siconos/siconos#281]
Hello,

I am creating this new issue because I can't find the position of the generated documentation after a cmake with the flag   ``-DWITH_DOCUMENTATION=ON`` (followed by make && make install).

On a subject related to the documentation, I think it is important to detail in the non-linear relations documentation that ``TimeStepping.ComputeResiduY`` and ``TimeStepping.ComputeResiduR`` must be set to ``true`` to handle non-linear inputs (I lost quite a lot of time due to this lack of information). Another solution would be to set them to ``true`` by default ( which would result in increased computational cost in the linear case by default ?) .

Alexandre

**Comment by fperignon** [comment]
Hi,

documentation is generated into <CMAKE_BINARY_DIR>/docs/build/html 

Franck

**Comment by roccaa** [comment]
Hello,

In ``CMakeCache.txt`` I do not have a ``CMAKE_BINARY_DIR`` var,  I guess it is ``siconos_BINARY_DIR`` ?

my ``cmake`` is exactly:
```
cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_INCLUDE_DIRS=/usr/include/python3.6/ -DWITH_DOCUMENTATION=ON  ../siconos/
```
followed by
```make clean && make -j8 && make install -j8```


I do have a folder ``<siconos_BINARY_DIR>/docs/build/html``, but it is empty

**Comment by fperignon** [comment]
<CMAKE_BINARY_DIR> is a default variable  that represents the place
where you build

Indeed it’s the place where you run cmake. 

And you folder docs/build/html will be filled in when you run "make doc"

**Comment by vacary** [comment]
For EulerMoreauOSI. the default behavior must be to compute residues R and Y.

**Comment by vacary** [comment]
see MR https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos/merge_requests/1
