### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#283]
make doc target failed 

-> documentation is not built
-> web site is not built neither published

Bug in breathe/sphinx renderer : 
"AttributeError: module 'sphinx.domains.cpp' has no attribute 'CPPUnionObjectt"

I suspect something related to mismatch between sphinx, python ... versions.

Ongoing investigation ...

**Comment by pissard** [comment]
still problem on building doc (ubuntut 18.04)
1)
problem on docs/CMakeLists.txt : include(doc_devel) 
 doc_devel not found during the cmake process ...

the web site still not available.

2) 
If I comment  include(doc_devel) 
make doc failed

Running Sphinx v1.7.9
docs/CMakeFiles/html.dir/build.make:57: recipe for target 'docs/CMakeFiles/html' failed
make[3]: *** [docs/CMakeFiles/html] Error 2
CMakeFiles/Makefile2:367: recipe for target 'docs/CMakeFiles/html.dir/all' failed
make[2]: *** [docs/CMakeFiles/html.dir/all] Error 2
CMakeFiles/Makefile2:438: recipe for target 'docs/CMakeFiles/doc.dir/rule' failed
make[1]: *** [docs/CMakeFiles/doc.dir/rule] Error 2
Makefile:294: recipe for target 'doc' failed
make: *** [doc] Error 2
