### ISSUE TITLE
install siconos - list packages ubuntu

### ISSUE THREAD

**Issue by franckbourrier** [siconos/siconos#287]
is there  a list of the packages required for installing siconos on ubuntu 18.04 or an installation script for that ?

Best,

**Comment by fperignon** [comment]
Hello,

   - apt update -qq 
   - apt install -y -qq cmake git-core wget make
     libboost-dev libgmp-dev swig gcc gfortran g++ liblapack-dev
     libatlas-base-dev lp-solve liblpsolve55-dev python3-dev
     libpython3-dev bash swig doxygen python3-pip htop
     libcppunit-dev python3-scipy python3-pytest valgrind python3-h5py 

usually you can find this kind of information in 
ci-scripts , eg:
https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-tutorials/blob/master/.gitlab-ci.yml <https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-tutorials/blob/master/.gitlab-ci.yml>
https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-tutorials/blob/master/ci/dockerfiles/build-ubuntu-18.04/Dockerfile <https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-tutorials/blob/master/ci/dockerfiles/build-ubuntu-18.04/Dockerfile>

**Comment by alexmyczko** [comment]
I'm working on a package: http://phd-sid.ethz.ch/debian/siconos/

**Comment by vacary** [comment]
@alexmyczko 
Nice to hearing that you are interested in.
We are in the process to submit an official package in debian.
There is a project in debian salsa system to build a package. Perhaps, we can share our effort

**Comment by radarsat1** [comment]
Here is the salsa package: https://salsa.debian.org/science-team/siconos/

And here is the list of packages it requires: https://salsa.debian.org/science-team/siconos/blob/master/debian/control

Note that this is for current Debian unstable.  It will evolve.  We are still trying to find a sponsor to upload the package.
