### ISSUE TITLE
Build failed with FCLIB

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#291]
On Linux ubuntu 18.04 (massiveattack), build fails with FCLIB

```
[ 90%] Swig source
/bin/sh: 1: Syntax error: "(" unexpected
numerics/swig/CMakeFiles/_fclib.dir/build.make:122: recipe for target 'wrap/siconos/fclibPYTHON_wrap.c' failed
make[2]: *** [wrap/siconos/fclibPYTHON_wrap.c] Error 2
CMakeFiles/Makefile2:524: recipe for target 'numerics/swig/CMakeFiles/_fclib.dir/all' failed
make[1]: *** [numerics/swig/CMakeFiles/_fclib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by vacary** [comment]
This is due to the new curious include dirs:
```
NUMPY_INCLUDE_DIR:STRING=Traceback (most recent call last):
```

**Comment by fperignon** [comment]
can you be more specific on the configuration process you use ?

I tried a conf with -DFCLIB=ON, building only numerics and WITH_PYTHON_WRAPPER=ON
and it works well for me, both on my laptop (macOS) and on massiveattack, using fclib installed in /usr/local.


in CMakeCache.txt, I have 
NUMPY_INCLUDE_DIR=/usr/local/lib/python3.7/site-packages/numpy/core/include
or, on Massiveattack
NUMPY_INCLUDE_DIR=/usr/local/lib/python3.6/dist-packages/numpy/core/include

**Comment by vacary** [comment]
If the script for guessing the version of numpy or scipy fails, it returns the error message that it uses has an include dir for numpy and scipy. Then it cannot compile.
We have to prevent for using wrong  include dirs when python raise an error or an exception.
