### ISSUE TITLE
siconos documentation on readthedocs

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#293]
I stubbled upon that: https://siconos.readthedocs.io/en/latest/
Looks fairly old (a8972b47 is more than a year old) an not updated. Does anyone remember how that was pushed? (It could even be my doing ...)

**Comment by vacary** [comment]
Not me. Perhaps we can remove it

**Comment by vacary** [comment]
should we remove it ?

**Comment by xhub** [comment]
Yes. It can always be added back, and it removes some confusion.
