### ISSUE TITLE
Other kind of matrices for MassMatrix in BouncingBallTS

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#296]
If one tries to build a banded matrix in the BouncingBall:

```c++
SP::SiconosMatrix Mass(new SimpleMatrix(nDof, nDof, Siconos::BANDED));
```
(which would be something as a tremendous optimization...),
this fails.

The problem is in ```SimpleMatrixSolvers.cpp:50```
 ```c++
void SimpleMatrix::PLUFactorizationInPlace()
```

where the case Siconos::BANDED is not checked, only the dense and sparse cases are checked.

Moreover, in the sparse case only the symmetric case is treated
```
 int info = cholesky_decompose(*sparse());
    // \warning: VA 24/11/2010: work only for symmetric matrices. Should be replaced by efficient implementatation (e.g. mumps )
``

**Comment by vacary** [comment]
More generally, we should improve the simpleMatrix to provide more linear solvers.

**Comment by vacary** [comment]
The #319 PR should help to take into account
