### ISSUE TITLE
[CI] add a config for OCE

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#30]
no config currently builds wiith OCE. There is some data in CI/config/siconos.yml that indicate that it was worked on. Is there any major blocker.

If it is tested on CI, then errors could show up on the CDash

**Comment by vacary** [comment]
I would be glad to help on this issue, but where I can find some info how to add a  config in CI.

Where can i find the basic things to know how to add a config ?  I just need to read the .yml file ?

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2016-03-17 06:29:02 -0700]:

> I would be glad to help on this issue, but where I can find some info how to add a  config in CI.
> 
> Where can i find the basic things to know how to add a config ?  I just need to read the .yml file ?

You need to do the following (every file path is relative to CI):
- edit config/siconos.yml to configure the packages to install. There is already a oce pkg configuration; you may need to complete it.
- create a new cmake config file like config/with_oce.cmake to enable the build at the cmake level.
- create a new task or add this to current task in tasks.py. You need to add something to the ci_config and the add_pkgs keywords. If you choose to create a new task, you need to add it to a vm in known_tasks. It would be best to add it to vm0 because of space issue on vm2 and vm3.

**Comment by vacary** [comment]
Ok, ideally one the interesting config is for WITH_MECHANISMS=ON

The main challenge is that pythonocc is not distributed as package for the recent Linux distribution, so we have to compile it and to install. On my computer it takes 15 minutes of compilation. It is reasonable or not

**Comment by xhub** [comment]
> The main challenge is that pythonocc is not distributed as package for the recent Linux distribution, so we have to compile it and to install. On my computer it takes 15 minutes of compilation. It is reasonable or not

Yes, we don't care about the time to compile on CI.
However, you have to install in /usr, not /usr/local, since the later should be delete after each run.

See for example, see in siconos.yml how we install fclib.

However, note that you could create a tar.gz of the binaries, store it
on the siconos website and get it during the preparation phase.
See for instance cppunit_clang in siconos.yml.

In any case, if the docker container already exists, it should not
compile anything, just use the existing container. But if the software
is installed in /usr/local, it will fail since this directory should be
delete after each run.

**Comment by xhub** [comment]
I think we do have that now.
