### ISSUE TITLE
Need help on siconos compilation: No rule to make target [...]siconos/io/swig/io_base_swig_compilation

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#301]
Hi,
I am under Ubuntu 18.04 (up-to-date), and I would need some help to compile siconos. I have an error just before the end of the make command.
My cmake command line is: `cmake -DWITH_PYTHON_WRAPPER=ON -DWITH_BULLET=ON  ../siconos/`

Here are the [cmake](https://github.com/siconos/siconos/files/3610251/cmake.log) and the [make VERBOSE=1](https://github.com/siconos/siconos/files/3610337/make.log) outputs.

And finally the error message:

> No rule to make target '/home/francois/Documents/Micro-entreprise/projets/chute_blocs/siconos/public/siconos/io/swig/io_base_swig_compilation', needed by 'man/siconos_vview.1'.  Stop.

Many thanks for you help,
François

**Comment by vacary** [comment]
Hi François,

Are you working with the master branch  or an old release ?

Vincent

**Comment by batzkass** [comment]
Hi Vincent,
I tried master branch here and in gricad gitlab repo.

**Comment by batzkass** [comment]
I have the same system (its ubuntu mate 18.04) installed in a virtual machine and compilation runs well. So the origin of the issue is likely a package conflict.

**Comment by xhub** [comment]
For quick fix, try to add -DHELP2MAN=0 to the cmake arguments

Some dependencies in  io/swig/CMakeLists.txt looks to be a bit old. Someone would need to look at line 67 and maybe update the cmake target name?

**Comment by batzkass** [comment]
Brilliant, it worked, thanks ! Even though the mystery remains unsolved...

**Comment by xhub** [comment]
Well, now I can explain: on one machine you have the `help2man` program installed, and not on the VM. If this program is detected, then it tried to build the man pages from the help message of each program. To ensure the correct dependency, a (now bogus) dependency on the man targets is added. My guess is that the name of the dependency was changed, but not updated here.

This also highlights that most likely none of the CI machines have `help2man` installed.

**Comment by batzkass** [comment]
Well, many thanks, nothing to add.

**Comment by xhub** [comment]
I would suggest leaving the issue open, since this is really a bug (I used to be able to reopen issues, but apparently lost those powers)

**Comment by vacary** [comment]
@xhub you are back as "Owner"

**Comment by xhub** [comment]
Related to that issue:

[100%] Generating man/siconos_export_raw_data.1 using help2man
help2man: can't get `--help' info from /scratch/huber/builds/siconos_gentoo/wrap/siconos/io/siconos_export_raw_data

**Comment by vacary** [comment]
try to change the permission in 5154e0d06
