### ISSUE TITLE
Compilation of the BouncingBall is broken on the master

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#302]
I am on 7c7c04bd0
The examples are cc175a9
The system is an ubuntu 18.04
With
```
   cmake ~/src/siconos -DCMAKE_INSTALL_PREFIX=/usr/local
   make && sudo make install
```

The ``BouncingBallTS.cpp`` cannot be compiled, suitesparse is not found:
```
/usr/local/include/siconos/numerics/CSparseMatrix.h:49:10: fatal error: cs.h: No such file or directory

 #include "cs.h"
```
Note that if you use the system suite sparse, the result is the same.

If I add ```-I/usr/include/suitesparse``` it is ok.

If I use fclib, it fails at the cmake level:
```
siconos BouncingBallTS.cpp 

|=============================================================================|
|          Siconos-Kernel version 4.2.0        Copyright 2018 INRIA       |
|                                                                             |
|                    Free software under Apache License.                      |
|=============================================================================|
-- Boost version: 1.65.1
CMake Error at siconos-config.cmake:90 (set_and_check):
  set_and_check Macro invoked with incorrect arguments for macro named:
  set_and_check
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)


-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   timer
-- Configuring incomplete, errors occurred!
```

**Comment by bremond** [comment]
Apparently, the include of cs.h directly in [CSparsematrix.h](https://github.com/siconos/siconos/blob/7c7c04bd06985e3aa98a3ae5f7ed3f69b1982022/numerics/src/tools/CSparseMatrix.h) has been inserted in 0646e97de. The usage of suitesparse was meant to be opaque, if one looks at the underlying comments. This is this include at line 49 that breaks the compilation.

**Comment by xhub** [comment]
Let's just revert the removal of the CSparseMatrix_internal.h then, and put a comment about the purpose of this file.

**Comment by fperignon** [comment]
Hi,

this commit was supposed to fix some warnings due to CXSparse,
related to missing or confusing definitions in CSparseMatrix.h (where for example cs.h was missing, it seems)
So I’m not sure that a revert will fix the pb properly ? 
I’ll have a look at this and try to fix properly this wrong  behaviour at runtime.
The idea being, correct me if I’m wrong, that we don’t want/need  CXsparse in Siconos interface at runtime, is it?

**Comment by bremond** [comment]
Yes CXSparse must remain private from siconos in the header files, that is why there were a CSparseMatrix_internal.h, included only from siconos sources that has been deleted in 0646e97. Why has it been deleted ?

**Comment by fperignon** [comment]
As I said in my previous comment, there were many warnings due to multiple definitions of CS_INT (from cs.h and CXSparse.h) among other things.

**Comment by xhub** [comment]
I just reverted the commit except for issues with swig 4, there is just missing include for the numerics python wrapper. Under which setup did the warning appeared? Do we still have a CI?

**Comment by fperignon** [comment]
> Le 18 sept. 2019 à 16:05, Olivier Huber <notifications@github.com> a écrit :
> 
> I just reverted the commit except for issues with swig 4, there is just missing include for the numerics python wrapper. Under which setup did the warning appeared?
> 
with clang I think, maybe some others

> Do we still have a CI?
> 
yes, this one for example :

https://my.cdash.org/viewBuildError.php?type=1&buildid=1693879

**Comment by vacary** [comment]
Is it better now ?

**Comment by fperignon** [comment]
it is

**Comment by vacary** [comment]
[acary@ohana-2]$ siconos BouncingBallTS.cpp
Traceback (most recent call last):
  File "/Users/acary/.local/bin/siconos", line 813, in <module>
    main()
  File "/Users/acary/.local/bin/siconos", line 80, in main
    create_build_dir(args)
  File "/Users/acary/.local/bin/siconos", line 289, in create_build_dir
    args.build_dir = Path('.siconos').resolve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 1109, in resolve
    s = self._flavour.resolve(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 330, in resolve
    return _resolve(base, str(path)) or sep
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 315, in _resolve
    target = accessor.readlink(newpath)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 422, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/acary/siconos-tutorials/examples/mechanics/BouncingBall/.siconos'
----- ~/siconos-tutorials/examples/mechanics/BouncingBall -----

**Comment by vacary** [comment]
with ca1d1f7099319a970a28a517892c588e5cc37a03, it works like a charm. Thank you
