### ISSUE TITLE
Error when erasing RigidBody2dDS from _interman

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#304]
Hi,

I use bullet+RigidBody2dDS bodies, and I would like to be able to remove them. However the RemoveBody method seems not to be designed for 2d objects.

This is the error I get :
`File "/usr/local/lib/python3.6/dist-packages/siconos/mechanics/collision/bullet.py", line 8291, in removeBody
    return _bullet.SiconosBulletCollisionManager_removeBody(self, body)
TypeError: in method 'SiconosBulletCollisionManager_removeBody', argument 2 of type 'SP::RigidBodyDS const &'`

Would it be possible for you to implement it ?
Many thanks.

**Comment by vacary** [comment]
ok, I ll have a look

**Comment by vacary** [comment]
could you try with 3b8b398

**Comment by batzkass** [comment]
Same result. Is the binding with swig automatic ? Here is the python signature I get :                                                                      
```
In [2]: s.interman.removeBody?
Signature: s.interman.removeBody(body:'SP::RigidBodyDS const &') -> 'void'
Docstring: <no docstring>
File:      /usr/local/lib/python3.6/dist-packages/siconos/mechanics/collision/bullet.py
Type:      method
```

**Comment by vacary** [comment]
Could you provide me a simple example ? It seems to work on my computer.

**Comment by batzkass** [comment]
I have nothing that you could simply run. But I will check tomorrow, maybe you have a minimal working example that I could check ?

**Comment by vacary** [comment]
ok, I made an example. It works if you recompile from scratch siconos

The method is automatically wrapped by swig but it needs to recompile siconos from scratch. I do not why the dependence is not taken into account.
@fperignon do yo have an idea ?

**Comment by batzkass** [comment]
Thank you very much, so I have 10 minutes of compile-coffee-break. I'll keep you informed.

**Comment by batzkass** [comment]
It works perfectly, thanks.

**Comment by vacary** [comment]
Cool

**Comment by fperignon** [comment]
> Le 27 sept. 2019 à 10:00, Vincent Acary <notifications@github.com> a écrit :
> 
> ok, I made an example. It works if you recompile from scratch siconos
> 
> The method is automatically wrapped by swig but it needs to recompile siconos from scratch. I do not why the dependence is not taken into account.
> @fperignon <https://github.com/fperignon> do yo have an idea ?
> 

The problem is that the c++ wrapper file is not re-generated when mechanics sources are modified.
I’ll have a look at this
