### ISSUE TITLE
Mechanics: numerical instability if time_of_birth > 0

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#305]
Hi,

I discovered a weird numerical instability that triggers if objects `time_of_birth > 0`, i.e. when they are imported after `T=0`.

[Here is an example](https://github.com/siconos/siconos/files/3657548/convexhull2d_on_box.py.zip), which is a slightly modified version of `convexhull2D_on_box.py` found in siconos examples.

L48, I have set `time_of_birth=0.1`, and the result is a square that, after gravity deposition, keeps getting non-constant forces from the ground. As a result, i) its velocity never reach low values, and ii) the square slowly sink down into the ground.

If you set `time_of_birth=0` L48, the square drops then stabilizes normally on the ground surface, reaching very low velocities.

Any idea ?
Thanks.

**Comment by vacary** [comment]
No idea fro the moment but 2D API is very new so it is probably a bug. I'll have a look

**Comment by batzkass** [comment]
Well, I discovered this morning that this issue doesn't only affect 2D Mechanics but Mechanics in general as well. I attached a [modified version of the convexhull.py script](https://github.com/siconos/siconos/files/3661794/convexhull.py.zip) : 

- increased timestep
- increased number of steps
- `time_of_birth=0.1` for the dynamic hull

You will see the same strange behavior, that disappears if `time_of_birth=0`.

**Comment by vacary** [comment]
ok, It seems that is the result of side effect of the merge with 2D mechanics. I continue to investigate

**Comment by vacary** [comment]
The bug seems to be deeply hidden  int he construction of the Delassus matrix. I continue to investigate ...

**Comment by vacary** [comment]
Hi,
This should be fixed in 0bb99f0766ef29d2915d5662cad09d7eaa26bb1f
It took a very long time to understand the problem, hope it will help you

**Comment by batzkass** [comment]
Many thanks, it looks like it works. Let me just double-check this tomorrow before closing the thread.

**Comment by batzkass** [comment]
After a bunch of test, it seems to work perfectly.
Many thanks.
