### ISSUE TITLE
Disable Mechanics 2D data display

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#306]
Hi,
Is there a way to disable the display at each contact in mechanics 2d ? I mean, avoid the call to:
https://github.com/siconos/siconos/blob/01fe2e7de2b8c3803a2d76064d12f9d9ff78c897/kernel/src/modelingTools/NewtonImpactFrictionNSL.cpp#L46

Thanks.

**Comment by vacary** [comment]
This should be fixed in aa38ca0
This was a debug verbose that I have forgotten
