### ISSUE TITLE
[io][mechanics] Document cubes.py and mechanics_io.py

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#31]
The goal is to render more visible the very good of @bremond for input/output scenes and results for mechanical systems

**Comment by vacary** [comment]
start with [ec17cd844](https://github.com/siconos/siconos/commit/ec17cd844250754eeb72c89343eeb46250f47c1e)

**Comment by radarsat1** [comment]
Perhaps we move this to 4.2, and add a few more documentation items.

* NewtonEulerDS is missing from http://siconos.gforge.inria.fr/users_guide/dynamical_systems.html
* Mechanics, control, IO modules here are empty: http://siconos.gforge.inria.fr/reference/siconos_python_reference.html
* We need to add io/mechanics_io.rst somewhere

**Comment by vacary** [comment]
replaced by #224
