### ISSUE TITLE
Change signature and improve Linear solvers in NumericsMatrix.c

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#312]
With @bremond, we propose to rename the following functions

NM_gesv_expert --> NM_LU

NM_posv_expert --> NM_ LLT (or Cholesky)

and to add 

NM_LDLT

see also comment in #309

**Comment by xhub** [comment]
Sounds good. Do we want to keep some notion of "solve" in the name?
What about `NM_gesv` ?

**Comment by vacary** [comment]
Start to do the job. If you're interested in :

https://github.com/vacary/siconos/tree/LUandCo
