### ISSUE TITLE
Issue in fclib.i after swig-4 modifications

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#313]
After commit d4fdc79df3a80e8ac we have a problem  in the swig wrag of fclib,  see

https://my.cdash.org/viewBuildError.php?buildid=1726959

The macro `$descriptor(fclib_solution *)` is not correctly converted to SWIGTYPE_p_fclib_solution

**Comment by xhub** [comment]
I think it is "fixed". However, I believe the typemap is never applied so this looks like dead code anyway. Maybe a cleanup could be done (see also https://github.com/FrictionalContactLibrary/fclib/issues/6 )

**Comment by vacary** [comment]
Thank you. perfect.

Clearly, we have to move fclib.i in Fclib.
