### ISSUE TITLE
Install on Centos

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#317]
This is a summary of some discussion regarding Siconos Install on Centos.

Quote :

Bonjour,

J'attendais d'avoir essayé d'installer siconos pour avoir des
questions à poser, après quelques essais infructueux voici donc mes
première questions :

- Dans la documentation, il est spécifié dans les pré-requis d'avoir
une version de cmake supérieure à  2.8.7, 3.x, or lorsque j'essaie
de lancer la version 2.8.11 cela ne fonctionne pas. Il semblerait
que dans le fichier CMakeLists.txt, il semblerait que la version
minimale soit la 3.7. S'agit-il un problème de documentation non à
jour ?

- Est-il possible de compiler sans cblas ? Le package n'est pas
installé sur la plateforme de calcul du laboratoire car nous
utilisons la version FORTRAN, et l'installation de cblas demande du
temps.

En vous remerciant par avance,

Cordialement,

Benoît Lé

**Comment by fperignon** [comment]
Bonjour,

je confirme que la doc n’est pas à jour et que pour la branche master, la version minimale est cmake 3.7.

En ce qui concerne blas, oui il faut cblas.

La meilleure option, je pense, est d’installer OpenBlas.
Sur quel système travaillez vous ?

**Comment by fperignon** [comment]
Bonjour,

Merci pour votre réponse. Le serveur de calcul tourne sur CentOS7. OpenBlas est installé, mais il manque les headers.

Je pense avoir réussi à régler le problème en mettant l'option "INSTALL_EXTERNAL_HEADERS" à "ON" (le header était dans siconos/src/siconos/externals/blas_lapack/cblas_header). (Je peux rajouter ce commentaire à l'issue sur github si vous pensez que ça peut être utile).

J'ai maintenant un problème avec SuiteSparse : faut-il installer l'intégralité du code ? J'ai tenté de le compiler et j'ai pas mal de messages d'erreurs. J'ai tenté de ne compiler que CX_Sparse (qui semble être requis par Siconos) et de faire un set(SuiteSparse_CXSparse_LIBRARIES), malheureusement j'ai toujours le message d'erreur (copié en fin de mail).

Ci-joint également le fichier d'options que j'utilise pour lancer cmake.

En vous remerciant par avance,

Benoît Lé

...

--------------------------------------------------
-- Set up for siconos_numerics library ...

-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Could NOT find SuiteSparse_CXSparse (missing: SuiteSparse_CXSparse_LIBRARIES) 
-- Could NOT find PathFerris (missing: PathFerris_LIBRARIES) 
-- Could NOT find PathVI (missing: PathVI_LIBRARIES) 
-- The following REQUIRED packages have been found:

* Python3
* BLAS
* BLASDEV
* LAPACKDEV
* Boost (required version >= 1.61)
* Threads

-- The following OPTIONAL packages have not been found:

* PathFerris
* PathVI

-- The following REQUIRED packages have not been found:

* SuiteSparse

-- Generate siconos script ...
-- 
============================================ Summary ============================================
-- siconos version 4.2.0 is now ready for compilation and installation.
-- To proceed run 'make' and 'make install' and optionaly 'make test'.
-- C++ Compiler : /bin/c++ 4.8.2
-- C++ flags : 
-- C Compiler : /bin/cc 4.8.2
-- C flags : 
-- Fortran Compiler : /bin/gfortran 4.8.2
-- Fortran flags : 
-- Compilation mode is : Release
-- Code Sources are in : /glouton/struct/ble/eXlibrisNext/myExternalLib/siconos/src/siconos
-- Blas from mkl.
   Blas libraries : /usr/local/intel/mkl/11.0.2.146/composer_xe_2013.2.146/mkl/lib/intel64/libmkl_gf_lp64.so;/usr/local/intel/mkl/11.0.2.146/composer_xe_2013.2.146/mkl/lib/intel64/libmkl_gnu_thread.so;/usr/local/intel/mkl/11.0.2.146/composer_xe_2013.2.146/mkl/lib/intel64/libmkl_core.so;/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgomp.so;pthread;-lm;-ldl.
   Blas headers : mkl_cblas.h in /usr/local/intel/mkl/11.0.2.146/composer_xe_2013.2.146/mkl/include.
-- Lapack config:
   Lapack libraries : /usr/local/intel/mkl/11.0.2.146/composer_xe_2013.2.146/mkl/lib/intel64/libmkl_scalapack_lp64.so.
   Lapack headers : mkl_lapacke.h in /usr/local/intel/mkl/11.0.2.146/composer_xe_2013.2.146/mkl/include/.
-- Use system-provided SuiteSparse library, with:
   - CXSparse headers path: /glouton/struct/ble/eXlibrisNext/myExternalLib/SuiteSparse/suitesparse/include
   - CXSparse library : SuiteSparse_CXSparse_LIBRARY-NOTFOUND
-- Python interpreter is /usr/local/anaconda3/bin/python3.7
-- The project will be installed in /usr/local
-- To get more information about dependencies, config or else, 
-- check CMakeCache.txt file or re-run cmake with -DPRINT_ENV=ON.
-- =================================================================================================

-- Configuring done
CMake Error at cmake/ComponentSetup.cmake:34 (add_library):
 Target "numerics" links to target "SuiteSparse::CXSparse" but the target
 was not found.  Perhaps a find_package() call is missing for an IMPORTED
 target, or an ALIAS target is missing?
Call Stack (most recent call first):
 numerics/CMakeLists.txt:94 (create_siconos_component)


CMake Error at cmake/ComponentSetup.cmake:34 (add_library):
 Target "numerics" links to target "SuiteSparse::CXSparse" but the target
 was not found.  Perhaps a find_package() call is missing for an IMPORTED
 target, or an ALIAS target is missing?
Call Stack (most recent call first):
 numerics/CMakeLists.txt:94 (create_siconos_component)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by fperignon** [comment]
Bonjour,

bon, je ne connais pas centos mais  j’ai effectué quelques tests sur une image docker.
Voici le fichier de conf docker que j’ai utilisé pour faire marcher siconos :
(il est disponible dans le repo siconos dans ci_gitlab/dockerfiles/centos-7)

RUN yum update -y && yum install -y -qq \
     https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum update -y && yum install -y -qq \   
        wget \
        git-all \
        boost169-devel \
        boost169-serialization \
        boost169-filesystem \
        boost169-timer \
        boost169-chrono \
        gmp-devel \
        gcc-c++ \
        gcc-gfortran \
        swig3 \
        lpsolve-devel \
        cppunit-devel \
        suitesparse-devel \
        python3-devel \
        python3-pip \
        openblas-devel
RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.sh
RUN printf 'y\nn\n' | sh cmake-3.16.0-Linux-x86_64.sh --prefix=/usr/local
RUN pip3 install numpy scipy h5py packaging pytest lxml

Pour tester, sur une machine où docker est disponible :
docker build -t sico-centos ci_gitlab/centos

Sur votre serveur, il faudrait donc installer les packages listés dans le Dockerfile.

Pour la conf de siconos, je lance :

cmake -DUSER_OPTIONS_FILE=../sicoloc/ci_gitlab/siconos_confs/siconos_default.cmake -DBOOST_INCLUDEDIR=/usr/include/boost169 -DBOOST_LIBRARYDIR=/usr/lib64/boost169/  ../sicoloc/ -DCMAKE_CXX_STANDARD=11 -DCLAPACK_LIBRARY=/usr/lib64/libopenblas.so


Les points importants sont :

- les versions de libs par défaut sur centos  sont assez anciennes (gcc 4, boost 1.50 …)
- il faut préciser BOOST_INCLUDEDIR et BOOST_LIBRARYDIR car centos installe la version 1.69 dans boost169 et non pas dans /usr standard.
- il faut préciser CMAKE_CXX_STANDARD=11 car le compilo est un peu vieux et ne tourne pas en cxx 11 par défaut
- il faut choisir libopenblas comme librairie lapack, celle fournie par défaut ne fonctionne pas avec siconos (voir https://lists.fedorahosted.org/archives/list/epel-devel@lists.fedoraproject.org/thread/BBNSDKRFZV7Y7HZ5H2YIEXYTXU7D4N2S/
pour quelques infos sur la conf blas/Lapack sur centos)

Dites nous si ça fonctionne avec cette conf ?
Bonne journée

Franck Pérignon

**Comment by fperignon** [comment]
sur ma version centos, il faut aussi ajouter à la ligne cmake :

-DSICONOS_STD_ISNAN_ALREADY_HERE_AND_I_DO_NOT_KNOW_WHY=ON

je ne sais pas d’où vient cette option mais elle semble nécessaire

**Comment by fperignon** [comment]
J'ai ensuite essayé de revenir sur le serveur. En exécutant exactement les mêmes instructions, cmake trouve par défaut /usr/lib64/libblas.so pour CBLAS.


Or pour certaines raisons (qui dépassent un peu mes compétences malheureusement), openblas est installée sous

/opt/ExternalLib/gcc-4.8.2/lib64/libopenblas_vth_noaffinity.so

(l'extension provient d'une installation un peu particulière). J'ai ensuite essayé de dire à cmake  où trouver cette version d'OpenBlas en faisait un

set(BLA_VENDOR OpenBlas)

suivi d'un set(BLAS_LIBRARY_DIR ...)

mais j'obtiens le message d'erreur :

CMake Error at /glouton/struct/ble/myCMake/myCMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)

J'ai également essayé d'installer moi-même OpenBlas (pour éviter les extensions "folkloriques") ailleurs que dans /usr/lib64/ (malheureusement sur le serveur cela est un peu compliqué) tout en spécifiant à cmake où trouver ma nouvelle installation de cmake :

set(BLA_VENDOR OpenBlas)
#set(WITH_BLAS openblas)
#set(BLAS_LIBRARIES /glouton/struct/ble/eXlibrisNext/myExternalLib/OpenBLAS/localInstall/lib/libopenblas.so)
#set(BLAS_DIR /glouton/struct/ble/eXlibrisNext/myExternalLib/OpenBLAS/lib)
set(BLAS_ROOT /glouton/struct/ble/eXlibrisNext/myExternalLib/OpenBLAS/)
set(BLAS_LIBRARY_DIR /glouton/struct/ble/eXlibrisNext/myExternalLib/OpenBLAS/localInstall/lib/)
set(BLAS_INCLUDE_DIR /glouton/struct/ble/eXlibrisNext/myExternalLib/OpenBLAS/localInstall/include/)

mais j'otiens le même message d'erreur ( Could NOT find BLAS (missing: BLAS_LIBRARIES) ) .

Pensez-vous qu'il soit possible d'utiliser une version d'openblas installée ailleurs que dans /usr/lib64/  ?

En vous remerciant par avance,

Benoît Lé

**Comment by fperignon** [comment]
Suite des réponses à @ble912 :

la meilleure option est d’utiliser un fichier d’option (voir les exemples dans le repo siconos/ci_gitlab/siconos_confs)
et de mettre à ON la ligne
option(WITH_TESTING "Enable 'make test' target" ON)

Dans ‘make -j N test’ il faut:
- que la compilation (make) soit allée jusqu’au bout
- remplacer N par le nombre de coeurs à utiliser pour compiler ou lancer les tests

Pour la version avec un openblas dans un répertoire non standard, il faudrait essayer 
de spécifier BLAS_ROOT en ligne de commande :

cmake -DBLAS_ROOT=/opt/ExternalLib/gcc-4.8.2/  ... -DLAPACK_ROOT=...

Si ça ne marche pas, merci de mettre en copie le fichier CMakeCache.txt généré dans le 
répertoire de build

**Comment by ble0912** [comment]
Cela semble fonctionner avec la version de OpenBlas que j'ai installé sur ma machine, pas avec celle du serveur, je pense que c'est un problème à voir de notre côté.

J'ai également réussi à faire tourner les cas tests de numerics, deux semblent avoir échoué :

52 - fc3d_TEST_NSN_COLLECTION_1 (Failed)
76 - ConvexQP_FC3D_test_collection (Failed)

**Comment by fperignon** [comment]
ok,

pour les tests, ça ne vient pas de votre installation, nous avons aussi l'erreur. C'est en cours
de correction
