### ISSUE TITLE
Travis does not report errors

### ISSUE THREAD

**Issue by bremond** [siconos/siconos#326]
https://travis-ci.org/github/siconos/siconos/jobs/663108683

line 477:
 77/128 Test #117: python_test_bouncing_ball ...................***Failed  Error regular expression found in output. Regex=[FAILURE]  0.88 sec

98% tests passed, 3 tests failed out of 128

The following tests FAILED:

	117 - python_test_bouncing_ball (Failed)

	118 - python_test_diode_bridge (SEGFAULT)

	128 - MultiBodyTest (Child aborted)

**Comment by vacary** [comment]
Any update ?

It seems also that the status of Travis build is no longer to GitHub. Is it related to 
https://travis-ci.community/t/travis-ci-build-no-longer-showing-as-check-on-github-pull-request-page/6955/5

**Comment by fperignon** [comment]
I think it's fixed in 6b8d3fa801d7626d9c8bdf064eec4b54e0ea2673
To be checked ...
