### ISSUE TITLE
[cmake] add options to enforce license

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#33]
We have some code that cannot be distributed as GPL or Apache v2, like MA28 in HEM5. To facilitate the distribution, I propose to add 2 cmake options
- ENSURE_GPL to guarantee that the resulting binary is GPL-compatible
- ENSURE_APACHE to guarantee that the resulting binary is compatible with this license. This would for instance ensure that WITH_UMFPACK is disable.

Code that should be disable in both cases:
- HEM5

Apache:
- UMFPACK
- FCLIB (if the license does not change to LGPL)

**Comment by vacary** [comment]
I do not understand how a compilation option will help the distribution of siconos. What do you mean exactly ? We can have  GPL or Apache non compatible source code in our distribution but, if we are able to compile and link without it, we preserve our license  at least for this compiled version ?
Are you sure about this point ?

**Comment by radarsat1** [comment]
I think he is consider more binary distributions, such as .deb, providing Debian with flags to enable to ensure the software doesn't have incompatible requirements.  That said, I am not aware off the top of my head of any software that changes it license depending on the compilation flags...

On the other hand, if the flags had an effect on what gets included in a tar-file source code release, that might be interesting.

**Comment by xhub** [comment]
* Stephen Sinclair <notifications@github.com> [2016-03-17 18:11:25 -0700]:

> I think he is consider more binary distributions, such as .deb, providing Debian with flags to enable to ensure the software doesn't have incompatible requirements.  That said, I am not aware off the top of my head of any software that changes it license depending on the compilation flags...

@radarsat1 is right, I was thinking about the distribution of siconos via binary packages. As for the change of license, I agree it's weird, but my understanding is that the compatibility between Apache v2 and GPLv3 means that when you link to a GPLv3 library from an Apache v2 code, the resulting binary is GPLv3.

> On the other hand, if the flags had an effect on what gets included in a tar-file source code release, that might be interesting.

I think that we still want people to be able to download the sources from github. It could be useful to remove some files in the debian source package, but it's not a high priority for me.


I think those 2 flags would be useful for us to deal with the packaging. Also, it should remove some burden for the user who should not have to look at each linked library to figure out under which license is the resulting binary. And it should force us to keep a little bit track of those (cumbersome) details.

**Comment by xhub** [comment]
I think this is overkill, we should just be careful and be careful when we create binaries
