### ISSUE TITLE
Example failure in debug mode

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#334]
The example mechanics/FEM/impactingBar.py fails when siconos is compiled
with CMAKE_BUILD_TYPE=Debug :

python3.6: /home/perignon/build/sico-light/wrap/siconos/kernelPYTHON_wrap.cxx:2382: int SWIG_Python_ConvertPtrAndOwn(PyObject*, void**, swig_type_info*, int, int*): Assertion `own' failed.

source of the problem seems to be in the DS constructor :

LagrangianLinearTIDS(...,M) 

if M is built using numpy it works but if M is built using SimpleMatrix (dense or sparse) it fails.

Notice that the example works in release mode.

**Comment by xhub** [comment]
This looks very close to #314

**Comment by fperignon** [comment]
right, it’s exactly the same. 
What was the fix ?

**Comment by vacary** [comment]
it seems that is was a change form swig3 to swig4
