### ISSUE TITLE
header include pattern needs updating all throughout Siconos

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#335]
It's really great that the headers have been moved into component categories, this makes things a lot cleaner.  However, the internals of Siconos have not been updated to reflect it.  I am just updating the package tests and I have a simple test program that starts with:

    #include "SiconosKernel.hpp"

And is compiled with,

    g++ -I/usr/include/siconos -o KernelDevTest KernelDevTest.cpp -lsiconos_kernel

which resulted in,

    KernelDevTest.cpp:1:10: fatal error: SiconosKernel.hpp: No such file or directory

No problem! Due to the reorganization my inclination was to change it to,

    #include "kernel/SiconosKernel.hpp"

but this resulted in,

```
In file included from /usr/include/siconos/kernel/BlockMatrix.hpp:27,
                 from /usr/include/siconos/kernel/Utils.hpp:23,
                 from /usr/include/siconos/kernel/SiconosKernel.hpp:25,
                 from KernelDevTest.cpp:1:
/usr/include/siconos/kernel/SiconosMatrix.hpp:29:10: fatal error: CSparseMatrix.h: No such file or directory
```

Okay, so the intention is to fix the command line, so I need to give numerics and kernel path?  I change it back to,

    #include "SiconosKernel.hpp"

and do,

```
$ g++ -I/usr/include/siconos/numerics -I/usr/include/siconos/kernel -o KernelDevTest KernelDevTest.cpp -lsiconos_kernel
In file included from /usr/include/siconos/kernel/SiconosMatrix.hpp:29,
                 from /usr/include/siconos/kernel/BlockMatrix.hpp:27,
                 from /usr/include/siconos/kernel/Utils.hpp:23,
                 from /usr/include/siconos/kernel/SiconosKernel.hpp:25,
                 from KernelDevTest.cpp:1:
/usr/include/siconos/numerics/CSparseMatrix.h:29:10: fatal error: SiconosConfig.h: No such file or directory
```

Ugh.  Okay I need to add `/usr/include/siconos`,

``
$ g++ -I/usr/include/siconos -I/usr/include/siconos/numerics -I/usr/include/siconos/kernel -o KernelDevTest KernelDevTest.cpp -lsiconos_kernel
In file included from /usr/include/siconos/kernel/SiconosMatrix.hpp:29,
                 from /usr/include/siconos/kernel/BlockMatrix.hpp:27,
                 from /usr/include/siconos/kernel/Utils.hpp:23,
                 from /usr/include/siconos/kernel/SiconosKernel.hpp:25,
                 from KernelDevTest.cpp:1:
/usr/include/siconos/numerics/CSparseMatrix.h:49:10: fatal error: cs.h: No such file or directory
```

Oh okay, Siconos needs to know where SuiteSparse is, that's reasonable:

    $ g++ -I/usr/include/suitesparse -I/usr/include/siconos -I/usr/include/siconos/numerics -I/usr/include/siconos/kernel -o KernelDevTest KernelDevTest.cpp -lsiconos_kernel

Success!

Hm, adding an include path for each library is reasonable, but it seems really ugly to have to add the include path for every component of Siconos.  This could be alleviated if Siconos internally did this:

```
#include <numerics/...>
#include <kernel/...>
```

or even,

```
#include <siconos/kernel/...>
```

Then one could just add `-I/usr/include/siconos` and done.

Also, it might be nice to be able to provide these paths as well as library linkage dependencies (eg. suitesparse) via pkg-config.  I also tried to see if CMake could alleviate the situation but it got long-winded so I'll add another issue.

**Comment by fperignon** [comment]
Hi, 

have you tried to use siconos script rather than calling g++ ? 

I think it handles all the problems you get, isn’t it ? 

And if you just want to compile, 

run 

siconos —no-exec KernelDevTest.cpp

**Comment by xhub** [comment]
Using the siconos script is outside of the scope here. The idea behind using siconos as a library is to be able to fully integrate it into another software. Think of how siconos is used in Gazebo (even if it may be a plugin in that case).

The siconos script is great to build siconos examples.

**Comment by xhub** [comment]
I believe that @fperignon did some work to have an easier integration. The proper directories should be set in siconosConfig.cmake. I think that `find_package(siconos)` should then be successful. 

Then it should contain the list of directories to include. For the projects not using cmake, it falls a bit short, then we would have a pkg-config file?

For cs.h, it is sad that it is included in that way. One of the design principle was to have the end-user code as much as possible independent from the siconos deps.

**Comment by fperignon** [comment]
ok,
anyway, using siconos script can give you an example on how siconos should be used as an external library

Try for example:

siconos BouncingBallTS-Scleronomous.cpp 
and have a look to the generated CMakeLists.txt in .siconos (where you run the example)


You’ll get something like the file below, which should be a proper inspiration and may answer you questions Steve ?
I think the especially important lines are those in red with the target_link to each component



project(BouncingBallTS-Scleronomous CXX C)
cmake_minimum_required(VERSION 3.7)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SKIP_BUILD_RPATH  FALSE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(siconos_DIR /home/perignon/install/siconos-debug/lib/cmake/siconos-4.2.0)
find_package(siconos 4.2.0 CONFIG REQUIRED)
set(CMAKE_MODULE_PATH ${siconos_ROOT}/lib/cmake/siconos-4.2.0)
if(ON)
set(Boost_NO_BOOST_CMAKE 1)
find_package(Boost 1.61 COMPONENTS timer timer)
endif()
add_executable(BouncingBallTS-Scleronomous /home/perignon/siconos-tutorials/examples/mechanics/BouncingBall/BouncingBallTS-Scleronomous.cpp)
target_include_directories(BouncingBallTS-Scleronomous PUBLIC /home/perignon/siconos-tutorials/examples/mechanics/BouncingBall)
target_link_libraries(BouncingBallTS-Scleronomous PRIVATE Siconos::externals)
target_link_libraries(BouncingBallTS-Scleronomous PRIVATE Siconos::numerics)
target_link_libraries(BouncingBallTS-Scleronomous PRIVATE Siconos::kernel)
target_link_libraries(BouncingBallTS-Scleronomous PRIVATE Siconos::control)
target_link_libraries(BouncingBallTS-Scleronomous PRIVATE Siconos::mechanics)
target_link_libraries(BouncingBallTS-Scleronomous PRIVATE Siconos::io)
if(Boost_TIMER_FOUND)
         target_link_libraries(BouncingBallTS-Scleronomous PUBLIC Boost::timer)
 endif()
install(TARGETS BouncingBallTS-Scleronomous DESTINATION /scratch/franck/tmp-nok)

# === Create plugin BouncingBallPlugin ===
add_library(BouncingBallPlugin MODULE /home/perignon/siconos-tutorials/examples/mechanics/BouncingBall/BouncingBallPlugin/BouncingBallPlugin.cpp)
target_sources(BouncingBallPlugin PRIVATE /home/perignon/siconos-tutorials/examples/mechanics/BouncingBall/BouncingBallPlugin/BouncingBallPlugin.cpp)
target_include_directories(BouncingBallPlugin PUBLIC /home/perignon/siconos-tutorials/examples/mechanics/BouncingBall)
target_include_directories(BouncingBallPlugin PUBLIC /home/perignon/siconos-tutorials/examples/mechanics/BouncingBall/BouncingBallPlugin)
target_link_libraries(BouncingBallPlugin PRIVATE Siconos::externals)
target_link_libraries(BouncingBallPlugin PRIVATE Siconos::numerics)
target_link_libraries(BouncingBallPlugin PRIVATE Siconos::kernel)
target_link_libraries(BouncingBallPlugin PRIVATE Siconos::control)
target_link_libraries(BouncingBallPlugin PRIVATE Siconos::mechanics)
target_link_libraries(BouncingBallPlugin PRIVATE Siconos::io)
set_target_properties(BouncingBallPlugin PROPERTIES PREFIX "")

**Comment by radarsat1** [comment]
Oh yes sorry I forgot to mention that, @xhub is right I am thinking about how to ensure that its use is more or less "works as expected" even outside the script.  The siconos script works well!

**Comment by radarsat1** [comment]
Oh but what I am suggesting in this particular issue (as opposed to the other one which is concentrated on CMake) is that things would be just a bit smoother if even inside siconos we used `#include` lines that include the component directory, eg., `kernel/SiconosMatrix.hpp`.  Mainly because that is how they are now referred to relative to where they are installed, which was not the case before.  I guess my point is that doing just,

```
#include "SiconosKernel.hpp"
```
and using,
```
-I /usr/include/siconos
```
should not fail.

But for that to be the case all Siconos headers would have to refer to each other relative to `/usr/include/siconos`, therefore include `kernel/` and `numerics/`, etc.  I also happen to think that would improve the code slightly, not having to guess which headers are in which components.

Anyways, just saying that it would be my preference, we can always agree to disagree ;)

**Comment by xhub** [comment]
I like that idea. For me it is not a deal breaking is the user has to do
```-I /usr/include/siconos/numerics -I /usr/include/siconos/kernel -I /usr/include/siconos/mechanics```
One can even short in it in
``` -I /usr/include/siconos/{numerics,kernel,mechanics} ```

What would be more important, is to not depend on the siconos dependencies by default.

For the `cs.h` issue, it looks like `cs.h` should be included in a private header. I am looking into that

**Comment by radarsat1** [comment]
Actually thinking further I realized my proposal is quite problematic because it depends only on where the headers are _installed_ but ignores where they are in the source tree.  e.g., `#include <kernel/SiconosMatrix.hpp>` would work nicely in a user program after installation, but would fail at build time because the source path is `kernel/src/utils/SiconosAlgebra/`.  Not sure how to handle that otherwise, in that case maybe this is the wrong tree to bark up.

As for `cs.h` I don't mind really, since that is what it is called in the system.  But perhaps it could be done smoother, not sure.  At least the path could be provided by pkg-config, although unfortunately it seems libsuitesparse-dev does not come with a `.pc` file.  Probably in the debian package I will end up just patching it to hardcode it to `/usr/include/suitesparse/cs.h`.

**Comment by xhub** [comment]
I think it is unreasonable to support compiling against a build tree. For me the scenario should be the user either compiles the sources locally or install a package like libsiconos-dev and wants to use it as a library in his code.

For me cs.h is an issue since libsiconos-dev would have to depend on libsuitesparse-dev for instance, when there is no reason why it should

**Comment by radarsat1** [comment]
> I think it is unreasonable to support compiling against a build tree.

Only Siconos itself ;)  I just mean that compilation of siconos would fail if the headers referred to each other in that manner.  I hadn't thought of that before I posted the issue as I was examining it more from a user point of view.

> For me cs.h is an issue since libsiconos-dev would have to depend on libsuitesparse-dev for instance, when there is no reason why it should

Ah okay I understand, I mean currently it does and I think this is not so bad but perhaps it's possible to hide it completely.

**Comment by xhub** [comment]
Let's see how many things 4b1341090 breaks

**Comment by vacary** [comment]
@xhub 'For cs.h, it is sad that it is included in that way. One of the design principle was to have the end-user code as much as possible independent from the siconos deps.'

I fully agree with you. Another code that should be removed is the include concerning the timer libraries of boost. This is not mandatory, I think, in the Kernel. Furthermore, It prevents to make some "git bisect" just because of changes in the boost libraries. Finally, all the examples must be updated each time boost:: timer changes.

**Comment by radarsat1** [comment]
Also, I realized last night that maybe the only reason I had to add `find_package(Boost)`, apart from the headers, is because I was testing with serialization.  Or maybe it was just the headers.. I'll have to test that.  It's not a big deal I guess, but ideally the user shouldn't have to care that Siconos uses boost internally, although maybe that is not realistic considering that some of our basic types are derived from boost...

like `#include <SiconosGraph.hpp>` will *always* depend on boost.  Same with `BlockCSRMatrix.hpp` and even `NSLawMatrix` is derived from a boost matrix type.

However, agreed with respect to the timer.

**Comment by vacary** [comment]
Clearly, For the timer, we may have if needed, our own implementation based on C++ time function.

**Comment by fperignon** [comment]
Concerning boost timer : the only reason why it’s linked inside siconos is its presence in control/src/Simulation/ControlZOHSimulation.cpp
And I fully agree to the fact that it should be removed and be only used in examples. @xhub, you’re the control guy, can’t we change ZOH to remove boost-timer ? 

Inside Siconos we should use std::chrono I think.

Regarding the header stuff 

#include "SiconosKernel.hpp"
and using,

-I /usr/include/siconos
should not fail.


won’t be possible we the current install process. As Olivier, I don’t think it’s so bad to use -I /usr/include/siconos/{numerics,kernel,mechanics}
but it’s only my opinion

One more thing that may be a source of the problems you have Steve, is that I tried some time ago
to compile with « include-what-you-use » to remove useless headers inclusions,  but I did not completely finish the review and I did not try the process with serialization on. Anyway, it proved to be very efficient to reduce the build time of some examples.

**Comment by xhub** [comment]
> you’re the control guy, can’t we change ZOH to remove boost-timer ?

Fully agree, it's done in 70d1d70ac
It was mostly there for having some fancy data.

Also :+1: for « include-what-you-use »
