### ISSUE TITLE
installed CMake could be improved for using Siconos as a library

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#336]
Out of curiosity I thought I'd see if CMake would take care of problems encountered in the previous issue, since this is mostly a CMake project:

```
cmake_minimum_required(VERSION 3.10)
project(KernelDevTest)
find_package(siconos)
include_directories(${siconos_INCLUDE_DIR})
link_libraries(${siconos_LIBS})
add_executable(KernelDevTest KernelDevTest.cpp)
```

After fixing a couple of things, finally,

```
$ cmake .
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sinclairs/projects/debian/siconos/debian/tests
```

but unfortunately,

```
$ make
[ 50%] Building CXX object CMakeFiles/KernelDevTest.dir/KernelDevTest.cpp.o
/home/sinclairs/projects/debian/siconos/debian/tests/KernelDevTest.cpp:1:10: fatal error: SiconosKernel.hpp: No such file or directory
    1 | #include "SiconosKernel.hpp"
```

Okay there is no variable `${siconos_INCLUDE_DIR}` or `${siconos_INCLUDE_DIRS}` so I'll add it manually:

```
cmake_minimum_required(VERSION 3.16)
project(KernelDevTest)
find_package(siconos)
include_directories(/usr/include/siconos)
include_directories(/usr/include/siconos/numerics)
include_directories(/usr/include/siconos/kernel)
link_libraries(siconos_numerics siconos_kernel)
add_executable(KernelDevTest KernelDevTest.cpp)
```

But still!

```
$ cmake .
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sinclairs/projects/debian/siconos/debian/tests

sinclairs@035d759ffae4:~/projects/debian/siconos/debian/tests (wip-nextrelease)
$ make
Scanning dependencies of target KernelDevTest
[ 50%] Building CXX object CMakeFiles/KernelDevTest.dir/KernelDevTest.cpp.o
In file included from /usr/include/siconos/kernel/SiconosMatrix.hpp:29,
                 from /usr/include/siconos/kernel/BlockMatrix.hpp:27,
                 from /usr/include/siconos/kernel/Utils.hpp:23,
                 from /usr/include/siconos/kernel/SiconosKernel.hpp:25,
                 from /home/sinclairs/projects/debian/siconos/debian/tests/KernelDevTest.cpp:1:
/usr/include/siconos/numerics/CSparseMatrix.h:49:10: fatal error: cs.h: No such file or directory
   49 | #include "cs.h"
```

Finally the right one:

```
cmake_minimum_required(VERSION 3.16)
project(KernelDevTest)
find_package(siconos)
include_directories(/usr/include/siconos)
include_directories(/usr/include/siconos/numerics)
include_directories(/usr/include/siconos/kernel)
include_directories(${SuiteSparse_CXSparse_INCLUDE_DIR})
link_libraries(siconos_kernel)
add_executable(KernelDevTest KernelDevTest.cpp)
```

And this one works!  But it's a lot of things to need to add and to know just to use Siconos as a library.  Can we improve it?  Should we add siconos_INCLUDE_DIR(S?) and siconos_LIBS as output variables for use with `find_package`?  What is the correct way to tell user programs they also need the SuiteSparse include path?

**Comment by radarsat1** [comment]
(By the way FindSuiteSparse.cmake was not installed causing cmake to fail, I will push a commit to fix this.)

**Comment by radarsat1** [comment]
FindSuiteSparse fixed in da83b9266710b7a998321b9756fb288edbd3da91

**Comment by radarsat1** [comment]
I realized maybe i needed to specify the components to `find_package`, so one line changed to:

```
find_package(siconos COMPONENTS numerics kernel)
```

However this results in,

```
CMake Warning at CMakeLists.txt:3 (find_package):
  Found package configuration file:

    /usr/lib/cmake/siconos-4.2.0/siconos-config.cmake

  but it set siconos_FOUND to FALSE so package "siconos" is considered to be
  NOT FOUND.
```

I'll look into that.

**Comment by radarsat1** [comment]
Okay in the other issue @fperignon mentioned that it should be `Siconos::externals` rather than depending on `siconos_INCLUDE_DIRS` or whatever, that sounds like better, more modern use of CMake so I'll check that out tomorrow and close this if it seems I was just doing something wrong.

**Comment by radarsat1** [comment]
alright i found that the following minimal cmake works,

```
cmake_minimum_required(VERSION 3.16)
project(KernelDevTest)
find_package(siconos)
find_package(Boost)
include_directories(${SuiteSparse_CXSparse_INCLUDE_DIR})
link_libraries(Siconos::numerics)
link_libraries(Siconos::kernel)
add_executable(KernelDevTest KernelDevTest.cpp)
```

Actually I was surprised that even `include_directories(Siconos::kernel)` is not needed, apparently `link_libraries` takes care of that?

Anyways, the SuiteSparse line can be removed after @xhub's latest commit so I'll close this.

(imho user shouldn't have to ask for Boost and numerics if it's only using Siconos kernel... maybe at least "find_package(Boost)" can be moved into siconos's cmake? i mean, if it's always required to use Siconos, may as well...)

**Comment by radarsat1** [comment]
I just tested moving `find_package(Boost)` into the installed `siconos-config.cmake` and it did indeed work.  I think that would be a small improvement, but not sure if that's a normal thing to do with cmake, any opinions?

**Comment by fperignon** [comment]
About target_link( …  Siconos::component) yes it handles everything with some cmake magic and propagates all the required dependencies of  Siconos::component declared as PUBLIC or INTERFACE.
And by dependencies, I mean libraries, headers or even compile options or definitions (declared with target_compile_…

Concerning boost, I’m not sure  you can move the find_package(Boost)  into siconos-config.cmake.
To be honest, I had tried this a while ago and change it back for some reason I don’t remember.
Did you try it and run the examples ?

**Comment by radarsat1** [comment]
I did, but just a quick test.  I could more fully test it.  Also I realized maybe in some cases it is only needed for serialization.. at least at link time.  But as noted in the other issue, some parts of siconos definitely require boost for includes, so it seems `find_package(Boost)` would theoretically always be needed.
