### ISSUE TITLE
What about removing plugins from siconos?

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#337]
Everything is in the title. What do you think of this?

+ plugin stuff could be replaced by proper derivation in examples
+ will simplify a lot DS and Relation classes 
+ will avoid memory problems (like #325) due to copy from blocks to C double* required to call plugins
+ from the users' point of view, that won't be more complicated, I think, to use derivation, if properly documented of with the existing examples.

- required a bit of work to re-write properly the examples using plugins

**Comment by xhub** [comment]
Here is a summary of a proposal:
- Remove all the plugings from "base" classes (that is actually all the classes)
- The base classes would have methods `compute*` has pure virtual for any non constant data
- update the methods `compute*` to take the most generic vectors and matrices.
- Add some `Plugin` classes (like `FirstOrderNonlinearPluginR`) that have all the plugin fonctionnalities.
- There would 2 ways to use define a TI/NL DS/Relation:
  - use derivation to implement the methods. This should be the recommended way for basic examples
  - use plugins if the functions are begin generated or for more advanced uses like functions being defined in an external library or via JIT.
