### ISSUE TITLE
[numerics] support NM_SPARSE matrices in fc3d solvers

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#34]
As per @vacary 's request, I've added fc3d_sparse_test.c aka FC3D_sparse_test, a test that tries to solve a dummy fc3d problem with a sparse matrix. I'm raising that issue because I tried to solve fc3d from python that came from a reduction of a gfc3d problem and it failed for a few solvers.

We can discuss the list of solver to test (that is that should have that feature).

I'm only one test for all solvers since we already have too many binaries and tests.

Also if we decide that a solver should not support this kind of solver, it should return an error, not quit like now. Python does not really like that ...

**Comment by vacary** [comment]
It seems that @bremond did a work in that direction.
Maurice @bremond could you report it a bit ?

**Comment by xhub** [comment]
nsgs has been done in 0e38f683d2ede9e0f7c7a265c6e32928b3fbb4f2. Time to do the other ones?

**Comment by vacary** [comment]
I am not able to follow your link number in your previous comment. Dis you want to  ref to
(676ec652880f47a7da86260e22868939989347a1) ?

In any case, it seems that you complete the job in (dff8e2289462df97af7bb289980e941f7e5044f9). Should we close  this issue with a possible new issue on more specific aspects ?

**Comment by xhub** [comment]
I don't remember. There is a bug in the creating of a matrix (it fails with UMFPACK on some simple example, see FC3D_test_sparse). We can list the remaining solvers that it would be interesting to test. For a list of supported solvers, see solvers_to_test in fc3d_sparse_test.c I'll leave it to you to decide which additional solvers should be supported

**Comment by xhub** [comment]
Unfortunately, I don't have time to implement this now. This is low priority and should not block a release. It was partially implemented. 

If @vacary has time to list the solvers that could benefit from supporting the sparse format, it would be nice for a future release.

**Comment by vacary** [comment]
The test fc3d_sparse_test.c is succeeding. I propose to close this issue and to reopen a more specific one if UMFPACK is not working well

**Comment by xhub** [comment]
I believe that it would be good to make a list of solver that should support sparse matrices. That's one of the item from the issue that has not been discussed, I believe.
