### ISSUE TITLE
Compilation errors when upgrading to gfortran 10

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#347]
type-mismatch warnings are turned to errors when using gfortran > 9
See https://scivision.co/gfortran-type-mismatch-error/

And since there are many of these warnings in siconos externals component (from odepack, hem5 ...), compilation fails.

Fix it either with fallow-argument-mismatch ... or remove all fortran dependencies

**Comment by vacary** [comment]
@fperignon Thank you.

The commit d27d70675a9ff027ae68ef5103f6949bc8b7d091 fixes the problem with new CMake (works fro 3.18.2) and the installation problem with `Command` in NumPy.distutils.core. 

By the way, NumPy.distutils.core and distutils.core are both necessary ?
