### ISSUE TITLE
Simulation error for LCS and NLCS

### ISSUE THREAD

**Issue by roccaa** [siconos/siconos#360]
Hello,

I want to report what seems to be a bug in the recent version (4.4.0) of Siconos. With the program attached, I have an inversion error in the EulerOSI at some points of the simulation.
```
-= BEGIN ==== EulerMoreauOSI::computeFreeState()
EulerMoreauOSI::computeFreeState xfree <- residuFree
xfree.display(): [3](1.098832e+00,-6.718191e-04,5.294518e-04)
xfree.display(): [3](3.204918e-01,-1.079612e-03,-5.262468e+01)
EulerMoreauOSI::computeFreeState xPartialNS from Interaction
xPartialNS.display(): [3](-nan,inf,-inf)
/scratch/arocca/Siconos/siconos-gitlab/kernel/src/utils/SiconosAlgebra/SimpleMatrixSolvers.cpp(559): Throw in function virtual void SimpleMatrix::Solve(SiconosVector&)
Dynamic exception type: boost::exception_detail::clone_impl<Siconos::exception>
std::exception::what: std::exception
[Siconos::tag_errno_code*] = 0
[Siconos::tag_errno_description*] = Success
[Siconos::message*] = SimpleMatrix::Solve failed (LU)
```
Using a rollback to 4.3.0, the program simulates without error.

 If needed, I also have a similar simulation error with a FirstOrderLinearTIDS linked to a LCP interaction, coded in python (jupyter).

[bugged-example.zip](https://github.com/siconos/siconos/files/5511738/bugged-example.zip)
[bugged-example python-jupyter.zip](https://github.com/siconos/siconos/files/5511774/bugged-example.python-jupyter.zip)

**Comment by vacary** [comment]
Are you sure that your matrix is invertible ? This was not really checked previously.

**Comment by roccaa** [comment]
Currently I do not really know which matrix it is, I guess it is the W matrix in the compute free state, I will check it ?
In the old version (4.3.0 and prior) if the matrix was singular it would have outputed: 
``SimpleMatrix::PLUForwardBackwardInPlace failed.`` 
right ?

**Comment by roccaa** [comment]
Ok I found what happen. the matrix W becomes singular at some point.
It happens here:
```c++
      // At this point xfree = (ResiduFree - h(1-gamma)*rold)
      // -> Solve WX = xfree and set xfree = X
      DEBUG_EXPR(W.display());
      W.Solve(xfree);
      DEBUG_EXPR(W.display());     
```
Display avant le solve

```
W.display(): SimpleMatrix storage type - num = 1
3.127660e+00, 0.000000e+00, 0.000000e+00, 
-1.000000e-03, 1.000000e+00, 1.000000e-03, 
0.000000e+00, -1.000000e-02, 0.000000e+00,
 ```

solve ...

```
-= BEGIN ==== SimpleMatrix::PLUSolve(SiconosVector &B)
-= BEGIN ==== void SimpleMatrix::Factorize()
-= END   ==== void SimpleMatrix::Factorize()
-= END   ==== SimpleMatrix::Solve(SiconosVector &B)
```

And after the solve

```
W.display(): |  |  SimpleMatrix storage type - num = 1
3.127660e+00, 0.000000e+00, 0.000000e+00, 
-3.197279e-04, 1.000000e+00, 1.000000e-03, 
0.000000e+00, -1.000000e-02, 1.000000e-05, 
```

So the solve function alters the W matrix (NM_LU_solve in particular).

**Comment by vacary** [comment]
Yes, if you work we dense matrix, the matrix is altered. It is rather classical to store LU factor in place. Normally, a flag is set if the matrix is LU factorized.

**Comment by roccaa** [comment]
Ok, this is a bit misleading then when displaying the matrix ... :) 
But then, I really do not see why the solve fails.

**Comment by vacary** [comment]
just to understand. Lu fails on 
```
3.127660e+00, 0.000000e+00, 0.000000e+00, 
-1.000000e-03, 1.000000e+00, 1.000000e-03, 
0.000000e+00, -1.000000e-02, 0.000000e+00,
```

**Comment by vacary** [comment]
The problem comes perhaps from the fact xNS contains inf and nan

**Comment by vacary** [comment]
With 2eea008accd290c74409605df32f3261d005e923, I do not experience your problem.

**Comment by roccaa** [comment]
Ok, I will pull and re-install siconos from scratch, maybe the `make uninstall` I usually run before an update did not do the trick correctly and there is some side-effect ...

**Comment by roccaa** [comment]
Ok I still have the same error even If I switched to the commit you specified. 
I guess it is my installation which is flawed (again) ? 
I did a `make uninstall` then I deleted any remaining trace of siconos in my install folder (`./local`)
Then in an empty build folder I did the cmake call:

``` cmake -DPathFerris_ROOT=/scratch/arocca/Siconos/external-librairies/pathlib/ -DCMAKE_INSTALL_PREFIX=/scratch/arocca/.local/ -DCMAKE_BUILD_TYPE=Release -DWITH_DOCUMENTATION=ON -DWITH_TESTING=ON -DWITH_PYTHON_WRAPPER=ON ../siconos-gitlab/```

Then `make -j4 && make install -j4`

I clean everything in the model folder, and compile it with `siconos example1NSDS.cpp` and still the same error...
