### ISSUE TITLE
Installing Siconos on Ubuntu 18.04

### ISSUE THREAD

**Issue by ali145** [siconos/siconos#369]
Hi dear developers,

I just wanted to find out this code, so how can I install it on Ubuntu 18.04? and what are the precompiled library packages required for installation?

Thank you very much

**Comment by vacary** [comment]
hi
Some recipes for ubuntu distribution can be found in the building scripts of docker images:
https://github.com/siconos/siconos/tree/master/ci_gitlab/dockerfiles

**Comment by ali145** [comment]
I received this error message when I try to install from source.

=============================================================================

~/siconos/build$ cmake .. -DWITH_PYTHON_WRAPPER=ON -DWITH_DOCUMENTATION=ON

 !!!!! Load default configuration set from file /home/ginger/siconos/cmake/default_options.cmake !!!!! 

-- Found python package /home/ginger/.local/lib/python3.6/site-packages/packaging/__init__.py, version 20.7
 ---- Start Blas/Lapack search process ---- 
-- Found a Blas implementation named OpenBlas.
-- Start headers search and functions checking.
-- A library with LAPACK API found.
CMake Error at cmake/BlasLapackUtils.cmake:153 (message):
  LAPACK implementation found is not complete, missing function:
  LAPACKE_dgetrf.
Call Stack (most recent call first):
  cmake/FindLAPACKDEV.cmake:160 (check_interface)
  cmake/SiconosSetup.cmake:138 (find_package)
  CMakeLists.txt:127 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ginger/siconos/build/CMakeFiles/CMakeOutput.log".
See also "/home/ginger/siconos/build/CMakeFiles/CMakeError.log".

**Comment by vacary** [comment]
Your installation of blas lapack Ian not correct

**Comment by vacary** [comment]
Do you plan some comparisons with Yade ? I will be very interested in

**Comment by ali145** [comment]
with LMGC90 and Yade also, if I can install your code.

I installed again blas and lapack from source but I have a new error message.

========================================================
cmake .. -DWITH_PYTHON_WRAPPER=ON -DWITH_DOCUMENTATION=ON

 !!!!! Load default configuration set from file /home/ginger/siconos/cmake/default_options.cmake !!!!! 

-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The Fortran compiler identification is GNU 7.5.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Verifying Fortran/CXX Compiler Compatibility
-- Verifying Fortran/CXX Compiler Compatibility - Success
-- Found Python3: /usr/bin/python3.6 (found version "3.6.9") found components:  Development Interpreter NumPy 
-- Found packaging: /home/ginger/.local/lib/python3.6/site-packages/packaging/__init__.py (found version "20.7") 
-- Found python package /home/ginger/.local/lib/python3.6/site-packages/packaging/__init__.py, version 20.7
 ---- Start Blas/Lapack search process ---- 
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Found a Blas implementation named OpenBlas.
-- Start headers search and functions checking.
-- Looking for cblas_dcopy
-- Looking for cblas_dcopy - found
-- Looking for cblas_dgemv
-- Looking for cblas_dgemv - found
-- Looking for cblas_daxpy
-- Looking for cblas_daxpy - found
-- Looking for cblas_dscal
-- Looking for cblas_dscal - found
-- Looking for cblas_dnrm2
-- Looking for cblas_dnrm2 - found
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for cblas_dgemm
-- Looking for cblas_dgemm - found
-- Found BLASDEV: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Looking for LAPACKE_dgetrf
-- Looking for LAPACKE_dgetrf - not found
CMake Error at cmake/BlasLapackUtils.cmake:153 (message):
  LAPACK implementation found is not complete, missing function:
  LAPACKE_dgetrf.
Call Stack (most recent call first):
  cmake/FindLAPACKDEV.cmake:160 (check_interface)
  cmake/SiconosSetup.cmake:138 (find_package)
  CMakeLists.txt:127 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ginger/siconos/build/CMakeFiles/CMakeOutput.log".
See also "/home/ginger/siconos/build/CMakeFiles/CMakeError.log".

**Comment by ali145** [comment]
lapack-3.9.0.tar.gz

I installed this version of lapack

and I have:

libblas.a  liblapack.a

/usr/local/lib/

**Comment by xhub** [comment]
You need lapacke to be installed. You can get it from the Ubuntu
distribution (liblapacke-dev ?)

**Comment by ali145** [comment]
now it's OK for this command
cmake .. -DWITH_PYTHON_WRAPPER=ON -DWITH_DOCUMENTATION=ON

then, for running an example how can I do?

thanks

**Comment by ali145** [comment]
make
make install
make test

?

**Comment by vacary** [comment]
with `make test`, if you compile with `WITH_TESTING=ON`, you will run all the unit test

**Comment by ali145** [comment]
I installed it but without test option, how can I find a simple example to understand how works this code?

Now in a python medium I can do the command "import siconos" and that works.

**Comment by vacary** [comment]
cool, so you should be able to run the siconos example

**Comment by ali145** [comment]
Not really, until now I could not find a simple example that works with the python interface.
where can I find some example codes?

thanks again.
