### ISSUE TITLE
siconos with BULLET option

### ISSUE THREAD

**Issue by ali145** [siconos/siconos#370]
Hi dear,
I wanted to run an example by python interface that uses apparently bullet option, so I installed the code with these commands:

=========================================================
cmake .. -WITH_TESTING=ON -DWITH_PYTHON_WRAPPER=ON -DWITH_DOCUMENTATION=ON -WITH_BULLET=ON -WITH_XML=ON -WITH_OCE=ON -WITH_RENDERER=ON

make

sudo make install
==============================================

but when I ran the example I received this error message:

######################################
python3 n_cubes.py
No module named siconos.fclib.
[mechanics_run] WARNING: Bullet is the collision backendbut the module siconos.mechanics.collision.bulletcan not be imported. Check your installation.
Traceback (most recent call last):
  File "n_cubes.py", line 16, in <module>
    bullet_options = siconos.mechanics.collision.bullet.SiconosBulletOptions()
AttributeError: module 'siconos.mechanics.collision' has no attribute 'bullet'
####################################################################

thanks a lot

**Comment by vacary** [comment]
```
WARNING: Bullet is the collision backendbut the module siconos.mechanics.collision.bulletcan not be imported.
```
Are you sure that the component mechanics is compiled and corretly installed ?

**Comment by ali145** [comment]
I added 

-WITH_BULLET=ON

in the cmake command

**Comment by vacary** [comment]
and ?
It has successfully installed the package into your python site-packages repository ?

**Comment by ali145** [comment]
how can I check it?

**Comment by ali145** [comment]
/usr/local/lib/python3.6/dist-packages/siconos/mechanics/collision$ ls
base.py    convexhull.py  native.py    tools.py
bodies.py  __init__.py    __pycache__

**Comment by ali145** [comment]
How can I fix this problem of installation for using the SiconosBulletOptions?

should I install it before do make for siconos?

or I have to add other options to line command of cmake?

**Comment by vacary** [comment]
Do  you have a software engineer at Ginger R&D that can help you ?

**Comment by ali145** [comment]
> Do you have a software engineer at Ginger R&D that can help you ?
No.

I try again to install pybullet with "pip3 install pybullet"

and then I will do siconos installation from zero.

**Comment by ali145** [comment]
> I try again to install pybullet with "pip3 install pybullet"
> 
> and then I will do siconos installation from zero.

again same problem, don't work!!!

**Comment by vacary** [comment]
Correct first the typos in the cmake call

**Comment by ali145** [comment]
I didn't pay attention to that. thanks

**Comment by ali145** [comment]
cmake .. -DWITH_TESTING=ON -DWITH_PYTHON_WRAPPER=ON -DWITH_DOCUMENTATION=ON -DWITH_BULLET=ON -DWITH_XML=ON -DWITH_OCE=ON -DWITH_RENDERER=ON


Could not find a package configuration file provided by "OCE" (requested
  version 0.17) with any of the following names:

    OCEConfig.cmake
    oce-config.cmake

  Add the installation prefix of "OCE" to CMAKE_PREFIX_PATH or set "OCE_DIR"
  to a directory containing one of the above files.  If "OCE" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  cmake/SiconosSetup.cmake:168 (include)
  CMakeLists.txt:127 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ginger/siconos-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/ginger/siconos-master/build/CMakeFiles/CMakeError.log".

**Comment by vacary** [comment]
Dear Ali,
Why do you want to install the component that uses OCE?

**Comment by vacary** [comment]
By the way,  I take the opportunity to recall the term of our license (Apache 2.0). Since you are working for a private company, you can use freely siconos, but you have to mention this fact in your commercial projects. In fact, you are obliged by law. 

It is quite important for us since we are paid by the French government to provide software in an open-source way, but we need to have some feedback from users to continue.

**Comment by ali145** [comment]
Hi Vincent
for the moment I could not yet install the Siconos, then I guess that it will take time to learn how it works.
and for instance, I do not know we will have a commercial projects to do with Siconos, if we have a case, I have to mention the name of software used for that. in any case, without your help I know it will be very complicated to arrive for using Siconos, I know that.

For the moment I'm only having fun for trying to install it, that's all, and if I'm not authorized, tell me not to spend the time for it.

Merci Vincent

**Comment by vacary** [comment]
You are clearly authorized under the terms of the license.
The installation is normally quite straightforward on ubuntu, except of you want to use the component with OCE. Remove it for the moment.

**Comment by ali145** [comment]
I remove the OCE option and apparently the problem is solved.
Thanks
