### ISSUE TITLE
document or simple examples for staring to work with Siconos

### ISSUE THREAD

**Issue by ali145** [siconos/siconos#372]
Hi dear users and developers

I'm looking for an explanatory document in simple way or examples in python for trying to start the model generation for siconos.
indeed, I will need as any new user:

1. The way of creating geometry of bodies (sphere, polyhedron,…), the possibility of giving the geometry by file for example in stl format, or I don't know by a txt file
2. Interaction parameters (friction, cohesion, contact law, ..)
3. And also how we can have output files like in vtk format files for example

Thank you very much

**Comment by vacary** [comment]
Hi,

1. Did you have a look to the tutorials? Our documentation is poor, but we have a lot of examples that are maintained.
2. Same answer with the documentation on the code https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos/complete_documentation.html
3. siconos_vview and siconos_export are the right tools see #316

**Comment by ali145** [comment]
I took a look but this document is not practical enough for someone who wants to quickly understand the structure of a model to be created.

**Comment by vacary** [comment]
> I took a look but this document is not practical enough for someone who wants to quickly understand the structure of a model to be created.

I agree with you. We are searching for people to write such a document :-)

**Comment by vacary** [comment]
Did you have a look to the tutorials?

**Comment by ali145** [comment]
I did, but this tutorial does not make you want to follow it. especially as I am looking for models of interaction between rigid bodies and there is not much on this subject.
it is better to have a document based on examples in different circumstances.

**Comment by vacary** [comment]
We have only document examples as 
```
#!/usr/bin/env python

#
# Example of one object under gravity with one contactor and a ground
#

from siconos.mechanics.collision.tools import Contactor
from siconos.io.mechanics_run import MechanicsHdf5Runner

import siconos.numerics as sn
import siconos.kernel as sk
# Creation of the hdf5 file for input/output
with MechanicsHdf5Runner() as io:

    # Definition of a cube as a convex shape
    io.add_convex_shape('Cube', [
        (-1.0, 1.0, -1.0),
        (-1.0, -1.0, -1.0),
        (-1.0, -1.0, 1.0),
        (-1.0, 1.0, 1.0),
        (1.0, 1.0, 1.0),
        (1.0, 1.0, -1.0),
        (1.0, -1.0, -1.0),
        (1.0, -1.0, 1.0)])

    # Alternative to the previous convex shape definition.
    # io.add_primitive_shape('Cube1', 'Box', (2, 2, 2))

    # Definition of the ground shape
    io.add_primitive_shape('Ground', 'Box', (100, 100, .5))

    # Definition of a non smooth law. As no group ids are specified it
    # is between contactors of group id 0.
    io.add_Newton_impact_friction_nsl('contact', mu=0.3)

    # The cube object made with an unique Contactor : the cube shape.
    # As a mass is given, it is a dynamic system involved in contact
    # detection and in the simulation.  With no group id specified the
    # Contactor belongs to group 0
    io.add_object('cube', [Contactor('Cube')], translation=[0, 0, 2],
                  velocity=[10, 0, 0, 1, 1, 1],
                  mass=1)

    # the ground object made with the ground shape. As the mass is
    # not given, it is a static object only involved in contact
    # detection.
    io.add_object('ground', [Contactor('Ground')],
                  translation=[0, 0, 0])

# Run the simulation from the inputs previously defined and add
# results to the hdf5 file. The visualisation of the output may be done
# with the vview command.

options = sk.solver_options_create(sn.SICONOS_FRICTION_3D_NSGS)
options.iparam[sn.SICONOS_IPARAM_MAX_ITER] = 100000
options.dparam[sn.SICONOS_DPARAM_TOL] = 1e-8

with MechanicsHdf5Runner(mode='r+') as io:

    # By default earth gravity is applied and the units are those
    # of the International System of Units.
    # Because of fixed collision margins used in the collision detection,
    # sizes of small objects may need to be expressed in cm or mm.
    io.run(with_timer=False,
           gravity_scale=1,
           t0=0,
           T=10,
           h=0.0005,
           theta=0.50001,
           Newton_max_iter=20,
           set_external_forces=None,
           solver_options=options,
           numerics_verbose=False,
           output_frequency=None)
```

**Comment by vacary** [comment]
With Python, it is also easy to get info and doc. Especially, to get the list of all possible options when you build your model

For reading csv files or stl description, it is also very easy.

I agree that it is perhaps not sufficient for end-users, but we never find time for that.

Contributions are welcome.

**Comment by ali145** [comment]
Thank you very much Vincent, this example works without problem, and via this example, now I can better understand how create a model.

I ran this model, as you can see the below message for the end of running procedure.
================================
[io.mechanics] step 20000 of 20000
[kernel] TimeStepping::newtonSolve --  _newtonNbIterations =1
[kernel] TimeStepping::newtonSolve --  _newtonResiduDSMax =3.9443e-31
[kernel] TimeStepping::newtonSolve --  _newtonResiduYMax =not computed
[kernel] TimeStepping::newtonSolve --  _newtonResiduRMax =not computed
[kernel] TimeStepping::newtonSolve --  _newtonCumulativeNbIterations =20000
[io.mechanics] output in hdf5 file at step  20000
[io.mechanics] number of contacts 4 (detected) 4 (active at velocity level. approx)
[io.mechanics] Numerics solver info at time :  10.000000 iterations =        1 precision = 4.459e-13
[io.mechanics] 
==========================================================

But when I'm trying to visualize the results in vtk format by paraview, this command does not work:

siconos_vview

and it gives me this error message:

############################
ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Filters/Python/vtkPythonAlgorithm.cxx, line 191
vtkPythonAlgorithm (0x1814d30): Failure when calling method: "ProcessRequest": 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 151, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 197, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 854, in RequestData
    self.pos_data = self._idpos_data[self._id_t_m, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 777, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 213, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 1)
.

ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x2211690): Algorithm vtkPythonAlgorithm(0x1814d30) returned failure for request: vtkInformation (0x229e5a0)
  Debug: Off
  Modified Time: 8458
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Filters/Python/vtkPythonAlgorithm.cxx, line 191
vtkPythonAlgorithm (0x1814d30): Failure when calling method: "ProcessRequest": 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 151, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 197, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 854, in RequestData
    self.pos_data = self._idpos_data[self._id_t_m, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 777, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 213, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 1)
.

ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x2211690): Algorithm vtkPythonAlgorithm(0x1814d30) returned failure for request: vtkInformation (0x229e5a0)
  Debug: Off
  Modified Time: 19396
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



Traceback (most recent call last):
  File "/usr/local/bin/siconos_vview", line 23, in <module>
    vview.run()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2695, in run
    self.initialize_vtk()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2663, in initialize_vtk
    self.setup_initial_position()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2102, in setup_initial_position
    self.pos_t0 = [self.io_reader.pos_data]
AttributeError: 'IOReader' object has no attribute 'pos_data'
##########################


How can I solve this problem?

Thanks a lot

**Comment by ali145** [comment]
>>> import h5py
>>> print (h5py.version.hdf5_version)
1.12.0
>>> print(h5py.__version__)
3.1.0


should I downgrade h5py? to what version?

**Comment by ali145** [comment]
this problem is solved by help of below command.

pip3 install --user 'h5py==2.10.0' --force-reinstall --no-cache-dir
