### ISSUE TITLE
VTK export is extremely slow

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#378]
Hi, 

On the example of a 2d flow on an obstacle
http://tripop.inrialpes.fr/people/acary/misc/2d_flow_7s_15.hdf5

siconos_vexport --global-filter

Is extremely slow. The computation takes arounf 2 hours, but the siconos_vexport exports 10% of the simulation in 2 hours.

How would it be possible to accelerate the process ? I am obliged to use parallel, but it slows down my computer?

**Comment by bremond** [comment]
Hi, I cannot reproduce those timings (it takes only  a few minutes on my laptop!) . siconos_vexport rely on vtk, what version of vtk do you use ?

On my laptop with vtk 9.0.1, with 8 procs here is what I get when I run the script given by
    `siconos_vexport --global-filter --gen-para-script=8 2d_flow_7s_15.hdf5`

	User time (seconds): 1863.09
	System time (seconds): 11.28
	Percent of CPU this job got: 744%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 4:11.67

So I had to wait just a bit more than 4 minutes. I checked the results with paraview, it seems ok.

On a computer with the capabilities for 40 procs, 
1) with vtk 9.0.1
    
    	User time (seconds): 1776.93
	System time (seconds): 68.71
	Percent of CPU this job got: 3606%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:51.18

2) with vtk 8.2.0

        User time (seconds): 1822.55
	System time (seconds): 65.86
	Percent of CPU this job got: 3613%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:52.26

    (So less than a minute which is what we could expect. There is a very very small improvement with vtk 9.0.1)

I used some guix commands with a specific channel for siconos (where you can find among others a python-vtk, versions 9.01 and 8.2.0, which is missing in the main guix repository)  so I hope it should be possible to reproduce those results (for vtk 8.2.0 one have to specify python-vtk@8.2.0):

```sh
  cat<<EOF>.channel
  (cons (channel (name 'guix-siconos) (url "https://gitlab.inria.fr/bremond/guix-siconos")) %default-channels)
  EOF
  guix time-machine -C .channel -- environment --pure --ad-hoc \
       python python-numpy python-h5py python-vtk siconos-seq -- \
       siconos_vexport --global-filter --gen-para-script=8 2d_flow_7s_15.hdf5 > exp
  guix time-machine -C .channel -- environment --pure --ad-hoc \
       time dash parallel python python-numpy python-h5py python-vtk siconos-seq -- time -v dash ./exp```

**Comment by vacary** [comment]
I do not understand what happens. I use vtk 9.0.1. I have to investigate

**Comment by vacary** [comment]
It seems that the build of vtk on MacOs with default options in cmake in very slow. I will try to find the good ones to improve the post-processing.
