### ISSUE TITLE
problem with stl foramt file 

### ISSUE THREAD

**Issue by Ali-RAFIEE** [siconos/siconos#379]
Hi everyone,
I send you below my simple code and also the error message that I have when I run this simple example.
I do not know why I can not take into account a stl format file in this code.

Thank you very much in advance.
Ali

#####################################

[slope2.zip](https://github.com/siconos/siconos/files/5829800/slope2.zip)
==== my simple code
from siconos.mechanics.collision.tools import Contactor

from siconos.io.mechanics_run import MechanicsHdf5Runner

from siconos.mechanics.collision.convexhull import ConvexHull

import siconos.numerics as sn
import siconos.kernel as sk
density=2000

# Creation of the hdf5 file for input/output

with MechanicsHdf5Runner() as io:
    vertices=[(-2.5,7.829999923706,17.375),(-2.5,7.829999923706,18.625),(-2.5,8.829999923706,17.375),(-2.5,8.829999923706,18.625),(-1.5,7.829999923706,17.375),(-1.5,7.829999923706,18.625),(-1.5,8.829999923706,17.375),(-1.5,8.829999923706,18.625)]
    
    io.add_convex_shape('bloc-1', vertices, insideMargin=0.0, outsideMargin=0.0)
    #io.add_convex_shape("bloc-1", vertices)
    
    io.add_Newton_impact_friction_nsl('contact', e=0.25, mu=0.7)
    
    
    ch = ConvexHull(vertices)
    inertia,volume=ch.inertia(ch.centroid())
    io.add_object('Block-1', [Contactor('bloc-1')], translation=[0, 0, 0] , mass=volume*density,inertia=inertia*density)

    io.add_mesh_from_file('Slope', 'slope2.stl', scale=1.0, insideMargin=0.0, outsideMargin=0.0)
    
    io.add_object('ground', [Contactor('Slope')], translation=[0, 0, 0])
    
    
    
    
    
# Create solver options
options = sk.solver_options_create(sn.SICONOS_FRICTION_3D_NSGS)
options.iparam[sn.SICONOS_IPARAM_MAX_ITER] = 10000
options.iparam[sn.SICONOS_FRICTION_3D_NSGS_FREEZING_CONTACT] = 100
options.dparam[sn.SICONOS_DPARAM_TOL] = 1e-3

T=20.0
hstep=0.0001

with MechanicsHdf5Runner(mode='r+') as io:
    io.run(with_timer=False,
           explode_Newton_solve=False,
           t0=0,
           T=T,
           h=hstep,
           multipoints_iterations=True,
           theta=1.0,
           Newton_max_iter=50,
           solver_options=options,
           output_frequency=50,
           )
=====================

----- received error message
No module named siconos.fclib.
[io.mechanics] setup model simulation ...
[io.mechanics] 
[io.mechanics] Simulation will run from time 0.0000 to 20.0000s, step 1 to step 200001 (h=0.0001, times=[?,?])
[io.mechanics] 
[io.mechanics] import scene ...
[io.mechanics] import dynamical systems ...
[io.mechanics] Import  dynamic or static object number  1 from initial state
[io.mechanics]                 object name    Block-1
[io.mechanics] Import  dynamic or static object number  1 from initial state
[io.mechanics]                 object name    Block-1
[io.mechanics] Import  dynamic or static object number  -1 from initial state
[io.mechanics]                 object name    ground
[io.mechanics] Import  dynamic or static object number  -1 from initial state
[io.mechanics]                 object name    ground
Traceback (most recent call last):
  File "traject-cube.py", line 55, in <module>
    output_frequency=50,
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/mechanics_run.py", line 2333, in run
    self.import_scene(t0, body_class, shape_class, face_class, edge_class)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/mechanics_run.py", line 1656, in import_scene
    birth=False)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/mechanics_run.py", line 1539, in import_object
    number=self.instances()[name].attrs['id'])
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/mechanics_run.py", line 1032, in import_bullet_object
    shp = self._shape.get(c.shape_name)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/mechanics_run.py", line 471, in get
    tmpf[0].write(data.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
-----------------------

**Comment by vacary** [comment]
This problem comes from my last commit to comply with h5py 3.1.0
Read the last commits message when you update from master !!

**Comment by Ali-RAFIEE** [comment]
Hi Vincent,
I use this version, and it's updated for me.
git clone https://github.com/siconos/siconos.git

**Comment by vacary** [comment]
Do you know how to use it git ?

**Comment by Ali-RAFIEE** [comment]
I don't work too fancy with git, but when I verified my Siconos version with these two commands and I have the below results:

git branch
* master

git pull
Already up to date.

**Comment by vacary** [comment]
Just unroll before the commits concerning h5py last week

**Comment by Ali-RAFIEE** [comment]
I do with this command:

~/siconos$ git reset --hard c1dd7a8
HEAD is now at c1dd7a855 [numerics, kernel] start to implement GeneralMechanical problem for 2D systems

is it right?
