### ISSUE TITLE
Replace https://github.com/sphinx-contrib/youtube by ytsphinx or sphinxembeddedvideos

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#383]
sphinx-contrib/youtube has no release and is not available on Pypi. It seems quite inactive. There is even an issue regarding Pypi, see https://github.com/sphinx-contrib/youtube/issues/9

It seems that ytsphinx is more actively maintained. Also it does install in `site-packages/ytsphinx` which makes it possible to install it via `pip install --user ytsphinx` and no be required to also install all other `sphinxcontrib` packages in `$HOME/.local/lib/python3.X/site-packages/`

**Comment by fperignon** [comment]
Right, let's try it.
I've got a branch where CI is currently running to generate doc : 
https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos/-/jobs/191501
