### ISSUE TITLE
"time_of_death" doesn't work

### ISSUE THREAD

**Issue by nhdanh1997** [siconos/siconos#399]
Hi,
I have a problem using option "time_of_death" when adding an object.
In my simulation for temp > 0.1s, i want to remove an object 'gate' (type box2d) at T = 0.1s by using time_of_death=0.1
The code run well but the object 'gate' was not remove at 0.1s and still remain during all the simulation
Here is a part of my code:
        io.add_primitive_shape('Gate', 'Box2d', (gate_thickness, gate_size),
                               insideMargin=0.0, outsideMargin=0.0)

        io.add_object('gate', [Contactor('Gate')],
                     translation=[gate_x_position, gate_y_position], time_of_death=0.1)
I'm looking for solution, thanks for helping me if you have the same issue

**Comment by vacary** [comment]
Dear Duc,

I just add a PR #400 on this subject and an example here https://github.com/siconos/siconos-tutorials/pull/5

It seems that it works now. I will merge the PRs after all the tests are passed

Best
