### ISSUE TITLE
[Kernel] ZeroOrderHoldOSI: fix implementation of freeoutput

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#40]
this function has not been updated w.r.t. to the last change in the relation.
We need to search in the graph for the data

**Comment by xhub** [comment]
Will try to make it happen before the release

**Comment by bremond** [comment]
As 4.1.0 is released now, should this be postponed to 4.2 (or 4.1.1) ?

**Comment by vacary** [comment]
@xhub Is there a example that fails related this issue ? It would be helpful to fix it.

**Comment by xhub** [comment]
No there is no example that fails. From what I remember, the computation of the free output (computeFreeOutput) should be (almost?) the same as EulerMoreauOSI. It would be nice to put the code from EulerMoreauOSI in  a function to factorize that part. But I may be wrong on that.
