### ISSUE TITLE
Siconos dies with <Signals.SIGSEGV: 11> on OCC examples.

### ISSUE THREAD

**Issue by WyomingWill** [siconos/siconos#401]
Hello, I'm brand new to Siconos, and have been able to run and view examples such as cubes_sphere_contactors.py, doublePendulum.py, ball_and_chain.py, etc... but haven't had any luck with any OCC examples. I've changed the code to deal with the api changes where import OCC.something has been replaced with import OCC.Core.something, and it compiles, runs for a while, and then crashes. Here is an example. I'm running Linux Mint 20. Any help would be great. Thank you!

% siconos occ_balls_in_a_bowl.py 
|===========================================================|
| Siconos software, version 4.4.0 - Copyright 2021 INRIA    |
|                                                           |
| Free software under Apache 2.0 License.                   |
|===========================================================|

[ run /usr/bin/python3.8 /home/me/Installs/siconos/siconos-tutorials-master/examples/mechanics/MultiBodySystems/OCC_Examples/occ_balls_in_a_bowl.py ]

No module named siconos.fclib.
ball mass: 0.014137166941154067
ball center of mass: (-5.4810461691962315e-18, -9.00570352907458e-19, 1.3432060248014857e-18)
ball moment of inertia: (0.00012723450247038658, 0.0001272345024703866, 0.0001272345024703866)
bowl mass: 0.5675810727485562
bowl center of mass: (7.266430274336686e-17, 0.47587638376383734, 1.4616485553673212e-16)
bowl moment of inertia: (0.21453683198875204, 0.3430702953524147, 0.21453683198875226)

*******************************************************************
******        Statistics on Transfer (Write)                 ******

*******************************************************************
******        Transfer Mode = 0  I.E.  As Is       ******
******        Transferring Shape, ShapeType = 0                      ******
** WorkSession : Sending all data
 Step File Name : /tmp/siconos_iol4yff6it(198 ents)  Write  Done
/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_hdf5.py:840: H5pyDeprecationWarning: Deprecated; use vlen_dtype(basetype) instead
  dtype=h5py_vlen_dtype(str))

*******************************************************************
******        Statistics on Transfer (Write)                 ******

*******************************************************************
******        Transfer Mode = 0  I.E.  As Is       ******
******        Transferring Shape, ShapeType = 2                      ******
** WorkSession : Sending all data
 Step File Name : /tmp/siconos_iop10rakrg(350 ents)  Write  Done

*******************************************************************
******        Statistics on Transfer (Write)                 ******

*******************************************************************
******        Transfer Mode = 0  I.E.  As Is       ******
******        Transferring Shape, ShapeType = 2                      ******
** WorkSession : Sending all data
 Step File Name : /tmp/siconos_io5sbg5kcc(32 ents)  Write  Done
/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_hdf5.py:871: H5pyDeprecationWarning: Deprecated; use vlen_dtype(basetype) instead
  name, (1,), dtype=h5py_vlen_dtype(str))
[io.mechanics] setup model simulation ...
[io.mechanics] 
[io.mechanics] Simulation will run from time 0.0000 to 10.0000s, step 1 to step 20001 (h=0.0005, times=[?,?])
[io.mechanics] 
[io.mechanics] import scene ...
[io.mechanics] import dynamical systems ...
[io.mechanics] Import object name: ball1
[io.mechanics]               number (id): 2 
[io.mechanics]               dynamic object
[io.mechanics]               position [0.0, 0.3, 2.0, 1, 0, 0, 0]
[io.mechanics]               velocity [0 0 0 0 0 0]
/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py:508: H5pyDeprecationWarning: Deprecated; use vlen_dtype(basetype) instead
  if self.shape(shape_name).dtype != h5py_vlen_dtype(str) :
Traceback (most recent call last):
  File "/home/me/Installs/siconos/siconos-tutorials-master/examples/mechanics/MultiBodySystems/OCC_Examples/occ_balls_in_a_bowl.py", line 207, in <module>
    io.run(with_timer=False,
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 2373, in run
    self.import_scene(t0, body_class, shape_class, face_class, edge_class)
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 1674, in import_scene
    self.import_object(name=name, body_class=body_class,
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 1562, in import_object
    body, flag = self.import_occ_object(
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 987, in import_occ_object
    contact_shape = occ.OccContactFace(
  File "/usr/local/lib/python3.8/dist-packages/siconos/mechanics/occ.py", line 1054, in __init__
    _occ.OccContactFace_swiginit(self, _occ.new_OccContactFace(*args))
Exception: std::exception
Traceback (most recent call last):
  File "/usr/local/bin/siconos", line 826, in <module>
    main()
  File "/usr/local/bin/siconos", line 179, in main
    run_command(cmd, args.quiet, env)
  File "/usr/local/bin/siconos", line 799, in run_command
    subprocess.run(command, check=True, **extra_args)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3.8', '/home/me/Installs/siconos/siconos-tutorials-master/examples/mechanics/MultiBodySystems/OCC_Examples/occ_balls_in_a_bowl.py']' died with <Signals.SIGSEGV: 11>.

===========================================================================================

A short hdf5 file is produced, but attempting to visualize it yields:

% siconos_vview occ_balls_in_a_bowl.hdf5 
Loaded configuration from  /home/wspears/.config/siconos_vview.json
   background_color :  [0.0, 0.0, 0.0]
   window_size :  [600, 600]
/home/wspears/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/wspears/.local/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/usr/local/bin/siconos_vview", line 22, in <module>
    vview = VView(io, opts, config)
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/vview.py", line 1194, in __init__
    self.io_reader.SetIO(io=self.io)
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/vview.py", line 1051, in SetIO
    self._min_timestep = numpy.min(dcf)
  File "<__array_function__ internals>", line 5, in amin
  File "/home/wspears/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2830, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/wspears/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by vacary** [comment]
Thank you for your feedback. I am on vacations but I will try to have a look to this example.

It seems that the problem comes h5py. What is the version of h5py that you use ?

**Comment by WyomingWill** [comment]
Thanks for replying and I hope you enjoy your vacation!
Does this indicate the version of h5py??

% sudo pip3 install h5py
       
Requirement already satisfied: h5py in /usr/local/lib/python3.8/dist-packages (2.10.0)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from h5py) (1.15.0)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.8/dist-packages (from h5py) (1.19.5)

**Comment by WyomingWill** [comment]
Hello, I downloaded h5py-3.2.1.tar.gz, extracted it, installed it with 'sudo python3 setup.py install' as per instructions, recompiled siconos and got the same error messages. How can be sure it used the new h5py? Thank you.
