### ISSUE TITLE
[Kernel] implement a resetState method for DS

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#41]
Right now it is difficult to reset the state of a dynamical system. We need to do it for the SMC controllers. The idea is to implement a method to do that properly.

**Comment by vacary** [comment]
Again a good idea. What do you want to do exactly ?
- reset the state x to a arbitrary value ?
- keep or reset also x0 the initial state ?
- keep, or reset or erase the siconos memory vectors that are related to the state ? 

It is that our long term to put all simulation variables to the graph keeping just a alias as current state in  the object will help

**Comment by vacary** [comment]
any updates ?

**Comment by xhub** [comment]
Unfortunately, I don't have time to implement this now. This is low priority and should not block a release.

**Comment by vacary** [comment]
Dynamical systems implement resetToInitialState(). If it is sufficient, please open a new issue with a specific requirements
