### ISSUE TITLE
AttributeError: 'EulerMoreauOSI' object has no attribute 'insertDynamicalSystem' in 'Tutorial: A 4-diodes bridge wave rectifier'

### ISSUE THREAD

**Issue by yurivict** [siconos/siconos#414]
These 2 lines fail:
```
osi = sk.EulerMoreauOSI(theta)
osi.insertDynamicalSystem(ds)
```

```
Traceback (most recent call last):
  File "x.py", line 49, in <module>
    osi.insertDynamicalSystem(ds)
AttributeError: 'EulerMoreauOSI' object has no attribute 'insertDynamicalSystem'
```

URL: https://nonsmooth.gricad-pages.univ-grenoble-alpes.fr/siconos/getting_started/tutorial_python/diode_bridge.html

**Comment by fperignon** [comment]
Hi,

the documentation is wrong and outdated. We'll fix this.
Just remove the line osi.insertDynamicalSystem(ds).
The reference for the DiodeBridge example is the notebook available here:
https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-tutorials/-/blob/master/siconos-notebooks/st01_diode_bridge.ipynb
