### ISSUE TITLE
Siconos on windows

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#426]
Dear all,
Do any of you have an idea how to install Siconos on Windows?
WSL2 for example? https://solidstudio.io/blog/windows-subsystem-for-linux-explained 
jupyterlab with a docker image?
Best

**Comment by spellizzari** [comment]
Hello,

Here is a recap of the steps I followed to get Siconos running in WSL2 along with the GUI, based on the links given by @roccaa.

- First, install WSL2 by running `wsl.exe --install` in an elevated prompt, then go to the Microsoft Store and install the Ubuntu 20.04 distribution. Then you can run the prompt for this distribution from a Windows prompt by running command `ubuntu2004`.
- From the ubuntu prompt, download and install updates with `sudo apt-get update`, `sudo apt-get upgrade` and `sudo apt-get dist-upgrade`.
- Install the dependencies to be able to compile SICONOS with `sudo apt install cmake git-core wget make libboost-dev libgmp-dev swig gcc gfortran g++ liblapack-dev libatlas-base-dev lp-solve liblpsolve55-dev python3-dev libpython3-dev bash swig doxygen python3-pip htop libcppunit-dev python3-scipy python3-pytest valgrind python3-h5py liblapacke-dev libopenblas-dev libbullet-dev`. and `pip install pyhull`.
- Follow the installation guide to compile and install SICONOS as you would on Linux. The command `siconos` is now able to run properly.

For the GUI, I followed this:
- `sudo apt install ubuntu-desktop mesa-utils`, then `pip install vtk`.
- Add the following to your `~/.bashrc`:
```
export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1
```
- Source your bashrc with `source ~/.bashrc` to reload it into current prompt.
- On Windows, install a X11 client. I used VcXsrv [https://sourceforge.net/projects/vcxsrv/](url). 
- Open the firewall advanced settings and add an **inbound rule** for TCP port 6000 with scope 172.16.0.0/12.
- Run VcXsrv and on the Extra settings page of the startup wizard, **uncheck** "Native opengl" and **check** "Disable access control".
- Do a test on unbuntu with command `glxgears`. If all went well you should see a window open with an animation of gears. This should allow you to run command `siconos_vview`.

Some references on those topics:
[https://github.com/microsoft/WSL/issues/2855#issuecomment-613935650](url)
[https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2](url)

**Comment by vacary** [comment]
@roccaa @spellizzari Thank you very much for your input. I think it will very useful for Windows users.
