### ISSUE TITLE
[Kernel] remove weak_ptr link from Simulation to Model

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#43]
A Simulation object should not have a weak_ptr to the Model.

A quick look at the code show that the Model is needed for 2 reasons:
- getting access to the topology. We can directly put a SP to the Topology.
- setting and getting time from the Model. My understanding is that the reference for the current/next time is the EventManager. The only usage I've spotted to get the current time through the following calls:  simulationLink->model()->currentTime(). Hence, I think a method of Simulation can directly  get this info.

Is this analysis correct or did I miss something?

**Comment by vacary** [comment]
I think you have completely right. The important link is the _simulation in the Model. The reverse link is curious but it comes form the fact that Topology is an hybrid class between simulation and modeling.

One the question is the preliminary design of Scions was to limit the relation between simulation and modeling, but is is very artificial. I think we have to identify the right level of discussion between modeling and simulation

I will remove the weak_ptr to model and put a pointer topology. The management go time is also quite curious. I will to work on that point

**Comment by vacary** [comment]
I have a question. If we remove the weak_ptr to simulation, we will need SP to topology and  possibly to nsds.

Will it solve the problem or just increase the size of the cycle between SPs ?

**Comment by vacary** [comment]
I remove the weak_ptr to Model in Simulation. I put a pointer to the nsds in the simulation. see 88ba163d675e3baf5b0e553c67370d6bca785e41and e94c2607df1e3e46ea89b5e533ea75995c2d0971

I was obliged to add the model in the initialization of the OSI just for the initialization of the extraAdditionalTerms. Indeed, the MatrixIntegrator needs the model for the setting the time interval of study. I can be perhaps optimized.

Another question that is raised is the fact that the management of the time is mainly in the simulation 
through the event manager. There is some curious call in EventDriven.cpp that have to be reviewed.
Be careful, the time in the model is not updated. If needed, this has to be made to an external call to Model::setCurrentTime.

**Comment by xhub** [comment]
Cool thanks for the work.

I don't think it is unreasonable for now to pass the Model at the initialization. I agree that we should review the time management and document it a bit more.

**Comment by vacary** [comment]
I close this issue and we can add a new one for the question of the time management.
