### ISSUE TITLE
Very slow siconos_vview 

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#432]
Hi,

I experience very slow 3D view of hdf5 files with siconos_vview which makes it nearly unusable. I use the latest version of siconos from master, under Ubuntu 20.04 and python3.
For instance, I ran the sphere.py example script from [here](https://github.com/siconos/siconos-tutorials/blob/master/examples/mechanics/GeometricPrimitives/sphere.py), and I got the linked hdf5 file : [sphere.hdf5.zip](https://github.com/siconos/siconos/files/7733710/sphere.hdf5.zip)
Then the 3D view in siconos_vview is very sluggish, very difficult to move the view or move sliders. Moving the timeline makes the situation even worse, I have huge delays between clicks and UI reaction.
At the same time, the terminal outputs some errors, but I can't tell whether it is linked to this issue. I get a bunch of :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/siconos/io/vview.py", line 1070, in RequestData
    self.cpa_at_time[mu])
KeyError: 0.1
```
Other 3D interfaces on my system are ok, including ones based on vtk and PyQt5. So this is likely not a hardware or driver issue I guess.

Do you have an idea about this ?
Thanks.

**Comment by vacary** [comment]
Hi,

On my computer (MacOsX), siconos_vview is very fast. Is it not always the case when we have a lot of objects. In the latter case, we prefer use paraview.

For the error output, it is a bug that we have to fix. The result of this bug is some persistency of contacts points in the scene even if they do not exist.

Perhaps, others have the same problem on Linux + Python3 and may help

**Comment by bremond** [comment]
Hi,

The visualization of the hdf5 is fast on my computer also (It is just one ball bouncing on a ground and then falling outside).
You can reproduce what I can see with guix (https://guix.gnu.org), just cut and paste this in a shell (of course, be patient the first time you do it):

```
addr=https://raw.githubusercontent.com/siconos/guix-siconos &&
wget -N $addr/channels/siconos-2021-06-08.scm && \
   guix time-machine -C siconos-2021-06-08.scm -- \
       environment  --pure --ad-hoc \
       python-vtk@8.2.0 siconos -- \
       siconos_vview sphere.hdf5
```

Note that the version of vtk is 8.2.0 (It fails with vtk 9.0). In the past, I experienced very slow visualization with vtk compiled without -DCMAKE_BUILD_TYPE=Release.

**Comment by bremond** [comment]
I had a try without guix on my system (which is a ubuntu 21.04). vtk-8 is not available from apt : only vtk-7 and vtk-9 and with both the sphere is not drawn. Only the plane and the contact force are visible. To keep this in mind, I related this in #436.

**Comment by vacary** [comment]
The issue comes from a bad management of the initial transparency of object.

Did you play with the key "t", "y"ot "u" to see if the sphere appears? I remember a post on that subject in vtk mailing list.

**Comment by batzkass** [comment]
On my 20.04 I only have vtk-7 in the package manager. In addition of the slowness, I realize that that - just like @bremond said -  the sphere does not appear, only the contact forces.
Multiple press of 't', 'y', 'y' makes the pane disappear, but the slowness isn't solved.

**Comment by bremond** [comment]
Pressing 'T' makes the sphere appears with vtk9 (So I propose  #437 which also fix the forces display and the error messages, I did not check with vtk 7)

**Comment by bremond** [comment]
I removed python3-vtk9, I also removed vtk installed via pip3 and I did the check with python3-vtk7 package on ubuntu 21.04. It works and it is fast.

**Comment by batzkass** [comment]
> Hi,
> 
> The visualization of the hdf5 is fast on my computer also (It is just one ball bouncing on a ground and then falling outside). You can reproduce what I can see with guix (https://guix.gnu.org), just cut and paste this in a shell (of course, be patient the first time you do it):
> 
> ```
> addr=https://raw.githubusercontent.com/siconos/guix-siconos &&
> wget -N $addr/channels/siconos-2021-06-08.scm && \
>    guix time-machine -C siconos-2021-06-08.scm -- \
>        environment  --pure --ad-hoc \
>        python-vtk@8.2.0 siconos -- \
>        siconos_vview sphere.hdf5
> ```
> 
> Note that the version of vtk is 8.2.0 (It fails with vtk 9.0). In the past, I experienced very slow visualization with vtk compiled without -DCMAKE_BUILD_TYPE=Release.

Thanks for the effort, launched that but unfortunately I don't have enough ram on my laptop to compile siconos on more that 3 or 4 cores.

Maybe we should wait 22.04 and see what happens.
