### ISSUE TITLE
Contact persistency and Bullet contact detection for spheres.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#439]
Hi,

The Bullet contact detector usually performs very well with contact persistency using its inherent feature given by btPersistentManifold.

For contact between spheres, it seems that there is no persistency. As a consequence on the siconos side, a new interaction is destroyed and then created at each contact detection step between two spheres. See attached example.

Did you observe the same behavior?

Perhaps, we need to use insideMargin in a smarter way for spheres?

[multispheres.py.txt](https://github.com/siconos/siconos/files/7802509/multispheres.py.txt)

**Comment by bremond** [comment]
Hi, for contact with spheres if I set 

```python
bullet_options.perturbationIterations = 1
bullet_options.minimumPointsPerturbationThreshold = 1 
```

instead of

```python
bullet_options.perturbationIterations = 3
bullet_options.minimumPointsPerturbationThreshold = 3
```

The contact points remain the same and the stack stay in place, whereas with 3 it collapses. 

[multispheres.tar.gz](https://github.com/siconos/siconos/files/7880990/multispheres.tar.gz)

**Comment by vacary** [comment]
@bremond  

I agree with you that removing the iterations of pertubations allows to get a better contact points, but all the  interactions between spheres  are destroyed and created again at each  contact detection. There is no contact persistency in that case.

For the contact between the bottom sphere and the box, the interaction is created once and updated at each contact detection. The persistency is working well.

I do not know this feature is intrinsically into bullet3, or if we misuse the bullet3 code

By the way, since you are using Newton iterations and you perform only one newton iteration per step, you have two contact detections (a first contact detection when we initialize the newton loop, a second one for the first iteration). Then 6 interactions are destroyed and updated at each time step

**Comment by vacary** [comment]
Ok, it seems related to a bug in Bullet see https://github.com/bulletphysics/bullet3/issues/4334
