### ISSUE TITLE
[Kernel] Do not selfthrow if Lsodar fails

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#44]
If Lsodar fails to integrate at one point, we just selfthrow and leave the poor user in the dark.
We should at least print the current state. A way to abort the simulation but still save simulation data somehow would be good.

**Comment by xhub** [comment]
Unfortunately, I don't have time to implement this now. This is low priority and should not block a release. It would be nice to fix it if someone wants to take up the task.

**Comment by vacary** [comment]
Transfered in wiki
