### ISSUE TITLE
[Kernel] remove dead code

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#45]
The functions in the following files appear to be use nowhere and has seen few updates in the last years. Therefore I think they could be consider for removal or move to some ``old'' directory. All the following files/classes are in the Kernel.
- DynamicalSystemFactory
- RelationFactory
- utils/contract/check.hpp
- SiconosSet
- Cmp

Possible removal (no use of functionalities)
- swapInMemory in DS ?

If you know more and especially why we should keep something or if you agree that some are effectively unused, raise your voice!

**Comment by vacary** [comment]
My point of view :  
 * utils/contract/check.hpp : we can remove  it but it seems that it has already been removed 
 * factories : I am not fond of factories, but it can be useful in the future if we design a GUI over the the standard DS.
 * SiconosSet/Cmp. We can put into an old directory or in siconos-junk
 * swapInMemory in DS are used in most of the time--stepping at every time-step. The goal is to replace this functionality by another one ?

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2016-04-23 14:36:58 -0700]:

> My point of view :  
>  * utils/contract/check.hpp : we can remove  it but it seems that it has already been removed 

Right. Someone else took care of this.

>  * factories : I am not fond of factories, but it can be useful in the future if we design a GUI over the the standard DS.

Ok. I'll try to document that somehow.

>  * SiconosSet/Cmp. We can put into an old directory or in siconos-junk

I can do that (moving to siconos-junk)

>  * swapInMemory in DS are used in most of the time--stepping at every time-step. The goal is to replace this functionality by another one ? 

Right. I missed the call to swapInMemory because it is done in a nice way in OneStepIntegrator::saveInMemory, with a std::bind and thus no '()'. My regexp didn't see it.
Mystery solved :)

I'm hijacking this bug report, but shouldn't we remove OneStepIntegrator::saveInMemory and in Simulation::saveInMemory iterate over the DSs of the indexSet0? We already do it this way for the Interaction (Simulation::pushInteractionsInMemory). This way we remove one use of OSIDynamicalSystems !

**Comment by vacary** [comment]
In fact, I have already removed the iteration over the DynamicalSet and replaced it by iteration on the OneStepIntegrator::_dynamicalSystemGraph. The solution is a little bit less elegant because I don't know how to use the std::bind method on the internal set::vector or std::mao of the graph.

Any idea ?

**Comment by xhub** [comment]
As far as I know, there is no advantage of having for_each instead of
the current loop. The code looks just fine to me.

**Comment by vacary** [comment]
It seems that there is nothing more to implement. Should we close ?

**Comment by xhub** [comment]
I removed SiconosSet/Cmp with e966d1128

Closing since everything has been done from my POV
