### ISSUE TITLE
Possible problem with contact surface / block position generation 

### ISSUE THREAD

**Issue by davidpilz** [siconos/siconos#455]
Hi,

I was playing around with siconos a bit and stumbled across a weird issue with the contact surface.
The goal I was trying to achive is setting up a simple inclined plane with some cuboids directly on the surface. Then I just wanted to observe how the simulation would propagate the cuboids.

But surprisingly when looking at the .hdf5 with siconos_vview, the blocks further down the plane gradually clipped into the surface or later spawned completely on the other side.
However, this was not the case for the blocks further up. They behaved as expected.

My first thought was, that I got the internal definition of the coordinate system wrong - I assumed (0, 0, 0) being the center of the defined heightmap / grid.
But a constant offset in cartesian coordinates should effect _all_ blocks equally..?

So how is the coordinate system defined internally in siconos?
Is there any detailed documentation on that topic available that I have not found?

Or could it be possible, that there is some issue with the initialization of the contact surface / the bodys?

It is entirely possible, that I misunderstood some part of siconos or have some other flaw in my code.
As I am kind of at a loss here, any help or idea is much appreciated!

---------------------------------------------------------------------

**Expected**: All blocks get initialized the same, i.e. like the blocks further up the plane, their z-position corresponding to the height given by the heightmap.
**Observed**: Only the blocks on the upper side of the plane spawn as expected, further down they increasingly clip through or spawn on the other side (their z-position being different from the heightmap). Maybe there is something wrong with the initialization of the heightmap / blocks?

A minimal working example python script with a small .hdf5 output file can be found here https://owncloud.gwdg.de/index.php/s/mIPaxOwXWlw5KYk

Setting 'bare_minimum = False' at the start of MAIN will adjust the orientation and (slightly) the position of the blocks, otherwise the default orientation and the unaltered height from the heightmap are used as starting parameters for the blocks.

If there are any questions/recommendations concerning the code - please let me now :)

**Comment by vacary** [comment]
Dear @davidpilz 

I tried to reproduce your issue. When I am running your script, I have only one block that is on the side of the plane. The contact points are not correctly located. I will have a look.

could you update your example such that there are multiple cuboids?

Your questions:
>  But a constant offset in cartesian coordinates should effect all blocks equally..?
Normally, yes.
> Is there any detailed documentation on that topic available that I have not found?
No, unfortunately. The coordinate system is defined on the position of the center of mass and a quaternion for the orientation.
> Or could it be possible, that there is some issue with the initialization of the contact surface / the bodys?
I will have a look on that

**Comment by davidpilz** [comment]
Dear @vacary,
Thanks for looking into this issue!

My script should already spawn multiple cuboids at positions specified in l. 216.
As written in my original post, only the first cuboid (the upper position, i.e. indices [0, 0]) spawns on the desired side of the plane.
The other two, a middle position and a bottom one, spawn on the other side (they might be tricky to locate in vview, as the overall plane is quite large).

If you want to spawn more cuboids, you just have add the desired indices (ranging from (0, 0) to mZ.shape -1) to the 'position' list at l. 216.

**Comment by davidpilz** [comment]
I just added a small loop to generate multiple cuboids in the middle of the plane for each index from 0 to mZ.shape[0].
That should make the issue a bit clearer I hope.

The updated script (with deactivated prints) as well as the output .hdf5 can be found at the same location (https://owncloud.gwdg.de/index.php/s/mIPaxOwXWlw5KYk).

**Comment by vacary** [comment]
ok, I see that the cuboids at the initial time are not above the plane,  but they start with a contact penetration. It means that the contact detection will be curious.

**Comment by vacary** [comment]
The coordinnates of the object is Siconos are defined w.r.t. the center of graviry. It seems that there is a mismatch between  the coordinates of the block and the position of the plane.

**Comment by davidpilz** [comment]
At this link you may find an updated version of my scripts earlier.
Now, at each grid point a spheres gets initialized clearly showing the mismatch between the simulated terrain and the input coordinate system grid

https://owncloud.gwdg.de/index.php/s/TTVkJqOkDAFn0SW

The script can be simply run by excuting
`python3 minimal_working_example.py`
in a shell.

Additionally, the script and .hdf5 file for a more complex height map can be found in the folder 'Euclides_K', and some already simulated versions of the simple incline with different resolutions in the folder 'incline_resolutions'.
For the complex height map, you need to run
```
python3 LROC_simulation_coordinates.py -g Euclides_K_map.asc -s Euclides_K_soil.asc -b Euclides_K_positions.asc -m rocks_params.csv -n soil_params.csv```

**Comment by vacary** [comment]
Dear @davidpilz 

For the mismatch between the simulated terrain and the coordinate system grid, I corrected you script in a specific branch of the following repo:

https://github.com/vacary/siconos-tutorials/commit/ac9df29ca43c157dc29b688c341018041829a0b3

I think there is a misunderstanding how the grid constructed in Siconos and in fact in bullet through this object `btHeightfieldTerrainShape`

If you want a terrain of 10 x 10m  with a resolution of 2m you need to give a grid of heights of 6x6 entries and not 5x5 entries.

To construct the heightmap, the key point is the internal computation of the resolution. It uses the number of points in the x-direction that corresponds to the width of the heightmap. if you have `n` points, then you have `n-1` segments and the resolution is `width/(n-1)`. This does not correspond to the definition in you `mininal_working example.py`

Let me know if it is clearer for you.

**Comment by vacary** [comment]
For the complex heightmap example in the `Euclides_K` directory, the script is not working in debug mode on my system. I have the following assert that comes from `bullet3` that has also be complied in debug mode.

```
...

[io.mechanics] import nslaws ...
[io.mechanics] import joints ...
[io.mechanics] import permanent interactions ...
[io.mechanics] first output static and dynamic objects ...
[io.mechanics] start simulation ...
[io.mechanics] step 1 of 50000
Assertion failed: (ptIndex >= 0), function convexHullSupport, file btConvexShape.cpp, line 121.
Abort trap: 6
```

It seems that there is a problem with the number of points defining the convex hull. I will try to have a closer look

**Comment by vacary** [comment]
Yes, it a good sign that the spheres are not not far from the corner of the triangle of the heightmap

put the sphere in a dummy collision group to avoid that

**Comment by davidpilz** [comment]
Oh, right.... 
Yes, with those modifications everything seems to be spawned correctly now!

Thank you for your time and help!
