### ISSUE TITLE
Bug concerning the ds IDs saved in cf and cf_info (.hdf5 datasets)

### ISSUE THREAD

**Issue by davidpilz** [siconos/siconos#456]
Hi, 

when looking at the generated .hdf5 output file of a simulation, I find the exact same integer in the dataset cf for 'ds 1 number' and 'ds 2 number'.
This gets replicated in the dataset cf_info as well.

As I thought, those numbers refer to the IDs of _both_ objects involved in the contact, I assume this might be a bug in the code.

---------------

**Observed:** 'ds 1 number' and 'ds 2 number' are the same in datasets cf and cf_info.
**Expected:** 'ds 1 number' and 'ds 2 number' are different as they refer to different objects involved in the contact.

It should be possible to replicate this behaviour by simply running a simluation with a MechanicsHdf5Runner() instance where two objects interact with each other.

A minimal working example reproducing this can be found here (same as the example for #455 ): https://owncloud.gwdg.de/index.php/s/mIPaxOwXWlw5KYk

Setting 'bare_minimum = False' at the start of MAIN results in contacts between the upper block and the ground as the block slides down the incline where both 'ds 1 number' and 'ds 2 number' are saved as '1'.

**Comment by vacary** [comment]
Dear @davidpilz 
Sorry for my late reply.
This is not a bug, but a consequence of our choices to distinguish contact between dynamical systems (objects that have a mass and inertia) identified by a positive integer and fixed static object identified by negative integer.

In cf, if you have the same number for ds1 and ds2, it means that the contact is made between the dynamical system object and a static fixed object.

In cf_info, we add more information. You have again ds1 number, ds2 number and the id of the static object (that is negative by convention). In you case, you have in cf_info
```
         (0,0): 0.001, 0, 1, 1, -1,
```
meaning that the ds number 1 (cuboid_0) is in contact with the static object -1 (ground_1)

I agree that this convention is a little bit curious, and perhaps to change that to be a bit clearer.

Best

**Comment by davidpilz** [comment]
Dear @vacary 
Thanks for your answer!

Ok, that makes some sense to me now.

But from a user's perspective, I certainly would prefer if all contacts would be saved in the same way.
If all objects (dynamic as well as static ones) get an unique ID, the contact information would still be unambigously saved in 'cf' and it just would be up to me to track my object-types if I want to distinguish between, say, 'dynamic' contacts  (ds-ds) and 'half-dynamic' (ds-static). 

In my opinion, that would clear things up a lot, as then ***all*** contacts can be clearly analysed by just looking at 'cf/ds number 1 , ds number 2' - though the naming might need to be changed for those values. 
And as a plus, 'cf_info' (which to my knowledge is soley mirroring a portion of 'cf' - apart from the static-object ID) won't be needed anymore.

If a change like that is not in the scope of the project or desired right now, I would suggest to document this (in my opinion not so obvious) convention somewhere if possible!

Best
