### ISSUE TITLE
[Numerics] Linear System (LS) solver category

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#46]
There is an LS Solver category in Numerics. Even though solver for Linear System is an important topic, it is far beyond the scope of Numerics.
It is basically a wrapper around LAPACK solver, with the same infrastructure as other categories of solvers.
The whole setup serves only one purpose: to have a consistent interface in GMP, which is nice, but it does not require to have its own category and to be displayed on the front page of Numerics. It should be rather hidden in tools or in GMP.

**Comment by vacary** [comment]
For me,  it is only aesthetic  change. If you want to put the LinearSolver in  tools, you can.

**Comment by vacary** [comment]
Finally, what did you decide ?

**Comment by xhub** [comment]
I'll do it soon

**Comment by xhub** [comment]
Done with a51dd793c and 96283106b

We don't have a least-square solver with NumericsMatrix. We can implement one is needed

**Comment by vacary** [comment]
The least-square method was used ? What is used in lcp_enum ? A direct call to a LAPACK solver ?

**Comment by xhub** [comment]
There was some code in LinearSolver_driver.c I believe. And yes, it was a call to DGELS. But in LCP/lcp_enum.c and MLCP/mlcp_enum.c there is directly a call to DGELS, it was not using LinearSystemProblem. That code was only used in GeneralMechanicsProblem.
