### ISSUE TITLE
Bug in ADMM solver

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#460]
I can only reproduce this when the package (current master on github, 629130d32c80647e2535e13f00840a322bd91447) is built with `CMAKE_BUILD_TYPE=Debug`, but I've verified that in release mode the problem is still present but the assertion is just skipped.

I get the following errors running "make test" in the `numerics` directory:

```
96% tests passed, 3 tests failed out of 79

Total Test time (real) = 315.64 sec

The following tests FAILED:
	 36 - fc3d_TEST_NSN_COLLECTION_1 (Failed)
	 37 - fc3d_TEST_NSN_COLLECTION_2 (Subprocess aborted)
	 64 - ConvexQP_test_collection (Subprocess aborted)

```

If I run `ConvexQP_test_collection` manually, I get the following output on `test_2`:

```
start test #2
test step 1
z[0]=-5.000000	PX[0]=0.000000
z[1]=-4.000000	PX[1]=0.000000
z[2]=-3.000000	PX[2]=0.000000
z[3]=-2.000000	PX[3]=0.000000
z[4]=-1.000000	PX[4]=0.000000
z[5]=0.000000	PX[5]=0.000000
z[6]=1.000000	PX[6]=0.000000
z[7]=2.000000	PX[7]=-5487458222656572253044242706512533009332565296704281842353464341423459222659694957657785623185792771358609158748433686054963230167620949827376493029768065102014423289909563218546376801907227961512137003210872266266533210566056108843254404124141251251786124500068864635864510729375034248770336586551263232.000000
z[8]=3.000000	PX[8]=0.000000
z[9]=4.000000	PX[9]=0.000000
q[0]=-1.000000	q[1]=-2.000000	q[2]=-3.000000	q[3]=-4.000000	q[4]=-5.000000	q[5]=-6.000000	q[6]=-7.000000	q[7]=-8.000000	q[8]=-9.000000	q[9]=-10.000000	test step 1
ConvexQP_test_collection: /home/sinclairs/projects/siconos/numerics/src/tools/NumericsMatrix.c:2993: NM_triplet: Assertion `NM_max_version(A) == NSM_version(A->matrix2, NSM_TRIPLET)' failed.
Aborted (core dumped)
```

The first problem is that PX is obviously invalid.  This can easily be fixed by adding,

```
cqp.m=10
```

to the top of the function ([here](https://github.com/siconos/siconos/blob/master/numerics/src/QP/test/ConvexQP_test.c#L181))

But the real bug is something to do with these NumericsMatrix version numbers.  I have been trying to debug it myself because it's blocking me from updating the Debian package, but unfortunately I just don't know enough about what's supposed to happen with these version numbers.  It appears that in this case A is actually an `NSM_CSC`, so it's trying to compare the `NSM_CSC` version with the `NSM_TRIPLET` version and they are different, but I can't figure out where in the ADMM loop something is either failing to clear the triplet or failing up update a version number.

If I add a print statement just before the assertion (and include the above `cqp.m` fix), I get this output:

```
start test #2
test step 1
z[0]=-5.000000	PX[0]=3.000000
z[1]=-4.000000	PX[1]=3.000000
z[2]=-3.000000	PX[2]=3.000000
z[3]=-2.000000	PX[3]=3.000000
z[4]=-1.000000	PX[4]=3.000000
z[5]=0.000000	PX[5]=3.000000
z[6]=1.000000	PX[6]=3.000000
z[7]=2.000000	PX[7]=3.000000
z[8]=3.000000	PX[8]=3.000000
z[9]=4.000000	PX[9]=4.000000
q[0]=-1.000000	q[1]=-2.000000	q[2]=-3.000000	q[3]=-4.000000	q[4]=-5.000000	q[5]=-6.000000	q[6]=-7.000000	q[7]=-8.000000	q[8]=-9.000000	q[9]=-10.000000	test step 1
NM_max_version(A): 0, NSM_version(A->matrix2, NSM_TRIPLET): 0
NM_max_version(A): 0, NSM_version(A->matrix2, NSM_TRIPLET): 0
NM_max_version(A): 1, NSM_version(A->matrix2, NSM_TRIPLET): 0
ConvexQP_test_collection: /home/sinclairs/projects/siconos/numerics/src/tools/NumericsMatrix.c:2993: NM_triplet: Assertion `NM_max_version(A) == NSM_version(A->matrix2, NSM_TRIPLET)' failed.
Aborted (core dumped)
```

Beyond this I am a bit lost.  Any help would be appreciated!

cheers, Steve

**Comment by radarsat1** [comment]
To reproduce, put in `Dockerfile`:

```
FROM debian:unstable

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git build-essential cmake libhdf5-dev \
    libsuitesparse-dev libgmp3-dev swig libmumps-seq-dev doxygen graphviz help2man \
    python3-sphinx python3-sphinx-bootstrap-theme python3-sphinxcontrib.bibtex python3-breathe \
    libbullet-dev libboost-graph-dev libboost-filesystem-dev libboost-serialization-dev \
    libboost-timer-dev libboost-chrono-dev liblpsolve55-dev liblapacke-dev libopenblas-dev \
    gfortran libcppunit-dev python3-lxml python3-scipy python3-numpy python3-pytest \
    python3-h5py python3-dev

RUN cd /root && git clone https://github.com/siconos/siconos.git --depth=1
RUN cd /root/siconos && mkdir bld
WORKDIR /root/siconos/bld

RUN cmake .. -DWITH_TESTING=ON -DWITH_PYTHON_WRAPPER=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_MUMPS=ON

WORKDIR /root/siconos/bld/numerics
RUN make -j
RUN ctest -R ConvexQP_test_collection
```

and,
```
docker build -t test1 .
```

Note that I _also_ get the same result if I use,

```
FROM ubuntu:20.04
```

**Comment by bremond** [comment]
Hy!
It can be reproduced on ubuntu 22.04 also. I made a PR #461 (which is only a small part of a very old #396) which adds some check at the start of NM_triplet (and the others).
When the assertion fails, the triplet matrix` is not up to date and it should have been cleared at the start of the function.

Unfortunately, at the moment, I cannot run your `Dockerfile`. ``apt get`` is complaining:

```E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'```

I tried different workaround but without any success.

**Comment by radarsat1** [comment]
The patch seems to work, I am now running a test on the full build.  Thanks @bremond .  Your explanation seems reasonable, I don't know the full implications of modifying NM_triplet so glad this makes sense to you.  ;)

Please also maybe think about the small other problem I noticed, it is just with that function `test_2` however, regarding `cqp.m=10`.  Probably it has no impact, but maybe worth fixing nonetheless.

**Comment by vacary** [comment]
There are still two tests that are working
```
	 55 - fc3d_TEST_NSN_COLLECTION_1 (Failed)
	 56 - fc3d_TEST_NSN_COLLECTION_2 (Subprocess aborted)
```
Those test are intrinsically unstable, ans depends on the accuracy of the computation of linear systems. I propose to set the properties as "expected to fail" when MUMPS is used.

**Comment by radarsat1** [comment]
Fix was merged.
