### ISSUE TITLE
Issue color in siconos_vexport

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#468]
When using `siconos_vexport` with or without global-filter with object with multiple contactor, the cell data are not connected with the shape. Then, it is not possible to colorize objects with cell data in paraview.

The following example show the problem.

[
[test_relative_orientation.tar.gz](https://github.com/siconos/siconos/files/9665873/test_relative_orientation.tar.gz)
](url)

**Comment by bremond** [comment]
With or without ``--global-filter``, the contact shape instance (a number) is associated in ``CellConnector`` (in ``vview.py``). So you can choose it in the coloring box in paraview as this:
![Screenshot from 2022-10-05 16-57-21](https://user-images.githubusercontent.com/5980800/194127185-998bf05f-fd39-4398-9fde-11f854b1db30.png).

When ``--global-filter`` is not specified, I have the coloring of each block (each contact shape) directly:
![Screenshot from 2022-10-05 19-30-58](https://user-images.githubusercontent.com/5980800/194129100-406f8968-cf7e-4e61-88d5-8b314d77d810.png). 

In this case, you can also choose ``instance`` or ``vtkCompositeIndex``

**Comment by vacary** [comment]
Hi @bremond,

If you have a look when `--global-filter` is specified in your first picture, there is two cylinder that stay in blue, whatever the value of the coloring variable you chose. There is a problem with compound objects (objects with multiple contactor shapes). For instance, they should share the same kinetic energy color, but it is not the case.

I attach the same example with only compound objects.

<img width="1704" alt="Captura de Pantalla 2022-10-06 a la(s) 10 16 03" src="https://user-images.githubusercontent.com/3368202/194259287-6d26c37b-547e-4b38-90c6-c079c1fd9fbd.png">

[test_relative_orientation.tar.gz](https://github.com/siconos/siconos/files/9722576/test_relative_orientation.tar.gz)
