### ISSUE TITLE
error "Segmentation fault" while using siconos_vview command in ubuntu 22.04 LTS Linux WSL 2 in Windows 11

### ISSUE THREAD

**Issue by rajkirandhiman** [siconos/siconos#471]
Dear Sir @vacary @radarsat1 @

I want to raise this issue which is concerned with displaying a GUI window using siconos_vview command. 

I run this example rockfall_from_dem.py file present in the siconos-tutorials-master\examples\mechanics\RockFall\  tutorial folder in GitHub.
Simulation is properly run on my system. But in order to see the results i am using siconos_vview command as suggested but getting this error which is attached as error_20-10-2022.txt file.

Earlier i used paraview to visualize the results after exporting it using siconos_vexport command and everything went OK, although i was not able to open dem.asc file in paraview. 

But, since i am working on rockfall modeling i need to randomly generate different convex polyhedron and simulate again and again. So, if i use paraview it is taking a lot of time to export the results and visualize. 

It would be great and easy for me to work if i can visualize the results using siconos_vview command. Kindly help me on this issue.

I saw **this one solution online to render visualization** see this link: https://github.com/Kaggle/docker-python/pull/360
but i don't know where to add **this solution** in the vview.py script. If you can help me using **this solution** that would also be great.

Waiting for your reply soon...

Regards,
Raj Kiran

[error_20-10-2022.txt](https://github.com/siconos/siconos/files/9828865/error_20-10-2022.txt)

**Comment by rajkirandhiman** [comment]
Dear @roccaa @spellizzari @vacary 

I found solution to this problem on this link https://github.com/siconos/siconos/issues/426

and i followed all the steps and i was able to run glxgears command on my linux ubuntu 20.04 LTS WSL 2 on Windows 10 and everything went well i could see the new window with gears. However when i am running siconos_vview command i am getting this error:
rk@DESKTOP-KAJKFD6:/mnt/f/H/RK/Project_Rockfall/tools/siconos-master/siconos-master/siconos-tutorials-master/siconos-tutorials-master/examples/mechanics/RockFall/rockfall_from_dem_simulation$ siconos_vview rockfall_from_dem.hdf5
2022-10-20 17:46:46.296 (   2.164s) [        21A36740]vtkOpenGLRenderWindow.c:517    ERR| vtkXOpenGLRenderWindow (0x2e8d030): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.
[DESKTOP-KAJKFD6:19711] *** Process received signal ***
[DESKTOP-KAJKFD6:19711] Signal: Segmentation fault (11)
[DESKTOP-KAJKFD6:19711] Signal code: Address not mapped (1)
[DESKTOP-KAJKFD6:19711] Failing at address: (nil)
[DESKTOP-KAJKFD6:19711] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f4521c45090]
[DESKTOP-KAJKFD6:19711] *** End of error message ***
Segmentation fault

Kindly help me on this issue

Regards,
Raj

**Comment by bremond** [comment]
Hello @rajkirandhiman ,
with ``glxinfo`` you can check the version of OpenGL, it should be >= 3.2.
If it is not the case, maybe have a look to https://github.com/microsoft/WSL/discussions/6154, they explain how 
to upgrade it (with the ``mesa`` library also).

for example, here is what ``gxlinfo | grep -i opengl`` gives me on an ubuntu 22.04:

OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by rajkirandhiman** [comment]
Hi @bremond thank you for your reply.

I am using ubuntu 20.04 LTS WSL 2 on windows 10. 
i updated the mesa library as per your suggestion https://github.com/microsoft/WSL/discussions/6154

but when i apply glxinfo | grep -i opengl command i get:

**OpenGL vendor string: Mesa/X.org
OpenGL renderer string: softpipe
OpenGL version string: 1.4 (3.3 (Compatibility Profile) Mesa 22.0.0-devel (git-7aab7ccd36))
OpenGL extensions:**

Can you help on this issue ??

**Comment by rajkirandhiman** [comment]
Dear @bremond 

I have NVIDIA Quadro P2200 5GB GPU installed on my system but  using command **glxinfo | grep -i opengl** I am not able to see this GPU on screen AS your comment also shows **OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)** graphic card, similarly my ubuntu system must show my NVIDIA card but its not the case.

**Comment by rajkirandhiman** [comment]
Dear All,

I have updated windows from 10 to 11 and followed this link https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps to install NVIDIA graphics and updated my WSL.

siconos_vview command is working now.

Thanks.
