### ISSUE TITLE
How to turn off _warnOnNonConvergence flag ?

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#479]
Hi,

Siconos is now widely used by PlatRock users on the Inrae server, that's great ! I'm however facing a small issue with logs : I get plenty of [this](https://github.com/siconos/siconos/blob/77e0d07aa3d7d0601e5de2508dbbfededa430e65/kernel/src/simulationTools/TimeStepping.cpp#L492) warning, resulting in gigas of syslog on the server. Two questions arises:

- how can I disable the `_warnOnNonConvergence` flag in the context of Python / mechanicsHdf5Runner usage ? (to make a parallel, the context is similar for instance to this [script](https://github.com/siconos/siconos-tutorials/blob/master/examples/mechanics/RollingFriction/sphere.py)) ;
- secondly, should I consider to fix this warning, or should I consider it as a normal one ?

Thanks,
François

**Comment by vacary** [comment]
I added flag in run_options to disable warning in [b05ff13](https://github.com/siconos/siconos/commit/b05ff137803e30b81863e57aa333365587cd02df).

This warning informs you that the tolerance you asked is not reached.

**Comment by batzkass** [comment]
Thanks, I'll give it a try.

**Comment by vacary** [comment]
To use it:
```
run_options['Newton_warning_on_nonconvergence']=False
run_options['Warning_nonsmooth_solver']=False
```
