### ISSUE TITLE
[Kernel] fix bad casting in OneStepNSProblem::getOSIMatrix

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#48]
This line of code

block = (std11::static_pointer_cast<MoreauJeanOSI> (Osi))->W(ds); // get its W matrix ( pointer link!)

is also executed for SchatzmanPaoliOSI, which is not based on MoreauJeanOSI.

The real fix is to remove the W matrix from the OSI and put it in the graph.

**Comment by vacary** [comment]
The correction of this issue on the track. When the DynamicalSystemsSet will be completely removed, I will start to migrate stuff on the Graph of DS.

**Comment by vacary** [comment]
fixed in 5f5e2fb9cca721baca4ab2e06e490b3b82f10667
