### ISSUE TITLE
Reproducible Mechanics simulation

### ISSUE THREAD

**Issue by batzkass** [siconos/siconos#486]
Hi,
Is there a way to force siconos (bullet ?) to make reproducible simulations for debug purpose ? As far as I understood, contact detection through bullet may introduce some randomization. So I'm looking for a random generator seed or something of that kind.
Thanks !

**Comment by vacary** [comment]
Hi,
It depends on what you mean by reproducible simulation. In fact, there's no explicit randomness in siconos and bullet. You won't find any random functions, even less seeds. For a given machine and a given script, the calculations must be reproducible.

On the other hand, there is a contact point sorting algorithm in Bullet which depends on the order of the objects in memory and which sorts them using distance criteria and inequalities on the surface area. For this algorithm, it's very hard to get control and a different calculation precision can lead to different results.

**Comment by batzkass** [comment]
That's nice, thanks for your answer.
