### ISSUE TITLE
LGPL code in kernel/src/utils/SiconosAlgebra/cholesky.hpp

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#49]
This is used to provide a factorisation method for sparse matrices in SimpleMatrix::PLUFactorizationInPlace

The best course of action is to remove that code and replace it by something that also works for unsymmetric matrix.

We are already developing a nice wrapper around multiple LU library in numerics. We should leverage that and use it also in the kernel. Otherwise we are maintaining 2 linear algebra front-end in the same software. And I don't think it makes sense.

**Comment by vacary** [comment]
I do not agree. SimpleMatrix::PLUFactorizationInPlace is perfect for LU factorize small symmetric matrices (mass matrices of small systems). There is no interest to call for other HPC solvers.

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2016-03-27 14:51:56 -0700]:

> I do not agree. SimpleMatrix::PLUFactorizationInPlace is perfect for LU factorize small symmetric matrices (mass matrices of small systems). There is no interest to call for other HPC solvers.

I thought that PLU meant LU with permutation not Cholesky. And this belief is consistent with the documentation.

I agree that using Cholesky for symmetric matrices of any size, regardless of the storage type. But then it has to be in a function called CholeskyFactorizationInPlace not PLUFactorizationInPlace. And the code I mentioned was only use in the sparse case, not the dense one. So for all examples but 2 (ImpactBar et co, where the matrices are also banded btw), we perform a LU factorization instead of a Cholesky one on the dense mass matrix. So I don't think the current implementation is perfect.
Right now, nothing states that this function is only for symmetric matrices in the sparse case. Also it is quite wrong in assuming that the matrix is sparse if num is not 1.

And I was nowhere advocating for HPC solvers, just robust implementations, instead of a naive one, with no stability guarantee and which is very likely to give poor sparse factorization with medium+ size problem in terms of density.
Also I wrote the comment about changing it to use NumericsMatrix because of this comment: ``warning: VA 24/11/2010: work only for symmetric matrices. Should be replaced by efficient implementatation (e.g. mumps )'' in SimpleMatrixSolvers.cpp
Is this comment still up-to-date?

Furthermore, no later than 2 weeks ago we were taking about system with non-symmetric matrices and of moderate sizes. I know we are not there, but if we are already changing things, why should we refrain from making changes that would allow ease thw work if we do it in the future?



Still I don't see how our comment address the license problem, which is a real blocker for the license change. One way to move forward is to rely on the code from other component. It would work fine with all backends, except for the where we want to solve sparse rhs (like matrices). But by looking at the CSparse code it would be easy to do. For UMFPACK, it looks way more complex. MUMPS support this case. We could use Cparse for small instances and have a threshold for using something else for larger ones.

Note that Cpsarse has routines to perform Cholesky factorization and solves and both UMFPACK and MUMPS can take advantage of the fact that the matrix to factorize is symmetric.

In the vector case, this in not an issue.There is this line in SimpleMatrixSolvers.cpp, SimpleMatrix::PLUForwardBackwardInPlace(SiconosVector &B):
ublas::column(tmpB, 0) = *(B.dense()); // Conversion of vector to matrix. Temporary solution.

so no loss here, we can only do better.



I'm fine with moving forward with another solution, as long as it is sound.

**Comment by vacary** [comment]
Thank you @xhub . The code has been moved in externals under LGPL licence.
