### ISSUE TITLE
How to turn on openMP in SICONOS ?

### ISSUE THREAD

**Issue by rajkirandhiman** [siconos/siconos#495]
Dear Sir,
I am working in rockfall propagation modelling. I am running a simulation for 120 s with dt = 1e-4 which results in 1200000 time steps. 
I am using HP Z6 workstation with 16 cores and 128 GB RAM. It is taking more than 24 hours to complete the simulation. 

I want to use openMP within SICONOS. Is it possible as i could see on this link https://github.com/siconos/siconos/blob/master/config.h.cmake

I have already installed openMP in ubuntu 22.04 using command 
sudo apt-get install libomp-dev

do i need to re-install SICONOS ?

can you let me know the procedure to run open MPI on SICONOS. 

Regards,
Raj

**Comment by vacary** [comment]
Dear Raj,

Unfortunately, in your case, the openMP will not help. I am a bit surprised by your time of simulation.  Perhaps, we can save time with some build-in optimization.

Could you share a script with me?  

Best
