### ISSUE TITLE
umfpack_dl_report_matrix reports out of order entries when it is called from NM_gesv

### ISSUE THREAD

**Issue by octave-user** [siconos/siconos#496]
Dear Siconos team,

It seems that the CSC format generated by CXSparse is not always suitable for Umfpack, whereas it is valid for CSparse.

For example, the following code works as expected, but if Umfpack is used instead of CSparse, then NM_gesv fails due to an invalid CSC format.
```
     NM_setSparseSolver(A, NSM_CSPARSE);

     NM_gesv(A, x, true);
```

If `umfpack_dl_report_matrix` is called from `NM_UMFPACK_factorize`, then I get the following output:

```
umfpack_dl_report_matrix(n_row,n_col,Ap,Ai,Ax,1,Control)

column-form matrix, n_row 850 n_col 850, nz = 21062. 

    column 0: start: 0 end: 58 entries: 59
	row 11 : (1.0472)
	row 10 : (0) ERROR: row index 10 out of order (or duplicate) in column 0
```
When I print the CSC matrix, then I can see that there are duplicate entries in Ai:
```
Ap=[ 0,
      59,
     118,
     177,
     234,
     ...

Ai=[11,
      10,
      11,
      10,
       9,
       8,
      ...
```
The matrix was assembled using `NM_entry` and `NM_triplet_alloc` was called before.

You can find the whole code here:
https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/dd54bd91de327037f6910489a12a46cff83a584c/libraries/libmbwrap/siconoswrap.cc
and there:
https://public.gitlab.polimi.it/DAER/mbdyn/-/blob/dd54bd91de327037f6910489a12a46cff83a584c/libraries/libmbmath/siconosmh.cc

Probably the issue could be fixed if `umfpack_dl_triplet_to_col` would be used in order to convert the triplet format to CSC format.

Best regards,
Reinhard

**Comment by vacary** [comment]
Thank you very much for pointing this issue together with the fix. 
Our CI is only testing cxsparse and Mumps so we never found this bug. Again your work is of great help. 

I will merge you fix into our Devel repo which is here https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos and it will be mirrored on GitHub.

**Comment by vacary** [comment]
It looks like you're on the right track for wrapping siconos/numerics in MBDyn. This is really a great initiative. What is your ultimate goal? I guess it's not just our interfaces to UMFPACK and MUMPS. 

A decade ago, Pierangelo and I attempted a coupling with Siconos for flexible multibody systems with impact.

Integrating the Siconos/numerics friction contact solvers into MBDyn would be fantastic. We have a lot of multi-body applications and we decided to write a module siconos/mechanisms  to simulate them because we didn't have the resources to develop them in MBDyn. For us, it was a temporary solution that has now become permanent. The idea for us to use MBdyn would be perfect. To do this, we need access to the Siconos/numerics solvers, but we also need to adapt the MBDyn time integrators to implement Moreau Jean-type schemes.

To be continued

**Comment by xhub** [comment]
We have `NSM_fix_csc`  to fix ordering. Duplicate entries yield an incorrect input matrix. It seems better to fix this before calling `NM_gesv`?

**Comment by octave-user** [comment]
> It looks like you're on the right track for wrapping siconos/numerics in MBDyn. This is really a great initiative. What is your ultimate goal? I guess it's not just our interfaces to UMFPACK and MUMPS.
> 
> A decade ago, Pierangelo and I attempted a coupling with Siconos for flexible multibody systems with impact.
> 
> Integrating the Siconos/numerics friction contact solvers into MBDyn would be fantastic. We have a lot of multi-body applications and we decided to write a module siconos/mechanisms to simulate them because we didn't have the resources to develop them in MBDyn. For us, it was a temporary solution that has now become permanent. The idea for us to use MBdyn would be perfect. To do this, we need access to the Siconos/numerics solvers, but we also need to adapt the MBDyn time integrators to implement Moreau Jean-type schemes.
> 
> To be continued

Well, at the beginning the idea was just to implement a robust mass conserving cavitation model for hydrodynamic lubricated bearings. In the meantime also a few models for unilateral contact may use the Newton Fischer Burmeister solvers. Unfortunately, the only time step integrator which is able to handle hard unilateral contact in MBDyn is Implicit Euler. In addition to that, it might be very difficult to implement More Jean-type integration schemes for all multi-step and multi-stage methods.

Nevertheless, unilateral contact and friction between a flexible solid body and a rigid body is already working. See this video for example:
[Rolling ring made of hyperelastic material subject to large deformations, contact and friction](https://www.youtube.com/watch?v=rxQP8V4U0dE)

**Comment by vacary** [comment]
Thank you for your answer.  very nice movie. We should have a look to your code.

I merge your PR #497. Thank you again.
