### ISSUE TITLE
LGPL code in externals/tools/f2c.h

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#51]
This files is included in
- many files in externals/netlib/dctemplates/ this is not an issue since we release this part under the LGPL
- io/src/SiconosFull.hpp
- kernel/src/SiconosFwd.hpp
- kernel/src/simulationTools/EventDriven.hpp
- kernel/src/simulationTools/LsodarOSI.hpp

It is included in SiconosFortran.h, which is itself included in
- hairer.h
- odepack.h
- QP_Solvers.h

and so on, so forth.

Note that there are 5 (yikes) f2c.h files in the siconos repository:
./externals/netlib/dctemplates/F2CLIBS/libF77/f2c.h
./externals/netlib/dctemplates/F2CLIBS/libI77/f2c.h
./externals/netlib/dctemplates/F2CLIBS/f2c.h
./externals/netlib/dctemplates/f2c.h
./externals/tools/f2c.h

**Comment by vacary** [comment]
Where/what  is the problem ?

 fc2.h is in externals and it only included and not modified in the code. What do you want to do ? you want to add a fake siconos_f2c.h that only include fc2.h in order to separate more the code from LGPL code?

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2016-03-27 14:48:38 -0700]:

> Where/what  is the problem ?

A trivial one is that we have 5 files with the same name. And they are quite different, like at least 2 of them define ``integer'' in a different way and incompatible way. Also can you tell which one gets installed without running ``make install''?
Also which one is used outside externals? So yeah after loosing 15 mins, I can see that externals/netlib/dctemplates is referenced nowhere.

>  fc2.h is in externals and it only included and not modified in the code. What do you want to do ? you want to add a fake siconos_f2c.h that only include fc2.h in order to separate more the code from LGPL code?

Well, this header is not part of any API it is just supposed to be data. It just feels strange and unusual since there is no library involved here. By reading the LGPL, it looks fine if I understand the paragraph 5 of the LGPLv2, but still it is strange reading this when  there is nothing behind the term «the Library».

We don't link to libf2c as far as I can tell. So just a few random questions:
- why do we need 5 times the same file, 4 times the same one and 2 different and incompatible versions? A related question is why is dctemplates in the sources at all?
- why is it any better than using the f2c.h from netlib, which is under a MIT-style license?


Ideally I would get rid of this f2c.h version and use the netlib one and delete dctemplates if there is no use of it.
