### ISSUE TITLE
Boost Log

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#55]
Would it be interesting to use [Boost log](http://www.boost.org/doc/libs/1_56_0/libs/log/doc/html/index.html) for a smart logging system ?

However, it seems that compilation with Boost log is not trivial. 

To be discussed

**Comment by xhub** [comment]
Would that be for the cpp code (kernel, mechanics, ...) or also for numerics?

Would it be better to have a more programmatic logging capability, like storing information in an hdf5?
To me, it is then easier to post-process the information in a programmatic way rather than parsing a log file.

**Comment by vacary** [comment]
I close this issue since @xhub started a log procedure in hdf5
