### ISSUE TITLE
[kernel] remove LagrangianDS::_workMatrix

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#57]
All is in the title.

Remove and transfer it if necessary to the DS Graph.

**Comment by vacary** [comment]
Lagrangian::massLU() should also be suppressed.

**Comment by vacary** [comment]
Done at least for LagrangianDS::massLU()

**Comment by vacary** [comment]
@xhub : should I start this work, if you have a work with subsequent work that goes in that direction ?

**Comment by xhub** [comment]
I haven't work on the LagrangianDS::_workMatrix. I worked on the memory vectors. I will try this week to polish that and fix the bug with SchatzmannPaoliOSI and push it on master

**Comment by vacary** [comment]
Ok, i will let working the Professional ;_0
