### ISSUE TITLE
siconos/mechanics/swig/mechanics/collision is missing

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#64]
It seems that since (1c4a7f343fa2643640174e6078fe90f52cc44d92),  the directory
siconos/mechanics/swig/mechanics/collision
is missing for the compilation.

**Comment by radarsat1** [comment]
Oh no, I tried to be so careful. Is it possible I did a "mv" instead of "git mv"? I'm afraid I left my computer at work, can't check it until monday! I have a mac here that I can maybe I install xcode, I'll see what I can do

**Comment by radarsat1** [comment]
Reverted mechanics/swig, can you test?

**Comment by vacary** [comment]
No stress. Let us fix that on monday after the coffee :-)

**Comment by radarsat1** [comment]
Reverted in 3f0ab095ab
