### ISSUE TITLE
[io] Dynamic management of objects in mechanics_io.py

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#66]
In the mechanics_io (hdf5) interface, it would be great to be able to fully use the capacity of Siconos/Mechanics to be highly dynamic from the point of view of the creation and destruction of bodies

Especially, if an object is created on the fly by addObject and add__Shape calls, it should be possible to use importObject  to include it into the simulation also on the fly. We have also to deal with bodies that already have an history

In the same spirit, a exitScene() should be implemented to remove (possibly temporarily) an object from the simulation scene.

Should we rename the function importScene(), enterScene()

**Comment by radarsat1** [comment]
Currently, when you run a simulation Python script, if there is already a simulation it is wiped clean, and the new simulation is written to the file.  You may also explicitly split creation of the scene and running the scene, as seen with `cube_scene.py` and `cube_simulation.py`.

This is good, but I want to discuss desired behaviour when a simulation already exists, is completed or empty, or is partially completed.  I'll do this with a series of questions:

When an already-complete simulation is found, should the program,

1. ask the user whether to erase it
2. just announce that it is complete, and exit.  User must manually delete the file.  Provide an "overwrite" command-line flag. (e.g. `--force`)
3. just go ahead and erase it

When a partially-completed simulation is found, should the program.

1. continue the simulation until `T`.
2. continue the simulation until `t+T`, where `t` is the last time simulated.  (current behaviour!)
3. continue the simulation until `t-h+T`, ie. disregard the last timestep assuming it may have been partially completed

A new feature should also be to be able to specify a time at which to continue the simulation, explicitly removing everything after a given time.  I am currently working on this.

Ideally, personally, I think it would be nice not to have two files like this, but rather define and execute the simulation from the same file.  Or have the simulation scripts only define simulations, but not automatically clear the data, and have a standard separate command for running the simulations.  (E.g. there is nothing really simulation-specific in `cube_simulation.py`, so we could make that an installed command perhaps?)

A problem with the above proposal is if you want to add a callback for adding forces or adding objects into the scene at certain steps or doing other things that manipulate the simulation while it is running.
We could just make it a standard practice to always make a dedicated "execution script" if that kind of thing is desired, or provide a way to specify a script name to load containing callback, and save this in the hdf5 file.

Another issue, how to ensure consistency between the simulation (only initialized, or partially completed..) and what has been defined?

These are some cases that I can think of, add your own if you think of more:

1. Simulation is defined, file contains identical simulation, check that simulation is completed, exit.
2. Simulation is defined, file contains identical simulation, change `T` and keep running it.
3. Simulation is not defined, but loaded from file, but change `T` and keep running it.
4. Simulation is defined, contains same  simulation plus more objects, with time of birth after the last time of the file.  Keep running it.  (Change `T`)
5. Simulation is loaded, more objects are added with time of birth after last time of the file.  Keep running it.  (Change `T`)
6. Simulation is loaded, more objects are added without time of birth, need to restart the simulation.
7. Simulation is loaded, more objects are added with time of birth at `t1`, rewind simulation to `t1` and run to `T`.

It seems to me that it should be possible to check if simulation definition is the same as that saved in the HDF5 file, disregarding positions.  Is it necessary to do this?  It comes down to two sets:

1. Defined simulation and file contain the same objects (shapes are the same)
2. Defined simulation contains all objects defined in the file
3. File contains some objects not in the simulation (error condition?)
4. File contains only objects that are not in the simulation (assume they are added at last time)

-----------

Okay on further thought, to keep things simple I think the behaviour should be left as it is currently, perhaps adding a warning if the file is going to be overwritten.

Along with this we can add a way for something like `cube_simulation.py` to restart the simulation extending `T` or changing `t0` to a later time, and it should do what is expected.  It should "finish" a partially completed simulation, and do nothing for a completed simulation.  This can be a standard script that takes the HDF5 filename as argument.  I propose the name `siconos_run`, or we can extend the existing `siconos` script.

We should then add a way to add objects to an already-initialized scene before executing `run`.  This should be a fairly straightforward extension of `cube_simulation.py`.  It should be assumed that new objects have time of birth after previous `T`, but it should require that a new `T` be given.

An alternative could be to have a way to import another simulation entirely into the current simulation.  It could be possible to load these "sub-simulations" as they are, perhaps just the last frame, and then run it from there.

**Comment by radarsat1** [comment]
With the time_of_birth feature can we close this bug?  Should we think about time_of_death as well?  (I think actually position_of_death would be useful!)

**Comment by vacary** [comment]
I think we can close it, but all the above points have been discussed and fixed ?

**Comment by radarsat1** [comment]
It has been a while, so I will review this points.  I think this issue should be closed and dedicated issues should be created as wish-list items.  Probably they will be added as-needed on a future project.

1. Add new items to an existing simulation before calling run()
2. Way to merge / import sub-simulations (eg. a pile of rocks into different chute structures, or importing vehicles into some terrain world..)
3. time_of_death / position_of_death

Otherwise, time_of_birth added by @bremond and siconos_run added by me (and siconos_info for checking `T`) handle all the main concerns here I think.  Further, I observe that the following controller can be added to a running simulation, which adds a new object to the HDF5 on the fly at a certain time:

~~~
class Ctrl(object):
    def initialize(self, io):
        self.io = io
        self.model = io._model
        self.added = False

    def step(self):
        t = self.model.simulation().nextTime()
        if t >= 5 and not self.added:
            self.added = True
            print('Adding an object..')
            self.io._number_of_dynamic_objects = 2
            self.io.addObject('cube', [Contactor('Cube')], mass=1.0,
                              translation=[0, 0, 7],
                              time_of_birth=t)
            self.io.importBulletObject(
                'cube', translation=[0,0,7], orientation=[1,0,0,0],
                velocity=[0,0,0,0,0,0], contactors=[Contactor('Cube')],
                mass=1.0, inertia=None, body_class=BodyDS, shape_class=None,
                birth=t, number=self.io._number_of_dynamic_objects)
~~~

This could be developed into a dynamic addImportObject() function for example.. do you think it's interesting to do so?  The only reason would be to be able to program dynamic objects to be added to the scene in reaction to current conditions.

**Comment by radarsat1** [comment]
Since last looking at this bug, time_of_death has been implemented, not position_of_death, but objects flying out of the screen generally do not take much computational resources, and I showed in the last comment that some clever things can be done in the controller callback if necessary to create objects on the fly.  I vote to close until such time that this is needed in a real application, otherwise API design choices regarding these issues will be very tentative anyways.

**Comment by vacary** [comment]
I agree
