### ISSUE TITLE
backport fixes to 4.0.x

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#67]
- PrismaticJointR::computeDotJachq, cf https://copr-be.cloud.fedoraproject.org/results/xhub/siconos-git/fedora-24-x86_64/00342234-siconos/build.log.gz
- Fix for isfinite being called on integer

**Comment by vacary** [comment]
I think that Steve has fixed the first bug in (7220392e25e3309d792fd97fce2ce8e2e01376f3). I will do the cherry-pick

**Comment by vacary** [comment]
This should be ok  for  (7220392e25e3309d792fd97fce2ce8e2e01376f3) and (fcb649e608b07eda740dff159222a86535b79ea0)
