### ISSUE TITLE
Python interface tests in build tree

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#69]
There is a bug in build-tree for swig-generated python interface.
This occurs for all .i files where  "%import kernel.i" is called (in control and mbtb for the time being)
leading to a .py generated file with "import kernel".

To observe it, in build tree, try:

cd wrap
python -c 'import siconos.kernel as sk; print sk.**file**'
--> siconos/kernel.pyc
which is ok
but:
python -c 'import siconos.control as sc; print sc.**file**'
either it returns the installed version of swig generated libraries (if any) or:
File "siconos/control/controller.py", line 377, in <module>
    import kernel
ImportError: No module named kernel

Both are wrong, since we must not use installed version in build tree.

**Comment by radarsat1** [comment]
Ah, I noticed something like that the other day, but could not figure out what caused it.  Good!

**Comment by radarsat1** [comment]
Just tested this, it seems to be fixed. Close?

**Comment by xhub** [comment]
@fperignon do you still see this issue?

**Comment by radarsat1** [comment]
I'm not sure in what commit it was fixed, but on current master in my build dir,
~~~
$ python -c 'import siconos.control as sc; print sc.__file__'
siconos/control/__init__.py
~~~
So I will close.  @fperignon please re-open if you see the issue still.

I hit on #149 while testing this, but it's a separate issue.
