### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#7]
Need to update almost all files.

**Comment by vacary** [comment]
Just an update of this issue, are we ready to change to LGPL ?

**Comment by vacary** [comment]
Why not Apache 2.0 rather LGPL ?

**Comment by xhub** [comment]
So a list of items to do before changing the license:
- Move all the code derived from csparse to externals/SuiteSparse/CSparse/ under the name csparse_extentions. There is for sure things in numerics/src/tools/SparseMatrix.c
- Document the license of siconos-externals being LGPLv2.1+ Make sure that this is true. ODEPACK is public domain, HEM5 looks BSD, but there is MA28 included and should be used for research only, see linsp.f. Document this. See also #33
- do a review of the code in numerics to look for code that could come from csparse. I think that apart from the part in numerics/src/tools/SparseMatrix.c that I introduce, we are fine.

**Comment by vacary** [comment]
@xhub : "Move all the code derived from csparse to externals/SuiteSparse/CSparse/ under the name csparse_extentions. There is for sure things in numerics/src/tools/SparseMatrix.c" 

How do you want to do it in practice. We can make a move of numerics/src/tools/SparseMatrix.c[.h] in  externals/SuiteSparse/CSparse_extensions but why it will solve the problem in a proper way ? 
what is the goal: to remove all the file that need a direct include of csparse.h ?

I will do that in brute force way and see how we can try to do better

**Comment by vacary** [comment]
I commented the commit (https://github.com/siconos/siconos/commit/d6fdf1aa254e01472bdf56f5f36ff75a5c1b44cb) it is just a  first start

**Comment by xhub** [comment]
* Vincent Acary <notifications@github.com> [2016-03-22 12:58:35 -0700]:

> @xhub : "Move all the code derived from csparse to externals/SuiteSparse/CSparse/ under the name csparse_extentions. There is for sure things in numerics/src/tools/SparseMatrix.c" 
> 
> How do you want to do it in practice. We can make a move of numerics/src/tools/SparseMatrix.c[.h] in  externals/SuiteSparse/CSparse_extensions but why it will solve the problem in a proper way ? 
> what is the goal: to remove all the file that need a direct include of csparse.h ?

The goal was to remove every piece of code that was derived from CSparse because it would infringe for sure the LGPL.  I was sure that this was the case for half of SparseMatrix.

Now just using the data structure and calling the functions is fine.

By looking quickly at the code, it looks like it is the only place where CSparse source code was used.

To nitpick, I think this test: numerics/src/tools/test/SparseMatrix_test0.c should belong to the external dir, or be removed, but just because it does make sense to have it in numerics

**Comment by vacary** [comment]
nitpick ? Have a translation for french dummies ?
Normally, we also have to specify our modification/extension in a notice file ? I am right ?

**Comment by radarsat1** [comment]
nitpick = pointing out very small, sometimes unimportant, details :)

**Comment by bremond** [comment]
GPL -> Apache done in 4.0 & master
