### ISSUE TITLE
Mechanisms tests

### ISSUE THREAD

**Issue by fperignon** [siconos/siconos#70]
Siconos Mechanisms tests use "siconos -P siconos_mechanisms.py"
to execute, meaning a call to an installed version of siconos, which is obviously a bad thing ...

**Comment by vacary** [comment]
Normally, you have to use siconos_mechanisms script. 
It is forbidden to use an installed python script ? 
You can also call the python script that is in your build directory
Could you explain a little bit more ? 
Cheers

**Comment by fperignon** [comment]
I think that when you run tests, you must rely only on the version you just build, not on an
previously installed version.  As you said it's just a question of calling the script in the build dir. I'll commit something that fix that, but it still depends on #69 fix.

**Comment by vacary** [comment]
Ok, I didn't understand  that it was for running tests. It is difficult for me this morning !!
Fully agree with you. We need to rely on script in the build directory.
