### ISSUE TITLE
Errors in blas-using code with gcc-6, need -flax-vector-conversions

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#71]
I get errors in blas-using code (e.g. SOL) when compiling with gcc-6.1.0 on Homebrew, e.g.:

    In file included from /Users/sinclairs/.local/Cellar/gcc/6.1.0/lib/gcc/6/gcc/x86_64-apple-darwin15.2.0/6.1.0/include/xmmintrin.h:1249:0,
                     from /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vecLibTypes.h:91,
                     from /System/Library/Frameworks/Accelerate.framework/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h:21,
                     from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                     from /Users/sinclairs/projects/siconos/externals/blas_lapack/SiconosBlas.h:44,
                     from /Users/sinclairs/projects/siconos/externals/SOL/lumod-c/lumod_dense.c:8:
    /Users/sinclairs/.local/Cellar/gcc/6.1.0/lib/gcc/6/gcc/x86_64-apple-darwin15.2.0/6.1.0/include/emmintrin.h:1262:1: note: expected '__m128i {aka __vector(2) long long int}' but argument is of type 'vUInt32 {aka __vector(4) unsigned int}'
     _mm_srl_epi64 (__m128i __A, __m128i __B)
     ^~~~~~~~~~~~~
    In file included from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20:0,
                     from /Users/sinclairs/projects/siconos/externals/blas_lapack/SiconosBlas.h:44,
                     from /Users/sinclairs/projects/siconos/externals/SOL/lumod-c/lumod_dense.c:8:
    /System/Library/Frameworks/Accelerate.framework/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h: At top level:
    /System/Library/Frameworks/Accelerate.framework/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h:26:0: warning: subframework include vecLib/vBigNum.h conflicts with framework include
     #endif

The solution seems to be to tell GCC to allow such type conversions by setting `CMAKE_C_FLAGS=-flax-vector-conversions`

**Comment by radarsat1** [comment]
(Note, that solves the compilation error, but doesn't get rid of the warnings about "subframework include conflicts"..)

**Comment by xhub** [comment]
This is a known issue with the latest BLAS-Accelerate on Darwin. I believe that even with gcc 4.9 it does not work without adding the extra flag.

For me the fix is to use clang on Darwin. I'm not sure we want to explicitly support compiling with gcc on recent version of OS X.

**Comment by radarsat1** [comment]
Fair enough, in any case it's just one flag to add if we change our minds.  In the meantime it is documented here.
