### ISSUE TITLE
normq error after loading mesh

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#72]
[stl-cube.zip](https://github.com/siconos/siconos/files/321235/stl-cube.zip)

I did a quick test to see if I could include an STL mesh in a simulation, and it didn't work.  I fixed mechanics_io.py to the best of my knowledge, in be1a79bc7988460be9b56c19f2701c3d384fdde8, but I still get a run-time assertion when I run it.

Attached `cube.stl` (in `stl-cube.zip`) was generated using Blender, but ultimately I want to load an STL that was generated using SolidWorks.

    $ python stl-cube.py 
    self._collision_margin 0.04
    self._collision_margin 0.04
    step 1 < 2000
    python: /home/sinclairs/projects/siconos/kernel/src/modelingTools/NewtonEulerDS.cpp:257: void normalizeq(SP::SiconosVector): Assertion `normq > 0' failed.
    Aborted (core dumped)

The script is,

    #!/usr/bin/env python
    from siconos.mechanics.contact_detection.tools import Contactor
    from siconos.io.mechanics_io import Hdf5
    import siconos.numerics as Numerics
    with Hdf5() as io:
        io.addMeshFromFile('CubeStl', 'cube.stl')
        io.addObject('cube', [Contactor('CubeStl')], translation=[0, 0, 4],
                     velocity=[0,0,0,0,0,0], mass=1)
    with Hdf5(mode='r+') as io:
        io.run(t0=0,
                T=10,
                h=0.005,
                multipoints_iterations=True,
                theta=0.50001,
                Newton_max_iter=20,
                solver=Numerics.SICONOS_FRICTION_3D_NSGS,
                itermax=100000,
                tolerance=1e-8,
                numerics_verbose=False)

I haven't tried to debug yet with gdb, but last time I got this normq assertion it turned out to be something very deep, so I thought it worth posting.

**Comment by vacary** [comment]
I will have a look but I am pretty that the quaternion is not correctly initialize in the obscure https://github.com/siconos/siconos/blob/master/mechanics/swig/mechanics/contact_detection/tools.py

For mesh, nothing is called for initialize.
