### ISSUE TITLE
remove or fix AppVeyor

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#82]
The fact that all builds fail on AppVeyor sort of spoils the pull request view on github.  Can we either fix it or remove it?  I think it's sort of redundant to Travis, no?

**Comment by xhub** [comment]
Appveyor is for windows only, whereas Travis works only on Linux. So it's complementary to Travis.

Honestly, I won't have time to fix it before the fall. I think that it would be a big plus to have it working and generate windows binaries. I propose we disable it for the time being.

If someone wants to fix it, feel free to do so.

**Comment by radarsat1** [comment]
Ok, agreed.  Could be useful in the future then, I guess.  I think disabling might be nice for now.

**Comment by xhub** [comment]
I disabled the hook. Let's see if it works.

**Comment by radarsat1** [comment]
Seems good now, thanks!
