### ISSUE TITLE
Warning dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#87]
On [cdash](https://cdash-bipop.inrialpes.fr/viewBuildError.php?type=1&buildid=22691), we have a lot of warning due a dereferencing of pointer mainly that come from the code in 
[solverOptions.i](https://github.com/siconos/siconos/blob/master/wrap/swig/solverOptions.i)

```
warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
      ((PyObject*)(op))->ob_refcnt++)
                      ^
```

I do not know if it is importan but at the same time, I experienced some bus error on very long and huge computations. Some comments on the web are  worrying  as in 
http://stackoverflow.com/questions/98650/what-is-the-strict-aliasing-rule

any idea ?

**Comment by bremond** [comment]
Seems like it is not our fault here ...

cf
http://legacy.python.org/dev/peps/pep-3123/

"Historically, compilers did not have any problems with this code. However, modern compilers use that clause as an optimization opportunity, finding that f->ob_refcnt and o->ob_refcnt cannot possibly refer to the same memory, and that therefore the function should return 0, without having to fetch the value of ob_refcnt at all in the return statement. For GCC, Python now uses -fno-strict-aliasing to work around that problem; with other compilers, it may just see undefined behavior. Even with GCC, using -fno-strict-aliasing may pessimize the generated code unnecessarily."


It should be ok with Python 3 now .

http://bugs.python.org/issue3326

If this is correct we should use '-fno-strict-aliasing' for python 2.7.x
bindings

**Comment by vacary** [comment]
ok, thanks Maurice.
I will add -fno-strict-aliasing in the compiler flags of the python wrapper

**Comment by radarsat1** [comment]
This was done in 3a90a852cf1751f07cac7168bc46587c49c18786.  Close?
