### ISSUE TITLE
build failed when with_serialization=ON

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#89]
Regenerating SiconosFullGenerated.hpp may do the trick.

Error here: http://cdash-bipop.inrialpes.fr/viewBuildError.php?buildid=22939

**Comment by radarsat1** [comment]
Just got back from conferencing, ready to fix these.. but I see you went ahead and got it working.  :) Close?

**Comment by xhub** [comment]
It's not working OOTB:

- The order of the include statements needs to be fixed. I had to move those 4 to the end:

#include "SiconosKernel.hpp"
#include "FirstOrderNonLinearDS.hpp"
#include "FirstOrderLinearDS.hpp"
#include "SiconosControl.hpp"

  They were already at the end in the file, but the script put them first.

- I had to manually add SICONOS_IO_REGISTER(InteractionManager::NSLawMatrix,)

- I manually edited SiconosFullKernelGenerated.hpp I don't know if it can be reliably generated. But at least there is an issue with InteractionManager::NSLawMatrix

Maybe there is some other issues that I don't remember.

**Comment by radarsat1** [comment]
Ok, job for tomorrow then, I'll look at the diff and try to make it generate the parts you had to change manually.  Thanks!
