### ISSUE TITLE
GPL licensed files in master

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#90]
# git grep -l 'GNU General Public License' | grep -v example 
Changelog
kernel/src/simulationTools/InteractionManager.hpp
mechanics/src/collision/BodyDS.hpp
mechanics/src/collision/SiconosCollisionManager.hpp
mechanics/src/collision/SiconosContactor.hpp
mechanics/src/collision/SiconosShape.hpp
mechanics/src/collision/bullet/SiconosBulletCollisionManager.cpp
mechanics/src/collision/bullet/SiconosBulletCollisionManager.hpp
mechanics/src/collision/bullet/test/ContactTest.hpp

It may be the result of the merge of the mechanics-proposed branch

**Comment by radarsat1** [comment]
Yeah good catch, must have copied & pasted from before it was all changed.  I'll fix that.

**Comment by vacary** [comment]
Could we close ?

**Comment by xhub** [comment]
This is not fixed (Changelog is fine):
git grep -l 'GNU General Public License' | grep -v example                                                                                                                                         
Changelog                                                                                                                                                                                                         
kernel/src/simulationTools/InteractionManager.hpp                                                                                                                                                                 
mechanics/src/collision/BodyDS.hpp                                                                                                                                                                                
mechanics/src/collision/SiconosCollisionManager.hpp                                                                                                                                                               
mechanics/src/collision/SiconosContactor.hpp                                                                                                                                                                      
mechanics/src/collision/SiconosShape.hpp
mechanics/src/collision/bullet/SiconosBulletCollisionManager.cpp
mechanics/src/collision/bullet/SiconosBulletCollisionManager.hpp
mechanics/src/collision/bullet/test/ContactTest.hpp
