### ISSUE TITLE
removing unneeded component dependencies

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#94]
While testing deb packages I'm noticing a lot of unnecessary dependencies, and the packaging tools complain as well. e.g.,
~~~
dpkg-shlibdeps: warning: package could avoid a useless dependency if
debian/libsiconos-numerics/usr/lib/x86_64-linux-gnu/libsiconos_numerics.so.4.0.0
was not linked against liblapack.so.3 (it uses none of the library's symbols)
~~~
(hundreds of these..)

Perhaps we could figure out how to get cmake to remove unneeded libraries from certain components.  For instance, if you compile with WITH_BULLET=ON, then `ldd libsiconos_numerics.so` tells you that it links to libBulletCollision, etc., even though this is only really needed for `libsiconos_mechanics.so`.  I suspect a bit of work with refining e.g. `SICONOS_numerics_LIBRARIES` instead of throwing everything into `SICONOS_LINK_LIBRARIES` might do the trick.

Although in general I think this is non-trivial to fix.

I'll note that I get similar warnings for the Python modules:
~~~
dpkg-shlibdeps: warning: package could avoid a useless dependency if [...]debian/python-siconos/usr/lib/python2.7/dist-packages/siconos/mechanics/_joints.x86_64-linux-gnu.so were not linked against libopenblas.so.0 (they use none of the library's symbols)
~~~
etc..

**Comment by xhub** [comment]
I notice that some time ago and I was about to raise that issue.

In SiconosTools.cmake, there may be already a way: setting COMPILE_WITH_ONLY should maybe do the trick. The code looks untested.  But the macro compile_with should accept an argument telling which component requires that library, since it is usually only 1. The only example that comes to mind is BLAS/LAPACK (numerics + kernel) for sure.

Otherwise, by setting LDFLAGS='-Wl,--as-needed', the linker actually links to a library online if it provides a symbol (IIRC). I tested it locally and it worked. But the best solution is still to add the library only to the specific component.

But if we do the splitting, we have no choice but to take care of that.

**Comment by radarsat1** [comment]
Oh I forgot about `--as-needed`, I'll try that.  Might be a good stop-gap solution.  It might actually be a preferred solution from a certain point of view.. the linker is in the best place to make that kind of decision.

**Comment by xhub** [comment]
> Oh I forgot about `--as-needed`, I'll try that.  Might be a good stop-gap solution.  It might actually be a preferred solution from a certain point of view.. the linker is in the best place to make that kind of decision.

I was hoping to add some granularity by doing this (specifing the library that needs to be linked against it). Also I don't know if all linker (win, Mac OS) support that.

**Comment by radarsat1** [comment]
True, I'll have to test on other platforms.  So far it looks like it works quite well for the Debian packages!
mechanics is now the only one that `ldd` reports linking to bullet, and numerics is the only one linking to lpsolve for example. I'll leave the flag on for now.

**Comment by vacary** [comment]
Should we keep the option `--as-needed` or to try to add an argument to `compile_with` to improve a bit the linking process ?

**Comment by radarsat1** [comment]
It seems `compile_with` already supports an `ONLY` option to target specific modules.  It is used in a couple of places.  I think this is a general issue that it should be used in a more targeted way, but I'll do some more work on the Debian package soon and report whether this is still a problem in general.

**Comment by xhub** [comment]
--as-needed on platform that supports it can't be bad. But I agree that most dependency are only needed for one modules.

**Comment by xhub** [comment]
Do we think this issue is resolved?

**Comment by alexmyczko** [comment]
Will it make into buster? Freeze mid Jan 2019?

**Comment by radarsat1** [comment]
> Will it make into buster? Freeze mid Jan 2019?

I doubt it, why would you think so?  Fwiw I recently asked for review of the package.  We'll see how it goes.
