### ISSUE TITLE
[python] support building bindings for multiple python version 

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#96]
Right now we support building only against one python version. It is standard in distributions to provide both python2 and python3 bindings. We already support building against python2 and python3, but only one at a time. It would be nice to support building against multiple python versions out of the box.

We my want to use setup.py to build the python bindings, but that require some work. However, it seems to to be the de facto way of building extensions.

**Comment by radarsat1** [comment]
Agreed! On another project I call out to setup.py from the build system, it should be possible. I have never built for multiple pythons though. I think swig needs to be run with different flags for python2 and python3 so I guess it might need a bit of work to put the outputs in different directories.

**Comment by xhub** [comment]
Ok I didn't get your point, but we are on the same page. It is low priority I'd say, but migrating to using setup.py for that seems to be the way to go.

**Comment by radarsat1** [comment]
Indeed, seems that setup.py can handle building 'extensions' and passing options to swig.  Not sure if that's better or worse than running it from cmake, but if it can automatically handle multiple Pythons then maybe it's the bets way forward.  I would have to try it on a test project to see how it could work.

**Comment by fperignon** [comment]
> Le 5 janv. 2017 à 15:16, Stephen Sinclair <notifications@github.com> a écrit :
> 
> Yep, I'm aware of -py3, but my point was more that the output from swig is distinct in the two cases, so swig needs to be run once for each Python and the output stored in different places. We can't just compile the same cpp from swig for each Python.
> 
Yes, I think you’re right.
A simple(ugly) solution is to configure (cmake) first with python2 detection build and install 
and then cmake/build/install again but with python3 
which leads to siconos-python packages installed in both the python2 and python3 site-packages directories.

I’m not sure but I think that cmake just checks which python version is in the PATH and then do the proper config.
So I guess that a user with multiple versions of python will be able to switch between them (using pyenv for example) and build two
different versions of siconos-python interface.

By the way for the notebooks on https://notebook-ljk.imag.fr <https://notebook-ljk.imag.fr/> I used python3 without any change in siconos config (no -py3, just python default being python3 ) and it worked well.



> For example, currently the build directory features folders like build/numerics/swig, it will have to be changed to output build/numerics/swig-py2 and build/numerics/swig-py3. On the other hand maybe we can get setup.py to handle this for us. Right now we use cmake to run swig but perhaps setup.py could be responsible for it. I'll look into how that works.
> 
> 

I looked at this before …As far as I remember that was possible but quite painful ...

**Comment by radarsat1** [comment]
Just reading up on this, it seems even a CMake developer recommends just calling CMake twice for each Python version.  Supporting both may be next to impossible without official CMake support.  Although this is from 4 years ago, maybe things have changed, but I can't find anything more recent.

https://public.kitware.com/Bug/bug_relationship_graph.php?bug_id=13857

On the other hand I had a look at the VERBOSE=1 output for CMake running swig when set to a Python3 executable, and it does not provide the `-py3` flag as far as I can tell.

If we do want to make the effort to build both, probably the only reasonable way is to switch for calling setup.py from each supported Python and using a fake 'timestamp' target: https://bloerg.net/2012/11/10/cmake-and-distutils.html

**Comment by xhub** [comment]
> If we do want to make the effort to build both, probably the only reasonable way is to switch for calling setup.py from each supported Python and using a fake 'timestamp' target: https://bloerg.net/2012/11/10/cmake-and-distutils.html

On Gentoo, there is a support to build against multiple python install. I think the trick is to call setup.py from different interpreter. In cmake, we could loop over the python implementation requested by the user on the command line and use a buildir like build_${PYTHON_EXECUTABLE} (if PYTHON_EXECUTABLE is python2.7). The difficult part is to migrate the cmake code (swig calls + doxy2swig + ...)

**Comment by vacary** [comment]
It works now
