### ISSUE TITLE
Compilation with "-std=c++11"

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#98]
Two questions in this issue

- I want to force the compilation of siconos in C++11. The main objective is to use [delegating constructors](http://www.nullptr.me/2012/01/17/c11-delegating-constructors/) to simplify our construction process in some messy classes. Do you think that it is safe today to force C++11 ?

- The compilation fails in the compilation of the swig wrapper for numerics. It seems that the global variable verbose in [numerics_verbose.h](https://github.com/siconos/siconos/blob/master/numerics/src/tools/numerics_verbose.h) is prefixed with tlsvar defined in [tlsdef.h](https://github.com/siconos/siconos/blob/master/numerics/src/tools/tlsdef.h ). When we compiled numerics in C, tlsvar is defined as __thead but when we compile the swig wrapper tlsvar is defined but empty. Why we define tslvar as empty if SWIG is defined ? could we change that or not ? At least it compiles when  SWIG is defined and tlsvar set to  __thread.

**Comment by radarsat1** [comment]
I would love to use C++11 more ;)  However it's a matter of how old a system we want to support.  We would have to require GCC 4.6 or later.  It's been a while since I tried with the std=c++11 flag, I will try and let you know.  Gazebo uses C++11 so I've been using the headers with that flag enabled without problems.

**Comment by radarsat1** [comment]
Here's where to look to see what version of GCC we would require for certain C++11 features: https://gcc.gnu.org/projects/cxx-status.html#cxx11

Some things I think we could benefit from on the surface are simplifying the expression of iterating over the dynamical system graph via range-based for, and initializer lists for SiconosVector.  However, I have wondered if visitors could be simplified a great deal in the long run .. but I have no proposal as of yet.  I do think we should be moving to std shared_ptrs and using make_shared more.

**Comment by xhub** [comment]
The minimal version for delegating constructor is 4.7, cf https://gcc.gnu.org/projects/cxx-status.html#cxx11

I think that we should either allow the full c++11, which means requiring a newer GCC/clang, or having a CI test with a given compiler that we define as the minimum we require.


For the tlsvar issue, Iirc I had issue with older versions of swig. First I can reproduce the issue. Second is that swig does not need to know about this tlsvar. Could you post the error you got?

I don't have a lot of time this week to look into that.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by radarsat1** [comment]
I managed to compile with std=c++11.  Some issues with isnan/isinf.  I made some corrections to the StdCxx.hpp file, I will post them tomorrow after testing more thoroughly.  (A bit scared to touch that one.. but the ::isnan thing seems wrong to me for C++11, should #include <cmath> and use std::isnan.)

No issues with swig as far as I can tell.  Vincent what version of swig are you using?

**Comment by bremond** [comment]
just a pointer to compilers support for c++{11,14,17}

http://en.cppreference.com/w/cpp/compiler_support

**Comment by radarsat1** [comment]
One approach could be to start making proposed c++11 changes on a branch, exclude those changes from 4.1.0, and plan to move to C++11 in 4.2.0.  (5?)  With a big warning in the release docs that future versions will drop support for old compilers..

Not sure if it's necessary.  We can't know about users that don't communicate, but for those that do, what are the current restrictions e.g. for compute clusters that are in use?  What operating system versions do they run?

On the cluster here in Chile when I was testing, it did have an old gcc.  I actually downloaded and compiled and a new gcc and boost, and installed them in the $HOME.  It worked fine.  So all is not lost, even for older systems.

**Comment by xhub** [comment]
I believe the only drawback is that we loose support for old compiler, like the one that are on cluster. But I don't think this should hold us. On Ubuntu 14.04, the previous LTS, gcc 4.8.4 is used to compile. The support for c++11 is fairly complete. I would be in favor or using quite a lot of the c++11 features.

For major changes, I would try in a branch. We should assess the import of using some of the keywords, like with swig and serialization.

**Comment by xhub** [comment]
@vacary Do you still have issues with tlsvar in the wrapper?

**Comment by vacary** [comment]
yes, I still the problem since we are using the C compiler for compiling numerics and the C++ compiler for compiling its swig wrapper. I get 
`  4%] Built target externals
[ 48%] Built target numerics
[ 48%] Generating ../wrap/siconos/numerics-docstrings.i
[ 48%] Built target numerics_docstrings
[ 48%] Building CXX object numerics/swig/CMakeFiles/_fclib.dir/__/__/wrap/siconos/fclibPYTHON_wrap.cxx.o
[ 48%] Linking CXX shared module ../../wrap/siconos/_fclib.so
[ 48%] Built target _fclib
[ 48%] Swig source
Scanning dependencies of target _numerics
[ 49%] Building CXX object numerics/swig/CMakeFiles/_numerics.dir/__/__/wrap/siconos/numericsPYTHON_wrap.cxx.o
[ 49%] Linking CXX shared module ../../wrap/siconos/_numerics.so
Undefined symbols for architecture x86_64:
  "__ZTW7verbose", referenced from:
      Swig_var_verbose_get() in numericsPYTHON_wrap.cxx.o
      Swig_var_verbose_set(_object*) in numericsPYTHON_wrap.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [wrap/siconos/_numerics.so] Error 1
make[1]: *** [numerics/swig/CMakeFiles/_numerics.dir/all] Error 2
make: *** [all] Error 2`

We have the choices 
+ linking the interface in C
+ compiling numerics in C++

**Comment by radarsat1** [comment]
what if in numerics.i you change this
~~~
%{
#include "SiconosNumerics.h"
#include "SiconosConfig.h"
#include "SolverOptions.h"
#include "SparseMatrix.h"
#include "NumericsMatrix.h"
#include "SparseBlockMatrix.h"
#include "NumericsSparseMatrix.h"
#include "Numerics_functions.h"
#include "SiconosSets.h"
#include "GAMSlink.h"
#include "NumericsFwd.h"
%}                    
~~~
to
~~~
%{
#ifdef __cplusplus
extern "C" {
#endif
#include "SiconosNumerics.h"
#include "SiconosConfig.h"
#include "SolverOptions.h"
#include "SparseMatrix.h"
#include "NumericsMatrix.h"
#include "SparseBlockMatrix.h"
#include "NumericsSparseMatrix.h"
#include "Numerics_functions.h"
#include "SiconosSets.h"
#include "GAMSlink.h"
#include "NumericsFwd.h"
#ifdef __cplusplus
}
#endif
%}                    
~~~
does it help?

**Comment by xhub** [comment]
Ok with 7ec76fa66 we now compile numerics in C. It's going to break when we need to build numerics in C++ mode, but I should have a fix for that ready

**Comment by xhub** [comment]
Is it still failing now?

**Comment by vacary** [comment]
It compiles now!! Thanks
